### ISSUE TITLE
'@directus/app' package seems to declare build dependencies as regular dependencies

### ISSUE THREAD

**Issue by kherock** [directus/next#1000]
I noticed that I was getting a peer dependency warning on install for `stylelint-config-prettier`, but to me it looks like all of the dependencies in [`@directus/app/package.json`](https://github.com/directus/next/blob/main/app/package.json) should be listed as dev dependencies. The only files published are the webpack chunks with dependencies bundled in.

**Comment by rijkvanzanten** [comment]
![](https://media.giphy.com/media/l46Cx2dkVXaoPibtK/giphy.gif)

**Comment by rijkvanzanten** [comment]
@kherock 

> seems to declare build dependencies as regular dependencies

Nah that's false. `stylelint-config-prettier` seems to have slipped through the cracks, but generally speaking all dev dependencies are defined in the root of the monorepo

**Comment by rijkvanzanten** [comment]
> The only files published are the webpack chunks with dependencies bundled in.

Very good point, hadn't thought about that 👍
