### ISSUE TITLE
RC-14: Error running install script - cannot read property 'overview' of undefined

### ISSUE THREAD

**Issue by lluishi93** [directus/next#1001]
Using the following script:

```bash
install () {
    local email="admin@example.com"
    local password="1234"

    npx directus database install
    local role=$(npx directus roles create --name Administrator --admin)
    npx directus users create --email "${email}" --password "${password}" --role "${role}"

    echo "Email: ${email}"
    echo "Password: ${password}"
}

install
```

I got the following error:

![image](https://user-images.githubusercontent.com/14786440/99236344-5fa53500-27f7-11eb-9287-e78d7976fd14.png)

Edit: The failing command is `npx directus users create --email "${email}" --password "${password}" --role "${role}"`

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/next/pull/996
