### ISSUE TITLE
RC-14: unable to select related collection fields when creating m2m

### ISSUE THREAD

**Issue by lluishi93** [directus/next#1002]
1. Create collection a
2. Create collection b
3. Create a m2m field in collection a pointing to collection b
4. Check that the first time you set it up, you're unable to select fields in the inteface step:

![image](https://user-images.githubusercontent.com/14786440/99270214-d73e8880-2826-11eb-9337-71ca3c97b9ef.png)

**Comment by rijkvanzanten** [comment]
This is expected, as the junction table that you're about to create doesn't exist.. (yet)

**Comment by lluishi93** [comment]
Technically it is expected, but IMHO it is not the best UX. Could showing the fields from that collection be possible, even if the junction table is not created yet? Reading from the directus_fields table maybe?
