### ISSUE TITLE
Activity Page

### ISSUE THREAD

**Issue by benhaynes** [directus/next#101]
Ideally should use the standard Browse page (with any needed magic). Eventually we'll want to add in a timeline Layout, but for now we can just use the Table layout.

Magic...
* Clicking an item would open a modal
* Detail modal: Include a big button at the top for navigating to the edited item

**Comment by rijkvanzanten** [comment]
Activity page was added in https://github.com/directus/next/commit/166d5df39e7892ad8c69e72c90b78629f24bd52a
