### ISSUE TITLE
Throw error when required field not set

### ISSUE THREAD

**Issue by jekuer** [directus/next#1010]
Reproduce by:

1. Creating a standard field and make it required.
2. Create another standard field not required.
3. Try to save a new item with only filling the non-required field.
4. Saving the item will lead to an error in the console, but without any feedback at UI level.

RC14

**Comment by rijkvanzanten** [comment]
Lets track this as a single "show uncaught errors on items" ticket :)

**Comment by rijkvanzanten** [comment]
Closed in favor of #1009
