### ISSUE TITLE
Add option to update original file

### ISSUE THREAD

**Issue by benhaynes** [directus/next#105]
Add an option to the File Detail page so that you can upload a new file to replace the source. This should **not** change the PK, relational references, or other field data... just the file itself.

This should be added to the "Information" sidebar section as `File: [Open] or [Replace]` (Under "Folder")

* "Open" would open the original in a new tab
* "Replace" would open an upload modal to overwrite

**Comment by benhaynes** [comment]
Sorry, this ticket was a bit outdated... 😬  Here's a more ideal way to handle this on the File Detail page:

* Clicking on the image preview (main image) should open the upload dialog (not the preview)
* The upload dialog should include a v-notice below that upload area that says "This replaces the original file, maintaining all existing relationships".
* Let's add a "File" (below "Folder") that links to the file (via the middleware). This should open in a new tab, not download (@rijkvanzanten will add a query parameter to allow this)
* Update "Folder" to _link_ to the folder page (we don't need "Move Folder" here since there's an action button for that)

**Comment by rijkvanzanten** [comment]
Query param for assets will be `download=true` (default to false)

**Comment by Nitwel** [comment]
Sounds good. 👍
