### ISSUE TITLE
Add displays/formatting for hidden fields in File Library

### ISSUE THREAD

**Issue by benhaynes** [directus/next#108]
Currently seen in modal revision review. These should at least be `half`, and ideally include icons/displays/options.

**Comment by rijkvanzanten** [comment]
Can be added right here:

> https://github.com/directus/next/blob/30ced3e3afc19fab59ac28b4b5af164ced0d9a94/api/src/database/seeds/system.yaml#L1436

**Comment by benhaynes** [comment]
This should be an easy one to close, @Nitwel ...
