### ISSUE TITLE
Create static thumbnails of animated GIFs

### ISSUE THREAD

**Issue by benhaynes** [directus/next#109]
Currently, GIFs are shown as-is in the File Library. This means that you could be loading a LOT of data (eg: 1-3MB each x100+ items) on the browse page. We should find a way to render a static thumbnail for these. Animated GIFs can just be the first frame.

**Comment by rijkvanzanten** [comment]
> We should find a way to render a static thumbnail for these.

Ideally, the asset endpoint can actually resize the thumbnails instead of just return a static image
