### ISSUE TITLE
ESC to close all notifications/modals

### ISSUE THREAD

**Issue by benhaynes** [directus/next#120]
**When available**, the escape key should close all modals, overlays, and confirmations.

**Comment by rijkvanzanten** [comment]
* Only close the top-most modal
* Only close "when available" means based on the content / context of the modal/dialog. Has to be added on a per-dialog context instead of global

**Comment by benhaynes** [comment]
@Nitwel — you were handling a lot of keyboard shortcut stuff, do you think you can take this on?

**Comment by Nitwel** [comment]
Oh, this is done I think haha.
As far as I know all modals/popups use the dialog component and it is implemented there so we should be able to close this?

**Comment by benhaynes** [comment]
Haha, so confident!

The first place I tried it didn't work 😬 

http://localhost:8080/admin/settings/data-model/+

**Comment by Nitwel** [comment]
Oh this is on purpose. You get the jump effect instead because the modal is set to persistent.

**Comment by benhaynes** [comment]
Hmm, not sure about that... wouldn't that mean it doesn't have a "Cancel" button? This can be cancelled with a click of that button, so we should be consistent with this.

**Comment by Nitwel** [comment]
Persistent means it can't be closed when clicking outside the modal.

**Comment by Nitwel** [comment]
If you want to try this out add a m2m collection, there you can have infinite modals by having that interface on both sides and clicking on add new.

**Comment by benhaynes** [comment]
Gotcha, so I guess we should review the usage of `persistent` in cases like these. I'd say for "Creating a Collection" we can remove the `persistent` flag, since there's not a _huge_ amount of data that would be accidentally lost by cancelling. That is, unless @rijkvanzanten has any objections. 😄

**Comment by rijkvanzanten** [comment]
Persistent !== the ability to cancel

The new collection modal for example has a cancel button, and should therefore also accept `esc`. `persistent` means that you can't click the smoke to cancel the modal. This is effectively added in every modal that has a "next". It's super easy to accidentally overshoot the next button with the mouse slightly, and click the smoke, therefore trashing all your progress. However, `esc` is a more deliberate action, and should trigger `cancel`

**Comment by Nitwel** [comment]
As far as I remember you said that I sould add that it doesn't close if persistent but I could be also mistaken something.
Always closing the modal on esc would be just a single line of code change.
Should I create that PR?

**Comment by rijkvanzanten** [comment]
> Always closing the modal on esc would be just a single line of code change.

This is not the case though, it should cancel the modal if the option to cancel already exists, otherwise it shouldn't

**Comment by Nitwel** [comment]
How do we check if the cancel option exists if this is done via  a slot?

**Comment by rijkvanzanten** [comment]
I think we'll have to do it on a case by case, just like with dialogs

**Comment by Nitwel** [comment]
So a prop that enables/disables the functionallity of pressing esc?

**Comment by rijkvanzanten** [comment]
No, cause cancel can do different things.

We should add an escape event on v-modal that the use of v-modal can then attach to the existing cancel method
