### ISSUE TITLE
Unbranded FavIcons

### ISSUE THREAD

**Issue by benhaynes** [directus/next#125]
Just use a colored circle as favicon (no rabbit) if project logo is uploaded. See Figma below for full favicon versions that include states for no-auth, notifications, etc. 

![Screen Shot 2020-08-13 at 2 38 16 PM](https://user-images.githubusercontent.com/522079/90173599-b0c60880-dd72-11ea-8cde-2c0a55ef7529.png)

**Comment by benhaynes** [comment]
Actually, I prefer this for notification count...

![Screen Shot 2020-08-13 at 3 06 57 PM](https://user-images.githubusercontent.com/522079/90176273-b1f93480-dd76-11ea-9088-94c3f6b55161.png)

**Comment by rijkvanzanten** [comment]
This was implemented
