### ISSUE TITLE
Don't allow duplicate field / collection names

### ISSUE THREAD

**Issue by benhaynes** [directus/next#129]
When creating a new field, we need to LIVE check that there are no existing fields with that key, and that is passes the requirements of SQL columns. This should then show a primary check (good) or danger "X" (bad) and disable the "Next" button as needed.

**Comment by rijkvanzanten** [comment]
API should check for existence before trying to DDL

**Comment by rijkvanzanten** [comment]
This was added in https://github.com/directus/next/commit/5bd7177d5afafc9e3ccab249a3cf97e290b88b22
