### ISSUE TITLE
Add password support for files/folders

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#13]
Allows folders / files to be password protected, allowing the user to make a folder/file private

**Comment by benhaynes** [comment]
@rijkvanzanten — is this a new feature? Didn't we have private files (via the URL) in v8? Or is this based on permissions?

**Comment by rijkvanzanten** [comment]
This is a new feature. It's a way to make files "public" (eg you don't need an account), but still "private" (eg you need a password to download the file).

It's effectively a way to share files "privately publicly" to people outside of Directus
