### ISSUE TITLE
Saving all preset activity

### ISSUE THREAD

**Issue by benhaynes** [directus/next#133]
Currently, the App is saving all preset activity to the DB... eg: for ever sort/change of a layout.

![Screen Shot 2020-08-14 at 6 22 08 PM](https://user-images.githubusercontent.com/522079/90297014-391fd880-de5b-11ea-9337-c677e54dccb7.png)

**Comment by rijkvanzanten** [comment]
This is not a bug, but the expected behavior. 

I'm down to discuss an allow list for specific collections to track.

**Comment by benhaynes** [comment]
Fair enough... _technically_. 😉 

But yes, we need to have a _per-collection_ filter on the activity page, with `directus_presets` off by default, and/or let's add a block list of which system collections do not need to be tracked. I think `directus_presets` should not be stored at all, it seems like useless data and with a decent number of users will swamp the activity and revisions tables just from people browsing data. For the rest, we can have filters on the Activity Log page.

**Comment by rijkvanzanten** [comment]
User presets shouldn't be tracked when they're saved by using the app "regularly", but we might want to save revisions for them if an admin sets them up explicitly through settings.. 🤔
 
Maybe we should do a similar thing as user tracking where there's a dedicated "save preset for current user" endpoint that doesn't save revisions 🤔

I believe we'd want to track activity and revisions for nearly all system tables, with the exception being user-last-page and presets (when saved during app usage)

**Comment by benhaynes** [comment]
Agree, `directus_users.last_page` and `directus_presets` are the only outliers. I'm fine not tracking all of presets, but if you'd rather save the admin changes for them, that's fine too.

Also, do we still have`directus_users.last_access`? That was used to calculate if a user is still logged on (for a user "online" badge)... did we have a new way to get that info? If we add that back, it would _also_ not be tracked.

**Comment by rijkvanzanten** [comment]
We won't add any custom logic for certain system collections. Instead, we'll rely on https://github.com/directus/next/discussions/259 to handle this in the future
