### ISSUE TITLE
Support manual sorting for items

### ISSUE THREAD

**Issue by benhaynes** [directus/next#140]
We need to add a field to `directus_collections` to track the field that will handle sorting, and make sure we have the displays work with this feature.

I think having sort turned on adds the item handles to appropriate layouts (only Table for now, Cards later), but the field continues can work as usual... so you can technically still have it on the Browse/Detail if you want (though this should be off by default, I think... see below).

We also need to update "sort" from the Create Collection modal of starter fields so that it:
1. Creates the field (standard int called `sort`)
2. Sets the Collection sort field
3. Sets the field to hidden on browse and detail

**Comment by rijkvanzanten** [comment]
Added in #152
