### ISSUE TITLE
Add ability to create ALIAS fields

### ISSUE THREAD

**Issue by benhaynes** [directus/next#143]
Add a "Add Alias Field" to the "Create Field" dropdown. Conditionally adapt the "schema" pane in the Create Field modal to only show "key", "type" (hardcoded to alias) and "note"?, then to to Interfaces limited by the alias type.

**Comment by rijkvanzanten** [comment]
Note (to self): the interfaces shown should _not_ include the relational interfaces. Those are technically aliases, but shouldn't be considered in the "alias" list
