### ISSUE TITLE
Add modified_on to directus_files

### ISSUE THREAD

**Issue by benhaynes** [directus/next#144]
* Add “Modified On” to File Info sidebar
* Also add a cache-buster based on this to thumbnails

**Comment by Nitwel** [comment]
I don't think this is in my range of skills yet. 😐 
@rijkvanzanten could you help me out here?

**Comment by rijkvanzanten** [comment]
* Add `modified_on` field in seeds under `api/src/database/seeds/01-tables/07-files.yaml`
* Add row for `modified_on` in `api/src/database/seeds/03-fields/05-files.yaml`
  * Set `special to `date-updated`
* Add `modified_on` to the field deny list on `app/src/modules/files/routes/detail.vue` L269
* Add modified date to `app/src/modules/files/components/file-info-drawer-detail.vue` the same was as `creationDate` that already exists

**Comment by Nitwel** [comment]
Do we really want to add this because revisions already contains all that functionallity?
We could even remove uploaded_on/_by.
![grafik](https://user-images.githubusercontent.com/22577866/95358883-d2062980-08c9-11eb-8697-49fda1a3d4c7.png)

**Comment by benhaynes** [comment]
Yes, because we need actual fields for sorting/filtering (on Collection Detail page).Revisions gives this info, but the created date could be buried if you have many revisions. I think it's pretty standard to have date created/modified in the metadata for files.

**Comment by Nitwel** [comment]
👍 There are also created_on/_by fields which currently are not shown inside the file view. Is this on puropse?

**Comment by benhaynes** [comment]
Yeah, none of those should be on the form... only in the file info sidebar, here:

![Screen Shot 2020-10-07 at 12 41 24 PM](https://user-images.githubusercontent.com/522079/95361208-6eb0d300-089a-11eb-92d1-518ccb80e75c.png)

**Comment by Nitwel** [comment]
Yep, I just noticed that too. 😄
Was just a bit confused why @rijkvanzanten wrote:
> Add row for modified_on in api/src/database/seeds/03-fields/05-files.yaml
> Set special to date-updated`
But I think we don't want to have that.
