### ISSUE TITLE
Item Browse: "Select All Items" keyboard shortcut should not trigger within filter input

### ISSUE THREAD

**Issue by benhaynes** [directus/next#147]
If you are in an advanced filter input and META-A to select all that text, it will actually select all the items on the browse page. We need to find a way to scope these shortcuts.

**Comment by rijkvanzanten** [comment]
Note (to self): this doesn't apply to all shortcuts globally, fe cmd+s should still save, even when you're in an input on the edit form

**Comment by rijkvanzanten** [comment]
Closed in favor of #235
