### ISSUE TITLE
Managed/Unmanaged collections/fields

### ISSUE THREAD

**Issue by benhaynes** [directus/next#149]
See Figma.

I realize this is part of a bigger conversation regarding how to handle managed/unmanaged database tables and columns. High-level: do we show them OOTB, or have Admins turn them on manually. Could this be a global setting? The worry with all being shown immediately is that the admin has less control over creating things and not having it impact users (and it's annoying to setup permissions before you create the actual table/column).

**Comment by rijkvanzanten** [comment]
By default, non-admin users don't have (read) permissions to anything, so nothing will show up until an admin sets up permissions for this user. I don't think the 

> the admin has less control over creating things and not having it impact users

part applies

**Comment by rijkvanzanten** [comment]
There's no technical difference between "managed" and "unmanaged" as of right now

**Comment by benhaynes** [comment]
Your statement is mostly correct, but there are a few instances that stand out:

* User permissions will eventually support `*`, which would make this relevant
* This may be an issue for Admin Users (who have that support)
    * Now that "Admin Access" is a flag for all Roles, I could imagine that being used more too. Speaking of, if a role gets admin access, will it disable all permissions and give them all access? At that point, what's the difference between admin roles? Just naming?

Just a reminder that the reason for this feature was to avoid "temp" or unrelated database tables to not show up in Directus at all. We could also consider simplifying all this with a "table_deny_list" in the env file. Just a thought.

All this said, it seems like it reduces complexity a lot to remove this feature and just rely on permissions for this. That also seems to be your preference. Thoughts on all this?

**Comment by benhaynes** [comment]
@rijkvanzanten — didn't we come to a conclusion and resolve this?

**Comment by rijkvanzanten** [comment]
Yup!
