### ISSUE TITLE
Re-install doesn't work because of foreign-keys

### ISSUE THREAD

**Issue by shealavington** [directus/next#150]
When attempting to re-install Directus9 onto an existing Directus9 instance, there's an error because of the existing foreign keys.

Messages from Discord:

![image](https://user-images.githubusercontent.com/16869302/90518460-b9e21b80-e15e-11ea-8f8b-41f673dfa228.png)

After collections broke, attempted a re-install on an existing database

_apiraino_  
@Shea there are foreign keys in your DB blocking the init script. Not sure it helps but in my DB init scripts I usually exclude them at the beginning of the procedure and enable them back at the end, something like this:

```sql
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- DROP TABLE IF EXISTS ....
-- CREATE TABLE ...
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
```

maybe the init scripts can be modified? Not sure

_Shea_  
That'd be something for the team to look at, I'm not running anything custom any FK's are Directus created :slight_smile:

_apiraino_  
yes, probably worth filing a bug report (or a patch)

_kukulaka_  
Yup @Shea , please log this and I'll have a look at it. :slight_smile: This is mySQL?

_Rijk_  
The installer tries doing a drop table if exists  if you install it on an existing v9 instance currently, but that seems to fail due to the foreign key constraints

_WoLfulus_  
dropping tables with fk needs specific order
also a pain when there's cross references which directus does in some cases
disabling in that case seems best way to do it
since you're trying to drop everything

_Rijk_  
If you're force reinstalling it on an existing Directus install, it should just disable the foreign key constraints  
yeah exactly  

_WoLfulus_  
it's vendor specific though  
they way you do it

**Comment by rijkvanzanten** [comment]
We've updated the CLI to show an error instead of crash and burn, and allow you to retry after it fails, allowing the user to clear their DB before installing Directus. I'll start a discussion to see how we can support purging the DB automatically on install
