### ISSUE TITLE
Cannot update and show Time field (PostgreSQL)

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#155]
Hello

When trying to update time field in PostgreSQL getting an exception:

`{"error":{"code":"INTERNAL_SERVER_ERROR","message":"update \"working_hours\" set \"open_time\" = $1 where \"id\" in ($2) - invalid input syntax for type time: \"2020-08-19T01:52:05+03:00\""}}`

The field itself is of a type `Time` in PostgreSQL therefore we should not be passing date part at all. Additionally, those values that are already entered in PostgreSQL are not rendering correctly and show NAN.

![image](https://user-images.githubusercontent.com/11473040/90626385-91702500-e223-11ea-84f1-a85bf4f1fe54.png)

**Comment by rijkvanzanten** [comment]
Fixed in #438
