### ISSUE TITLE
Duplicated requests to API when entering collection

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#169]
Hi,

I have noticed that requests are duplicated when navigating into the collection.

![image](https://user-images.githubusercontent.com/11473040/91226632-f77e1000-e72d-11ea-9d32-0e6cc937dfe3.png)

The number of requests seems to be (partially) dependant on Records Per Page setting. For example, I can see the same request being executed 5 times when I change Records Per Page to 250.

![image](https://user-images.githubusercontent.com/11473040/91226799-2eecbc80-e72e-11ea-97b1-2e3aaa2d2618.png)

**Comment by rijkvanzanten** [comment]
> For example, I can see the same request being executed 5 times when I change Records Per Page to 250.

@dmitrijsc Are you saying that it makes 5 requests when you navigate to the page, or do you see this behavior when changing the records-per-page option? I'm having some trouble reproducing this

**Comment by dmitrijsc** [comment]
Create a collection with over than 100 records. It shows only one query when all records fit on one page.

**Comment by rijkvanzanten** [comment]
Are the requests in your screenshot ordered alphabetically, or by when they were fired @dmitrijsc? I can't seem to reproduce it still..

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-09-18 at 16 22 03](https://user-images.githubusercontent.com/9141017/93641922-2608a700-f9cb-11ea-8514-92674ba59e33.png)

The app does make 2 different requests when you open a page (1 for the actual data, 1 for the item counts), but they aren't duplicated on my end

**Comment by rijkvanzanten** [comment]
I'll close this for now, as I suspect that's where the confusion might've come from. We can reopen if i'm wrong :)
