### ISSUE TITLE
SQL error when filtering on relationship

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#176]
Hello

When running a filter query over a relationship it fails with an error described below.
DB: postgres, build 21.

URL:
`http://localhost:41201/items/tests?limit=25&fields=*.*&access_token=XXX&filter[qualification_id.match_type][_eq]=1`

Error:
```
{
  "error": {
    "code": "INTERNAL_SERVER_ERROR",
    "message": "select *, \"qq\", \"qualification_id\", \"id\" from \"tests\" where \"qualification_id\".\"match_type\" = $1 order by \"id\" 
asc limit $2 - missing FROM-clause entry for table \"qualification_id\""
  }
}
```

**Comment by rijkvanzanten** [comment]
Not technically a bug, seeing I haven't implemented it in the API yet 👉🏻👈🏻 

I'll consider it a bug though, seeing it's surfaced in the app already  😁
