### ISSUE TITLE
Bearer token does not work when the word is Bearer written in lowercase

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#177]
Hello, 

Version 9 requires writing Bearer with capital B, the same time v8 supports both options.
https://docs.directus.io/api/reference.html#authentication

https://github.com/directus/next/blob/cb92a078b0ae2b535741ec1fe3f4c727d438c7ab/api/src/middleware/extract-token.ts

**Comment by rijkvanzanten** [comment]
This is intended. I'm trying to have less variation in settings like this to simplify usage/docs/maintenance. The same goes for no longer supporting aliases in filters like `=` for `_eq` etc
