### ISSUE TITLE
Unable to save translations in data model

### ISSUE THREAD

**Issue by lluishi93** [directus/next#180]
When I try to add a translation, the app gets stuck and does not save the changes.

Version: v9.0.0-alpha.33
DB engine: SQLite

Edit: here's the trace I get from the backend when trying to create a translation:

```
{"errors":[{"message":"Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

**Comment by rijkvanzanten** [comment]
I believe this might be caused by https://github.com/directus/next/issues/141
