### ISSUE TITLE
Dark Mode: Issues to Resolve

### ISSUE THREAD

**Issue by benhaynes** [directus/next#187]
Placeholder User image should be conditionally applied (or made into icon)

**Comment by Nitwel** [comment]
I'm not really sure what you mean by placeholder user image.
Where should it be applied? (Interface, Display...)
On what condition? Dark/Light mode?
![grafik](https://user-images.githubusercontent.com/22577866/94543640-9c6a9c00-024a-11eb-8360-5865bb594d24.png)
This is already using an icon and no image.

**Comment by benhaynes** [comment]
In v8 we had a image that was returned when no user image was available... did we get rid of that in v9 @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
I think that was in the user display

**Comment by benhaynes** [comment]
Can we update the app to use the icon for all user fallbacks? I think the browse+detail does already...

I'd prefer to remove the fall-back if possible, it doesn't play well with dark mode anyway.

**Comment by rijkvanzanten** [comment]
It was an issue of sizing. We can't have a gray background that's perfectly square if we use an icon in the display. The display has to be 100% height to work within the different contexts, but you can't set a thing to `width: height`

**Comment by Nitwel** [comment]
What about that `padding-top: 100%` trick?

**Comment by rijkvanzanten** [comment]
That allows you to set the height based on the width, but not vice versa </3

**Comment by benhaynes** [comment]
What about a transparent gif/png for the sizing, but we style with icons so we have CSS control over the styling?

**Comment by benhaynes** [comment]
@rijkvanzanten @Nitwel — thoughts on the empty GIF/PNG approach? I'd love to get the image placeholder out of the codebase.

**Comment by Nitwel** [comment]
We could also use an SVG for this I think.

**Comment by benhaynes** [comment]
In that case we could probably just do it inline with code, right? That works for me!

**Comment by Nitwel** [comment]
I have to try that out but yes. If that doesn't work I would just use a 1x1 Image.

**Comment by Nitwel** [comment]
I'm still not seeing where it does not adapt to the dark mode.
I checked the display, Interface (modal), users page, single user page, revisions and so on and couldn't find what is looking wrong?
![grafik](https://user-images.githubusercontent.com/22577866/95447619-47bdd400-0962-11eb-98d2-e49ba7ddbf3a.png)

**Comment by benhaynes** [comment]
Not sure where/how it's used, but I'd like to get rid of these:

https://github.com/directus/next/blob/main/app/src/assets/avatar-placeholder.svg
https://github.com/directus/next/blob/main/app/src/displays/user/user.vue#L13

**Comment by rijkvanzanten** [comment]
@Nitwel [like I said above](https://github.com/directus/next/issues/187#issuecomment-700718269) it's in the user display 🙂

**Comment by Nitwel** [comment]
Oh, I got a bit confused over here cause the small icon wouldn't render at all if unset.

**Comment by Nitwel** [comment]
Okay, so I tried 1x1 px, a custom directive and some other ways but nothing could fix this. I removed the background of that svg so it matches the dark mode.
![grafik](https://user-images.githubusercontent.com/22577866/95510454-3999a300-09b6-11eb-9804-5d4d3ea5a5ba.png)
![grafik](https://user-images.githubusercontent.com/22577866/95510472-44ecce80-09b6-11eb-9cac-badca172ac7d.png)
