### ISSUE TITLE
Keep field spacing when no label

### ISSUE THREAD

**Issue by benhaynes** [directus/next#188]
![Screen Shot 2020-08-31 at 2 18 36 PM](https://user-images.githubusercontent.com/522079/91752892-054fed00-eb95-11ea-98ce-bf0253ed0640.png)

**Comment by rijkvanzanten** [comment]
This does mean that there will be more "top margin" if you have a full width divider for example 🤔

**Comment by benhaynes** [comment]
Ideally this change ONLY applies if there is an adjacent field WITH a label (not full width fields with no label, or if both half fields have no label).

**Comment by Nitwel** [comment]
Should there be fields with no label in general, I can't think of a case where we would need this right now.

**Comment by benhaynes** [comment]
Yeah: dividers, notices, certain aliases, and other presentation fields...

**Comment by Nitwel** [comment]
Oh right, as on the image. 🤦‍♂️
