### ISSUE TITLE
Last login is null

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#192]
Should be saved with the timestamp on login (not refresh)

**Comment by benhaynes** [comment]
Not sure how we want to handle this, but the main reason for this field (or maybe it was the `last_access` was to know if a user is online or not. eg: `last_access` is within the last 1 minute.

Do we want a separate field for this? Can we do it through another means? I can add a ticket... but ALL avatars/user references in the App should have the green online dot indicator if/when they are online.

**Comment by benhaynes** [comment]
Yeah! And we can get logins from `activity`, right?

**Comment by rijkvanzanten** [comment]
We can get active user sessions from `directus_sessions` :)

**Comment by benhaynes** [comment]
Ohh, even better! that sounds more accurate for idle users. Maybe we use sessions for "online" (green) and `last_access` (if we keep that) for if they are "idle" (yellow) or not (eg: actually using the App in the past X minutes).
