### ISSUE TITLE
Route not found for /auth/refresh

### ISSUE THREAD

**Issue by kukulaka** [directus/next#2]
When accessing app  using SQLite  for database API call is returning 500 on the route /auth/refresh

This is returned
```
{"error":{"code":"ROUTE_NOT_FOUND","message":"Route /auth/refresh doesn't exist."}}
```

**Comment by rijkvanzanten** [comment]
Can you accurately reproduce this @kukulaka?

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this
