### ISSUE TITLE
More helpful error messages

### ISSUE THREAD

**Issue by reddo** [directus/next#206]
Tried to save a collection without filling all the fields and all I got was:

![image](https://user-images.githubusercontent.com/1180060/92281361-18035280-ef04-11ea-9d09-f191369faf25.png)

Consider adding more descriptive error messages like "Field x, and z can not be empty".

**Comment by benhaynes** [comment]
We actually would like to take this one step further for 9.0, and have the API error response return enough information to highlight the specific fields with specific errors. Then the notification itself can be more general.
