### ISSUE TITLE
Collection image preview missing in admin

### ISSUE THREAD

**Issue by reddo** [directus/next#208]
I have a collection which has images, the list in admin is missing the image:

![image](https://user-images.githubusercontent.com/1180060/92310484-a4bb1880-efb7-11ea-9f05-6ca78766698d.png)

The Request URL is `http://localhost:41201/assets/undefined?key=system-small-cover` and it's returning a `403 Forbidden`

**Comment by benhaynes** [comment]
Interesting. Not only should this be fixed — if possible, I would like the App to fallback to an "error placeholder" image for any broken assets.

**Comment by reddo** [comment]
I've created the app yesterday, so it should be the latest.
I'm using `"directus": "^9.0.0-alpha.32",` according to package.json.

**Comment by rijkvanzanten** [comment]
I believe this was since fixed

![CleanShot 2020-09-18 at 15 23 20](https://user-images.githubusercontent.com/9141017/93637024-e473fe00-f9c2-11ea-88ed-3e8f57941ee9.png)
