### ISSUE TITLE
Repeater field issues

### ISSUE THREAD

**Issue by reddo** [directus/next#209]
I have set up a repeater field with a multi-select and a text field.

The first issue I have is that the multi-select dropdown closes when I select one option, having to open it if I want to select more than one option.

The other is that I've added a simple text field with these options

![image](https://user-images.githubusercontent.com/1180060/92312848-89f39e80-efcd-11ea-82fc-32d029e8f24e.png)

And when I go and add value, it looks like a password input for some reason:

![image](https://user-images.githubusercontent.com/1180060/92312902-228a1e80-efce-11ea-9608-99bdeca8b8b8.png)
![image](https://user-images.githubusercontent.com/1180060/92312911-2b7af000-efce-11ea-97a5-a81b7be32068.png)

Weirdly, removing that field and adding a new one fixed the second issue

**Comment by Nitwel** [comment]
The dropdown closing after clicking should be resolved.
The second one I could not recreate. It might have been that you had enabled that option by mistake but I'm not sure.
If you run into either issue again, I can reopen this issue but other than that all seems fine.
