### ISSUE TITLE
Add /system/import / /system/export endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#21]
Should be able to import / export data and/or schema. Should have a way to specify what data/schema to export/import

**Comment by WoLfulus** [comment]
I played a little bit with this in PHP side already. The easiest way I found was to get it to implement a yaml with the structure that GraphQL receives as its inputs. Then automating the requests gets everything setup pretty quickly.

I haven't thought about initial data seeds though.

ref: 
https://github.com/directus/api-next/blob/master/examples/blog.yml
https://github.com/directus/api-next/blob/master/src/Console/ImportCommand.php

**Comment by rijkvanzanten** [comment]
Exporting can ideally be done to a configurable format (Yaml / JSON / CSV). Yaml is great for static (/ handwritten) seeds etc, but not the most friendly when exporting/importing between different systems 🤔 

As for the initial data seeds, I think you can copy/rely on the one the node one uses: https://github.com/directus/next/blob/main/api/src/database/seeds/system.yaml

**Comment by benhaynes** [comment]
Also, I know it won't work between versions and database vendors, but I think having a pure sequel export is important.

**Comment by WoLfulus** [comment]
Given that YAML has full compatibility with JSON, JSON works too. It's more about the structure than the format itself. I'm not sure about CSV in that case though.

As for SQL dumps, I think it's more a backup/restore than an export/import 🤔

**Comment by rijkvanzanten** [comment]
CSV if often used in export / import of relational tabular data in other tools like Tableplus etc. It's basically offering a way to export your database data to Excel, edit it in there, and re-import it into your database

**Comment by WoLfulus** [comment]
but that would be multiple csv files right? for different collections
