### ISSUE TITLE
Let users format date/ datetime string

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#211]
Hi, currently date/ DateTime fields rely on user locale when rendering values.

Depending on a locale, this can take too much space in the table. It would be great to allow users to choose if they need long string or short string, or even let to define the format manually, such as yyyy-mm-dd HH:MM:ss as in https://momentjs.com/docs/#/displaying/

![image](https://user-images.githubusercontent.com/11473040/92330012-72bbbc00-f074-11ea-8193-0273da90f4bd.png)

**Comment by benhaynes** [comment]
CC'ing @Nitwel ... our Interface and Display Lead

**Comment by Nitwel** [comment]
Sounds good. 👍 
I'm not sure when I'll implement this but this is definitely a nice feature.

**Comment by rijkvanzanten** [comment]
This should be an option on the display:

(Dropdown)

Format

- Long
- Short
- Custom...

Where custom allows a date-fns string
