### ISSUE TITLE
Modal windows never load for M2O

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#214]
Hello

Modal should be shown instead of a dropdown if there is over 100 records in related M2O field. Unfortunately the code fails and dropdown is shown instead.

![image](https://user-images.githubusercontent.com/11473040/92407102-5dad5e80-f142-11ea-9e8f-2c2c436accd6.png)

**Comment by rijkvanzanten** [comment]
@Nitwel Lets make this a "show inline" boolean option instead of relying on a threshold number

**Comment by Nitwel** [comment]
This treshold is already used for the `auto` option inside the `selectMode` prop. 😉 
All options are `modal, dropdown, auto`.
