### ISSUE TITLE
Repeater value not displayed correctly 

### ISSUE THREAD

**Issue by goggi** [directus/next#216]
Hi!
It works fine to create a item with a repeater. And the values saved in the database look good. But when I try to open the item the repeater value looks strange. 

Alpha 9.0.0-alpha.33
Mysql

Creation: 
![image](https://user-images.githubusercontent.com/1946339/92410918-12954a80-f146-11ea-9b6a-57946443caf2.png)

DB:
![image](https://user-images.githubusercontent.com/1946339/92410977-50926e80-f146-11ea-89a6-44dbf1ec5d97.png)

Edit:
![image](https://user-images.githubusercontent.com/1946339/92410966-44a6ac80-f146-11ea-8bba-78dec56a5631.png)

**Comment by benhaynes** [comment]
Weird — and this is using the JSON datatype?

**Comment by goggi** [comment]
yes, 
![image](https://user-images.githubusercontent.com/1946339/92415536-a9b7cd80-f159-11ea-86eb-c4f9b4d7f619.png)

**Comment by Kematia** [comment]
I'm having this error too! 

It seems like it gets stringified in the App? 
![image](https://user-images.githubusercontent.com/17851386/92480780-a8cc7d80-f1e5-11ea-8e8e-bd19905ef2c3.png)

![image](https://user-images.githubusercontent.com/17851386/92480836-bda91100-f1e5-11ea-8a65-68b0fdb347b2.png)

![image](https://user-images.githubusercontent.com/17851386/92480910-d7e2ef00-f1e5-11ea-89fd-776d598b5ac8.png)

![image](https://user-images.githubusercontent.com/17851386/92481023-01037f80-f1e6-11ea-887b-c2306b520525.png)

**Comment by rijkvanzanten** [comment]
Ah I think I know what's causing this. Could you confirm that the `special` column in `directus_fields` holds `json` for this field @goggi / @Kematia? I think it might be the fact that the app doesn't set this JSON flag correctly during field creation, which in turn means that the API returns the value as a string for MySQL

**Comment by Kematia** [comment]
`special` is `NULL` for me

![image](https://user-images.githubusercontent.com/17851386/92486486-75d9b800-f1ec-11ea-843b-37ee5fcc34cf.png)

setting it to `json` manually seems to fix it

![image](https://user-images.githubusercontent.com/17851386/92486596-93a71d00-f1ec-11ea-82a7-ce9fbfcc1907.png)

![image](https://user-images.githubusercontent.com/17851386/92486621-9a359480-f1ec-11ea-91bf-d8b18ba9106e.png)

![image](https://user-images.githubusercontent.com/17851386/92486678-a883b080-f1ec-11ea-9c0c-9d063eb6d910.png)

**Comment by goggi** [comment]
Same for me:

![image](https://user-images.githubusercontent.com/1946339/92494534-1ed8e080-f1f6-11ea-983e-ed890f38069d.png)

When I changed it from NULL to json it looked alot better!!! I will test it a bit more tonight!

**Comment by rijkvanzanten** [comment]
I'll push a fix later today/tomorrow to make sure it sets that flag correctly on field create. I won't add any auto-migrations for it though, as this is still an alpha and otherwise we'd end up with a million migrations before the real release ^^

For now, please make sure that all json fields have `special` set to `json`, and that all `boolean` fields have the special set to `boolean` 🙂

**Comment by rijkvanzanten** [comment]
We've updated the field setup flow to always set the correct special flag 🙂
