### ISSUE TITLE
Can't delete O2M relation.

### ISSUE THREAD

**Issue by Nitwel** [directus/next#222]
Clicking delete just does nothing. I assume this is because we have to delete a M2O but reversed so the field is in the other collection.

**Comment by rijkvanzanten** [comment]
@Nitwel Could you clarify what you mean by 

> Can't delete O2M relation.

Do you mean you can't delete the o2m field in settings, or that you can't de-select a row in the o2m interface in use

**Comment by Nitwel** [comment]
That I cant delete the field in the settings
