### ISSUE TITLE
Recommend fields on all relational interfaces/displays.

### ISSUE THREAD

**Issue by Nitwel** [directus/next#225]
Having predefined fields to select would be super helpful when setting up the interfaces / displays.
At the moment you don't really always know what fields there exist in a collection.
![grafik](https://user-images.githubusercontent.com/22577866/92616544-a722b880-f2be-11ea-8cf7-d885e7fbbe39.png)

**Comment by benhaynes** [comment]
I imagine finding an ideal "enable these fields" interface for these... this is just a CSV, not a "template", right @rijkvanzanten ?

Perhaps a grid of checkboxes or multiselect dropdown... anything that avoids uses TYPING these in.

**Comment by rijkvanzanten** [comment]
I think the regular checkboxes interface will work just fine. We do have to make this a "dedicated" options Vue component though, so we can dynamically pull the fields from the related o2m collection (that has to be dynamic)

**Comment by Nitwel** [comment]
I would love to implement this I just don't know how to implement access to the current collection for the interface / how to pass the current field down to the interface.

**Comment by rijkvanzanten** [comment]
@Nitwel Interfaces accept a Vue component for `options` in index.ts. See the repeater for an example. That way, we can create a custom "mini form" that has full access to the current field, including the relations info. That way, we can extract what the related collection is and pass it to a field-setup component 🙂
