### ISSUE TITLE
Support caching_sha2_password

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#23]
MySQL 8 changed to `caching_sha2_password` as it's default auth plugin, which is a breaking change compared to the previous version (5).

Directus relies on [`knex`](https://www.npmjs.com/package/knex) and [`mysql`](https://www.npmjs.com/package/mysql). 

`mysql` doesn't seem to support `caching_sha2_password` yet: https://github.com/mysqljs/mysql/issues/1959

`knex` also supports `mysql2` (https://github.com/knex/knex/tree/master/lib/dialects), but I'm not sure if that supports `caching_sha2_password` yet.

Oracle made a new MySQL connector package that definitely supports it: https://github.com/mysql/mysql-connector-nodejs, but that isn't supported in Knex (yet?): https://github.com/knex/knex/issues/3963

**Comment by rijkvanzanten** [comment]
@WoLfulus Didn't you confirm the other day that using `mysql2` as the driver package resolves this?

**Comment by WoLfulus** [comment]
It doesnt add support afaik. Install mysql2 and set the env variable in mysql startup to default the auth method allows it to work.

Just one or the other fails.

**Comment by rijkvanzanten** [comment]
This is out of our hands. This needs to be supported in Knex directly for us to be able to use it
