### ISSUE TITLE
Fields filter not working

### ISSUE THREAD

**Issue by Nitwel** [directus/next#243]
No fields setup:
```
{
   "id": 1,
   "name": "Moon",
   "orbiting_planet": 1,
   "datetime": "2020-09-09T06:56:19.000Z"
},
```

**Request**: `http://localhost:8080/items/moons?access_token=admin&fields=[id,name]`
```
{
   {},
   {}
}
```

**Request**: http://localhost:8080/items/moons?access_token=admin&fields=[w,id,name,w]
```
{
   "id": 1,
   "name": "Moon"
},
```

I'm not really sure what is happening here some something isn't quite right.

**Comment by rijkvanzanten** [comment]
The syntax is either `&fields=id,name` or `&fields[]=id&fields[]=name`. Where did you find `fields=[a, b, c]` ?

**Comment by Nitwel** [comment]
> Where did you find fields=[a, b, c] ?

I guess I mixed things up a bit.
