### ISSUE TITLE
M2M user-preview not working.

### ISSUE THREAD

**Issue by Nitwel** [directus/next#246]
This is the request directus does to preview a m2m relation. (m2m interface)
`http://localhost:8080/items/students_subjects?access_token=admin&fields[]=name,id,subject.id&filter[user][_eq]=1`

This is a request that currently works.
`http://localhost:8080/items/students_subjects?access_token=admin&fields=name,id,subject.id&filter[user][_eq]=1`

I'm not sure if this is an issue in the api not understanding the request or the app making a wrong one.

**Comment by rijkvanzanten** [comment]
this has been resolved since
