### ISSUE TITLE
Cleanup settings presets detail

### ISSUE THREAD

**Issue by benhaynes** [directus/next#258]
Convert "Name" field to be the "Toggle/Input" type (or something) so you can easily see when it's a "default". Alternatively, we could have the placeholder say "Serves as default when empty..."

Add Categories in sidebar, or to top of the layout (more accessible filter):
```
Collection Defaults
Global Bookmarks
Role Bookmarks
Personal Bookmarks
ーDIVIDERー
Dropdown for “All Collections” or one specific Collection
```

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/next/issues/258
