### ISSUE TITLE
Dropdown cannot be scrolled

### ISSUE THREAD

**Issue by shealavington** [directus/next#306]
When adding a WYSIWYG, the user cannot select items at the bottom of the list as it can't be scrolled.

![image](https://user-images.githubusercontent.com/16869302/93226686-826d8b80-f76b-11ea-9e39-01941fd39014.png)

**Comment by rijkvanzanten** [comment]
From my personal list:

![CleanShot 2020-09-15 at 12 23 29](https://user-images.githubusercontent.com/9141017/93237557-4972ee00-f74e-11ea-87a8-ac78e228b863.png)
