### ISSUE TITLE
Checkbox content is editable where it shouldn't be

### ISSUE THREAD

**Issue by shealavington** [directus/next#307]
You can edit the content in the checkboxes when trying to add a new field

![image](https://user-images.githubusercontent.com/16869302/93227295-1f302900-f76c-11ea-8cef-d250eca8fc0a.png)

**Comment by benhaynes** [comment]
Haha, this is intentional (so you can change the field name you're saving), but maybe the UX is not clear enough?

Perhaps we can disable the input/field when the checkbox is not enabled? Would that make this more obvious?

**Comment by shealavington** [comment]
Hmm yeah haha I guess it does make sense to be intentional, but yeah, I didn't understand that UX hahaha

**Comment by Nitwel** [comment]
Oh, I never noticed that!
What about putting an underline or something like this to it?

**Comment by rijkvanzanten** [comment]
_it's not a bug, it's a feature_

**Comment by benhaynes** [comment]
Haha, let's start with disabling the field when it's not checked. I think that will be enough, but we can test.

**Comment by Nitwel** [comment]
Disabling really helps!
![grafik](https://user-images.githubusercontent.com/22577866/95322776-52fafc00-089d-11eb-971f-7bb736d9572f.png)

**Comment by rijkvanzanten** [comment]
I don't know if I agree with that @Nitwel. To me, it looks like the checkbox itself is disable too

**Comment by Nitwel** [comment]
They are white inside which you don't see that good in the image. Any idea how to highlight that the checkboxes are clickable?

**Comment by benhaynes** [comment]
Hmm, I know it breaks from our normal styling, but we could make the unchecked box icon darker (foreground). That, along with the white BG will make it looked enabled.

**Comment by benhaynes** [comment]
Also, you sure that's white in there?

![Screen Shot 2020-10-07 at 9 40 44 AM](https://user-images.githubusercontent.com/522079/95338723-38b32500-0881-11eb-9f5a-6cf7c05bea4b.png)

**Comment by Nitwel** [comment]
Nope, that's my brain doing that Haha!

**Comment by rijkvanzanten** [comment]
@benhaynes Yeah it needs the full "active" regular check icon styling in that disabled input for it to work

**Comment by Nitwel** [comment]
This isn't looking that great 🤷 
![grafik](https://user-images.githubusercontent.com/22577866/95340262-3a96db80-08b5-11eb-8f14-a849da9cc552.png)

**Comment by rijkvanzanten** [comment]
Lets try just making the input value subdued when not activated yet

**Comment by benhaynes** [comment]
I agree, Nils, I think the subdued checkbox is better... but we need to get the white behind the icon. I think that will have to work, and users can learn how to use it. We could always add a note for each field that says "Click to enable".

**Comment by Nitwel** [comment]
Making the text subdued looks like this:
![grafik](https://user-images.githubusercontent.com/22577866/95341048-27384000-08b6-11eb-881a-00f6232770aa.png)

**Comment by benhaynes** [comment]
That works, but can the input be disabled until the field is enabled?

Also, let's change the header title to:

```
Enable and rename any of these optional fields.
```

**Comment by rijkvanzanten** [comment]
The above screenshot with the "enabled" darker checkbox, and I think it'll work

>  but can the input be disabled until the field is enabled?

@benhaynes I don't think this https://github.com/directus/next/issues/307#issuecomment-704951923 works that well

**Comment by benhaynes** [comment]
I agree, I'm saying **actually** disabled (can't be edited)... but with the same styling as the last screenshot.

**Comment by Nitwel** [comment]
So back to https://github.com/directus/next/issues/307#issuecomment-704860781?
With that new title?

**Comment by benhaynes** [comment]
No, this one: https://github.com/directus/next/issues/307#issuecomment-704956705

But with the new title and ideally without the text being editable until it's enabled.
