### ISSUE TITLE
MySQL datetime is being passed wrong value

### ISSUE THREAD

**Issue by shealavington** [directus/next#309]
I can't save any new items to my collection because of the following error, could be related to MySQL 5.7 only.

MySQL Ver 14.14 Distrib **5.7.31**, for Linux (x86_64) using  EditLine wrapper

```
{
  "errors": [
    {
      "message": "insert into `articles` (`content`, `date_created`, `slug`, `title`, `user_created`) values ('<p>z</p>', '\\\"2020-09-15T17:19:40.420Z\\\"', 'x', 'y', '6ef9c168-228b-4224-a1a5-fa4038dbcab0') 
      - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '\"2020-09-15T17:19:40.420Z\"' for column 'date_created' at row 1",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by shealavington** [comment]
That datetime issue I'm having, looks like it's attempting to save `'\\\"2020-09-15T17:19:40.420Z\\\"'` as the value, I would imagine it should be `'2020-09-15T17:19:40.420Z'`, no? :see_no_evil:

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/next/commit/d87fc912f4fd095d9dfe2c33bee678578db2b919
