### ISSUE TITLE
Auth Idle Timeout UX

### ISSUE THREAD

**Issue by shealavington** [directus/next#313]
Is there a way we can specify this is seconds, it's minor change, but all UX that can help is worth it :)

Also, any reason for this odd value that's equal to 3.8 hours if it is seconds aha?

![image](https://user-images.githubusercontent.com/16869302/93303150-f7d06f00-f7f2-11ea-9ebb-c21285b907ce.png)

**Comment by rijkvanzanten** [comment]
It's in minutes 😉 10080 minutes == 7 days

**Comment by benhaynes** [comment]
All the more reason to clarify the units! 😉

**Comment by rijkvanzanten** [comment]
What if we update the setting to be a text-input that takes a human readable time value like `5m` / `7 days` / `20s` ?

**Comment by benhaynes** [comment]
Is it `7 days` and not `7d`? Weird. 

This is nice, but is harder to validate (string instead of just an int). 

I wonder about adding a "units" field to text input and textarea... could show a subdued text to the right of the value. @Nitwel ?

**Comment by Nitwel** [comment]
That would be nice but I'm thinking more of a pre and suffix here because you might want to have £100.

**Comment by rijkvanzanten** [comment]
> Is it 7 days and not 7d? Weird.

Both are valid, we're using `ms` to parse this: https://www.npmjs.com/package/ms#examples

**Comment by benhaynes** [comment]
True! Would there be issues positioning these prefixes/suffixes when not using a monospace font?

**Comment by Nitwel** [comment]
I guess not. We'll see.

**Comment by benhaynes** [comment]
DO we have another ticket tracking  this change? Any reason to close this now @shealavington ?

**Comment by shealavington** [comment]
I have no idea why I closed this aha... 😶 Think I accidentally did it on mobile, just trying out the new GH mobile app haha
