### ISSUE TITLE
Collection columns: Drag handles not working

### ISSUE THREAD

**Issue by shealavington** [directus/next#314]
Handles don't work for dragging and re-ordering

![image](https://user-images.githubusercontent.com/16869302/93332373-aa1b2d00-f819-11ea-91f1-2223180af55a.png)

**Comment by rijkvanzanten** [comment]
This might be the same as 

> When editing a data model, if I try to drag and drop fields to reorganize them, it does not work and the mouse becomes unresponsive in the UI until I refresh the page or change page by going back in the browser etc.

in https://github.com/directus/next/issues/283#issue-699296928.

@shealavington What browser/os is this on? I can't reproduce it..

**Comment by shealavington** [comment]
Windows, Chrome 🤔 and yeah could be the same

**Comment by rijkvanzanten** [comment]
This is a very strange one, I've tried every browser I have (Chrome / Edge / Safari / Firefox), but can't reproduce this :|.. It must be something that only happens on Windows/Linux, but no macOS?

**Comment by shealavington** [comment]
I've noticed mine is intermittent, sometimes it does work but a lot of the time it packs up and basically freezes the browser

**Comment by rijkvanzanten** [comment]
@shealavington Anything interesting in Console / Network in the devtools when that happens? There must be some sort of infinite loop kicking in somewhere from the sounds of it, but I can't think of what (and can't reproduce it :| )

**Comment by shealavington** [comment]
Nothing in console, didn't check network, I can try dig next time I'm on my pc

**Comment by goggi** [comment]
I have the same issue. Running Windows 10.
It works on Firefox, but has the same issue as described on Chrome & New Edge

**Comment by benhaynes** [comment]
I know no one wants to share all their browser extensions (to see if there's an overlapping culprit)... but maybe those who are experiencing the issue can try reproducing in "incognito" (or your browser equivalent) to test in a vanilla state?

**Comment by shealavington** [comment]
Yeah, I've tested in incognito, same thing 😔

**Comment by Nitwel** [comment]
I will try to recreate that tomorrow and when I get it to *not* work I can look into either fixing it myself or posting more information here to find the root of this.

**Comment by Nitwel** [comment]
Just tested this now and for me, it works fine. I've also looked a bit into the setup and that all seems configured correctly.
Any special fields in that collection?

**Comment by rijkvanzanten** [comment]
@Nitwel You are on windows too right...... ? That rules out it being a windows v mac thing.. Wondering if there's a combination of fields / field data that makes it crash. @shealavington Care to send over a DB dump?

**Comment by Nitwel** [comment]
Yes, I'm using windows.

**Comment by nickrum** [comment]
I can reproduce this on Windows 10 with Chrome and Chromium Edge as well.
It affects any draggable UI and seems to be caused by the dropzone for file uploads that spans the whole window.
More specifically `onDragEnter()` in the _private_view_ component disables all pointer events inside the component by toggling the `.dragging` css class, which seems to prevent further drag events and any other interaction with the window.

Maybe the event listeners for the dropzone should only be called if a file is dragged. I could create a PR if you don't mind.

**Comment by rijkvanzanten** [comment]
ahhhhhhhhhhhhhhh good catch @nickrum! Yes please, a PR would be wonderful 👍

**Comment by rijkvanzanten** [comment]
I'm kinda confused it only seems to happen under Windows, but your explanation makes total sense to me

**Comment by nickrum** [comment]
I'm confused because of that as well. Especially since @Nitwel couldn't reproduce this on Windows. Otherwise my guess would be that the drag mechanism is somehow implemented natively on each platform.
