### ISSUE TITLE
Notice presentation field not working

### ISSUE THREAD

**Issue by shealavington** [directus/next#315]
Color preset seems broken when adding a notice presentation field

![image](https://user-images.githubusercontent.com/16869302/93332752-3a597200-f81a-11ea-8eb6-685ba2064fcf.png)

**Comment by Nitwel** [comment]
Wait a moment. Are you using the latest version of /next cause I don't think so.
The notice has a description in the latest version.

**Comment by shealavington** [comment]
Good spot Nitwel, I hadn't updated in two days I don't think, must've snuck past me! 

![image](https://user-images.githubusercontent.com/16869302/93348375-07b97480-f82e-11ea-9aac-41c41825d3f3.png)
