### ISSUE TITLE
Infinite refresh request after reloading the page.

### ISSUE THREAD

**Issue by thulioprado** [directus/next#316]
After creating the project using the command **npx create-directus-project my-project**, I logged in to the panel and updated the page using the F5 button (or the update button on the browser), and the app started making infinite refresh requests.
In a few seconds, I already had more than 5000 requests and continued to increase.

**App Version:** 9.0.0-alpha.37
**Db Version:** PostgreSQL 12.4
**Node Version:** 14.2.0

**Comment by benhaynes** [comment]
@rijkvanzanten ... Followed these steps and I am **not** getting any infinite requests — seems to work as expected.

However, on the login page I do get `503` errors for `interfaces`, `displays`, etc... and a `401` on `refresh`... not sure if we can resolve those. I get that random errors are maybe expected, but they make Directus "look" broken.

**Comment by rijkvanzanten** [comment]
> on the login page I do get 503 errors for interfaces, displays, etc...

This means your extensions folder is missing (and or the folders for the individual ones are missing)

> and a 401 on refresh

The app doesn't know if you have a valid refresh token (for security reasons), so it tries refreshing every time. 

> I get that random errors are maybe expected, but they make Directus "look" broken.

You can't suppress any `4xx` or `5xx` errors from the Chromium devtools (yet), even though they are perfectly fine and expected.

**Comment by rijkvanzanten** [comment]
Can't seem to reproduce this. Let me know if there's anything in your environment that could cause troubles @thulioprado
