### ISSUE TITLE
CLI setup failed - insert into directus_fields failed due to constraint 

### ISSUE THREAD

**Issue by kukulaka** [directus/next#321]
insert on directus_field table failed due to constraint issue  when running CLI 

**App Version**: 9.0.0-alpha.37
**Db Version**:  SQLite version 3.33.0
**Node Version**: v12.18.3

``` insert into `directus_fields` (`collection`, `field`, `interface`, `locked`, `options`, `readonly`, `sort`, `special`, `width`) select 'directus_collections' as `collection`, 'collection_divider' as `field`, 'divider' as `interface`, true as `locked`, '{"icon":"box","title":"Collection Setup","color":"#2F80ED"}' as `options`, NULL as `readonly`, 1 as `sort`, 'alias' as `special`, 'full' as `width` union all select 'directus_collections' as `collection`, 'collection' as `field`, 'text-input' as `interface`, true as `locked`, '{"font":"monospace"}' as `options`, true as `readonly`, 2 as `sort`, NULL as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'icon' as `field`, 'icon' as `interface`, true as `locked`, NULL as `options`, NULL as `readonly`, 3 as `sort`, NULL as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'note' as `field`, 'text-input' as `interface`, true as `locked`, '{"placeholder":"A description of this collection..."}' as `options`, NULL as `readonly`, 4 as `sort`, NULL as `special`, 'full' as `width` union all select 'directus_collections' as `collection`, 'display_template' as `field`, 'display-template' as `interface`, true as `locked`, '{"collectionField":"collection"}' as `options`, NULL as `readonly`, 5 as `sort`, NULL as `special`, 'full' as `width` union all select 'directus_collections' as `collection`, 'hidden' as `field`, 'toggle' as `interface`, true as `locked`, '{"label":"Hide within the App"}' as `options`, NULL as `readonly`, 6 as `sort`, 'boolean' as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'singleton' as `field`, 'toggle' as `interface`, true as `locked`, '{"label":"Treat as single object"}' as `options`, NULL as `readonly`, 7 as `sort`, 'boolean' as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'translation' as `field`, 'repeater' as `interface`, true as `locked`, '{"template":"{{ translation }} ({{ locale }})","fields":[{"field":"locale","name":"Language","type":"string","schema":{"default_value":"en-US"},"meta":{"interface":"system-language","width":"half"}},{"field":"translation","name":"Translation","type":"string","meta":{"interface":"text-input","width":"half","options":{"placeholder":"Enter a translation..."}}}]}' as `options`, NULL as `readonly`, 8 as `sort`, 'json' as `special`, 'full' as `width` union all select 'directus_collections' as `collection`, 'archive_divider' as `field`, 'divider' as `interface`, true as `locked`, '{"icon":"archive","title":"Archive","color":"#2F80ED"}' as `options`, NULL as `readonly`, 9 as `sort`, 'alias' as `special`, 'full' as `width` union all select 'directus_collections' as `collection`, 'archive_field' as `field`, 'field' as `interface`, true as `locked`, '{"collectionField":"collection","allowNone":true,"placeholder":"Choose a field..."}' as `options`, NULL as `readonly`, 10 as `sort`, NULL as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'archive_app_filter' as `field`, 'toggle' as `interface`, true as `locked`, '{"label":"Enable App Archive Filter"}' as `options`, NULL as `readonly`, 11 as `sort`, 'boolean' as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'archive_value' as `field`, 'text-input' as `interface`, true as `locked`, '{"font":"monospace","iconRight":"archive","placeholder":"Value set when archiving..."}' as `options`, NULL as `readonly`, 12 as `sort`, NULL as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'unarchive_value' as `field`, 'text-input' as `interface`, true as `locked`, '{"font":"monospace","iconRight":"unarchive","placeholder":"Value set when unarchiving..."}' as `options`, NULL as `readonly`, 13 as `sort`, NULL as `special`, 'half' as `width` union all select 'directus_collections' as `collection`, 'sort_divider' as `field`, 'divider' as `interface`, true as `locked`, '{"icon":"sort","title":"Sort","color":"#2F80ED"}' as `options`, NULL as `readonly`, 14 as `sort`, 'alias' as `special`, 'full' as `width` union all select 'directus_collections' as `collection`, 'sort_field' as `field`, 'field' as `interface`, true as `locked`, '{"collectionField":"collection","placeholder":"Choose a field...","typeAllowList":["float","decimal","integer"],"allowNone":true}' as `options`, NULL as `readonly`, 15 as `sort`, NULL as `special`, 'half' as `width` - SQLITE_CONSTRAINT: NOT NULL constraint failed: directus_fields.readonly```

**Comment by rijkvanzanten** [comment]
Fixed in 075d6251
