### ISSUE TITLE
Repeater options are a little funny

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#329]
![CleanShot 2020-09-18 at 15 47 04](https://user-images.githubusercontent.com/9141017/93639029-5bf75c80-f9c6-11ea-9b80-54ecd90161a8.png)

**Comment by benhaynes** [comment]
Repeaters (and several other interfaces) should never really be used in `half` width mode. Not sure if we want to enforce that, but we certainly need to avoid it in all system settings.
