### ISSUE TITLE
Add "first login" welcome / onboarding flow

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#344]
- [ ] First Admin:
  - [ ] Project Setup (just first 4 fields)
  - [ ] User Profile Setup
  - [ ] Data Model: Explains process, button takes you to this page
- [ ] User: 
 -  [ ] User Profile Setup
  - [ ] “Project Onboarding Text”  (New Field in Settings)

**Comment by Nitwel** [comment]
Oh, thats an awesome Idea, love it. ❤️
