### ISSUE TITLE
M2Os in O2M dont work. API does not return nested data

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#350]
Hi! O2Ms do not not render M2Os in tables and look as follows

`options` = `{"fields":["code","testid", "datetest", "testdropdown"]}`
URL: http://localhost:41201/items/test/1?fields[]=tests.code&fields[]=tests.testid&fields[]=tests.datetest&fields[]=tests.testdropdown&fields[]=tests.id
![image](https://user-images.githubusercontent.com/11473040/93667063-a68edc80-fa8b-11ea-8df9-568208fa0efe.png)

if I change the `options` to `{"fields":["code","testid.name", "datetest", "testdropdown"]}` it does not render the list at all and no results are returned by the API
URL: http://localhost:41201/items/test/1?fields[]=tests.code&fields[]=tests.testid.name&fields[]=tests.datetest&fields[]=tests.testdropdown&fields[]=tests.id
![image](https://user-images.githubusercontent.com/11473040/93667144-392f7b80-fa8c-11ea-94a5-c61042d7f575.png)
![image](https://user-images.githubusercontent.com/11473040/93667160-55331d00-fa8c-11ea-92ef-cdd77e3859f0.png)

I played a bit more the API request and realized the following:

1. `tests.testid` returns the ID of the records
2. `tests.testid.name` does not return any data
3. `tests.*.*` returns all necessary fields

![image](https://user-images.githubusercontent.com/11473040/93667252-0cc82f00-fa8d-11ea-9df0-a7c4f3244631.png)

I believe there is a bug in the API.

P.S. You cannot configure M2O from the admin panel. The field picker is missing from the interface.

**Comment by Nitwel** [comment]
This seems to be the same issue as in #376

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/next/commit/a5be4e3e480c13ade8cdc3b24ff485b0b9835208
