### ISSUE TITLE
Add a "Enable Sorting" option to M2M/O2M Setup

### ISSUE THREAD

**Issue by benhaynes** [directus/next#360]
It is a common use-case to have sorting on O2M and M2M relationships. Adding this to the setup flow will reduce confusion on how to accomplish this.

We'll use the "toggle/value" component for this... the only bummer is that it will increase the height of the relational setup and make it seem more confusing.

**Comment by Nitwel** [comment]
@rijkvanzanten How would this work. We can't just set the sort id's to whatever we want because not alll items are exposed so we could create duplicate id's by mistake?

**Comment by benhaynes** [comment]
When you are in the relational setup pane, it would have one of those toggle/inputs (with `sort` field name as default). When turned on, it would create the additional `sort` INT field, and automatically set the junction collection's sort option to the field name.

**Comment by Nitwel** [comment]
Yep, that is clear to me it's just that we don't know to what numbers.

**Comment by benhaynes** [comment]
> we don't know to what numbers

What do you mean by this?

**Comment by rijkvanzanten** [comment]
@benhaynes @Nitwel The sort setup is an interface option, not a relationship option. Not every o2m relational interface will support manual drag and drop.

> We can't just set the sort id's to whatever we want because not alll items are exposed so we could create duplicate id's by mistake?

I believe we can? "not alll items are exposed" All related o2m items are in fact exposed in the interface, so you should be able to set the `{ [sort-field]: index }` on manual drag and drop

> we don't know to what numbers.

This would be the index in the table of the o2m/m2m interfaces
