### ISSUE TITLE
CLI Init fails on SQL server due to port number / string issue

### ISSUE THREAD

**Issue by kukulaka** [directus/next#363]
**Directus**: 9.0.0-beta.1
**Node**:  v12.18.3
**SQL Server**: 15.0.2000.5

Initialising CLI

knex / tedious error 

```
(node:21392) UnhandledPromiseRejectionWarning: TypeError: The "config.options.port" property must be of type number.
    at new Connection (C:\Users\kukul\Documents\next\api\node_modules\tedious\lib\connection.js:620:17)
    at C:\Users\kukul\Documents\next\api\node_modules\mssql\lib\tedious\connection-pool.js:61:23

"config.options.port" property must be of type number.


at Client_MSSQL.acquireRawConnection (C:\Users\kukul\Documents\next\api\node_modules\knex\lib\dialects\mssql\index.js:221:12)
```

This is specific to MSSQL driver. 1433 was entered as port. If port is not entered this error is not thrown. 
``

**Comment by rijkvanzanten** [comment]
What did you use for the env var @kukulaka ? `DB_PORT="1433"` or `DB_PORT=1433` ?

**Comment by kukulaka** [comment]
@rijkvanzanten DB_PORT=1433

**Comment by mscbpi** [comment]
@rijkvanzanten the same issue stills appear if you enter a port from default when installing with `npx` (CLI wizard). 

Works when let empty (default). Would that mean that if `DB_PORT` is not set as env with `DB_CLIENT` mssql, it would default to 1433 ?
