### ISSUE TITLE
Depreciation warning  tedious/ mssql driver - will need to keep in mind for future 

### ISSUE THREAD

**Issue by kukulaka** [directus/next#365]
**Directus**: 9.0.0-beta.1
**Node**: v12.18.3
**SQL Server**: 15.0.2000.5

`[DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.`

This is specific to the tedious / mssql driver that is used by knex.

**Comment by rijkvanzanten** [comment]
Seeing we rely on external libraries, this is not something that we ourselves can fix in Directus. We can open a ticket over on the Knex repo
