### ISSUE TITLE
M2M Default Interface/Display

### ISSUE THREAD

**Issue by benhaynes** [directus/next#366]
If you use the default interface/display for a M2M field, you get a text input... and no way to change the interface afterwards.

![Screen Shot 2020-09-21 at 10 57 47 AM](https://user-images.githubusercontent.com/522079/93783356-97c63800-fbf9-11ea-95d0-2976ca7dcd8b.png)

**Comment by rijkvanzanten** [comment]
I think this was caused by the previous issue where you had some relational setup troubles due to multiple relationships to the same fields / duplicate fields. With that issue resolved, I think this situation can't occur anymore.
