### ISSUE TITLE
Error Deleting M2M Field

### ISSUE THREAD

**Issue by benhaynes** [directus/next#367]
![Screen Shot 2020-09-21 at 11 01 44 AM](https://user-images.githubusercontent.com/522079/93783596-df4cc400-fbf9-11ea-8692-cd5f1c729568.png)

**Comment by rijkvanzanten** [comment]
I think this was caused by the previous issue where you had some relational setup troubles due to multiple relationships to the same fields / duplicate fields. With that issue resolved, I think this situation can't occur anymore.
