### ISSUE TITLE
Field Showing as M2M, Editing As Standard

### ISSUE THREAD

**Issue by benhaynes** [directus/next#370]
After creating a M2M, the field hover shows it as a M2M, but editing in the Modal shows it as Standard and doesn't include the relational pane.

Also, this is after creating a M2M, deleting it, and adding it again. The `directus_relations` table has duplicated entries for these... which might be part of the problem.

![Screen Shot 2020-09-21 at 11 11 05 AM](https://user-images.githubusercontent.com/522079/93784699-4c148e00-fbfb-11ea-8699-f97613be5963.png)
![Screen Shot 2020-09-21 at 11 11 20 AM](https://user-images.githubusercontent.com/522079/93784712-4dde5180-fbfb-11ea-9c6f-8f0ef4af0f93.png)

![Screen Shot 2020-09-21 at 11 13 43 AM](https://user-images.githubusercontent.com/522079/93784932-8847ee80-fbfb-11ea-8ef3-3a3259ae2a9b.png)

**Comment by rijkvanzanten** [comment]
> the field hover shows it as a M2M

The field hover shows the interface that's used for the field, not the type 🙂

**Comment by benhaynes** [comment]
Ahh, right. Still, it's not showing the selected interface/display either... just the options.

![Screen Shot 2020-09-21 at 11 17 11 AM](https://user-images.githubusercontent.com/522079/93785406-0f956200-fbfc-11ea-8a3c-4860f8af49da.png)

**Comment by rijkvanzanten** [comment]
I think this is caused by 

> Also, this is after creating a M2M, deleting it, and adding it again. The directus_relations table has duplicated entries for these... which might be part of the problem.

**Comment by rijkvanzanten** [comment]
I think this was caused by the previous issue where you had some relational setup troubles due to multiple relationships to the same fields / duplicate fields. With that issue resolved, I think this situation can't occur anymore.
