### ISSUE TITLE
User Display Doesn't Seem to be Working

### ISSUE THREAD

**Issue by benhaynes** [directus/next#376]
I setup a user field, set the Display to User, and added a value... but nothing is showing up on the display.

![Screen Shot 2020-09-21 at 12 05 54 PM](https://user-images.githubusercontent.com/522079/93791976-e9bf8b80-fc02-11ea-9265-096fcebd4423.png)
![Screen Shot 2020-09-21 at 12 06 07 PM](https://user-images.githubusercontent.com/522079/93791983-eb894f00-fc02-11ea-9cd9-be3dfcaae7b2.png)
![Screen Shot 2020-09-21 at 12 06 10 PM](https://user-images.githubusercontent.com/522079/93791989-ecba7c00-fc02-11ea-9e14-088bfb241090.png)

**Comment by Nitwel** [comment]
This a bug in the api. The layout is requesting:
![grafik](https://user-images.githubusercontent.com/22577866/93860962-1a192f80-fcc0-11ea-8151-84b23af42f99.png)

And gets this as the response:
![grafik](https://user-images.githubusercontent.com/22577866/93861018-2a310f00-fcc0-11ea-8bd8-aec428358bcd.png)
