### ISSUE TITLE
Sign-out console errors

### ISSUE THREAD

**Issue by shealavington** [directus/next#38]
Upon clicking sign-out, I get redirected to the login page, but with a bunch of console errors.

![image](https://user-images.githubusercontent.com/16869302/89403519-5395db80-d710-11ea-9769-889e14f13452.png)

**Comment by rijkvanzanten** [comment]
It clears out the store before the navigation to /login occurs, which means that the elements relying on that store throw errors in the split second they try to refresh based on the now non-existing data :|
