### ISSUE TITLE
Custom Collection Without Grouping

### ISSUE THREAD

**Issue by benhaynes** [directus/next#381]
Can we find a way to allow for Custom Collections without forcing the grouping? Perhaps if the Group name is NULL it just ignores the group? And for all subsequent groups it just uses a divider (if name is null)?

![Screen Shot 2020-09-21 at 2 21 51 PM](https://user-images.githubusercontent.com/522079/93810227-53985f00-fc1c-11ea-9b88-fda8cd8c7446.png)

![Screen Shot 2020-09-21 at 3 08 59 PM](https://user-images.githubusercontent.com/522079/93810286-66ab2f00-fc1c-11ea-9c9d-a4a511dffacf.png)

**Comment by benhaynes** [comment]
Also, we should update the Repeater/Placeholder to reflect this.

**Comment by Nitwel** [comment]
When the name is undefined we now show either no title on the `v-detail` or a `v-divider` except for the first entry.
![grafik](https://user-images.githubusercontent.com/22577866/95439173-8c903d80-0957-11eb-8d1a-ab3f2286a35c.png)

**Comment by rijkvanzanten** [comment]
We shouldn't allow collapsing for unnamed groups, this works and feels pretty weird:

![CleanShot 2020-10-08 at 09 50 29](https://user-images.githubusercontent.com/9141017/95467656-b93e5800-094b-11eb-88ff-3e067d999ffe.png)

Also, I wish we had a better setup for no-group collections, with the "Empty item" placeholder and empty field this feels weird to use:

![CleanShot 2020-10-08 at 09 49 19](https://user-images.githubusercontent.com/9141017/95467753-d2470900-094b-11eb-9b30-48e4e921db6e.png)

**Comment by Nitwel** [comment]
Should this maybe a separate option in the dropdown?

**Comment by benhaynes** [comment]
1. Make Group Name Required
2. `Accordion` -> `Type`, with the options:
    * Divider: Always Open (Default)
    * Group Name: Always Open
    * Group Name: Start Open
    * Group Name: Start Collapsed

**Comment by benhaynes** [comment]
Also, let's add two options to the repeater:
* `Add Item Text`
* `Empty Item Text`

That will let us customize these use-cases a bit more.

**Comment by Nitwel** [comment]
How would `Add Item Text` and `Empty Item Text` work?
Is `Empty Item Text` a boolean?

**Comment by benhaynes** [comment]
Both are just text inputs for customizing the repeater text. They are just the text for the "add new" button and placeholder text in the header, respectively.

**Comment by Nitwel** [comment]
What should we replace the `Empty Item` with?

**Comment by benhaynes** [comment]
For the repeater in general, I think we keep it the same... for the Collections Nav, it won't matter much since we'll make "Group" required... but we can make it "New Collection Group" so that's displayed before you type the group name.
