### ISSUE TITLE
Create Corresponding Field in O2M not Working

### ISSUE THREAD

**Issue by benhaynes** [directus/next#382]
Clicking the toggle doesn't do anything, and no errors in console of API output.
![Screen Shot 2020-09-21 at 3 35 38 PM](https://user-images.githubusercontent.com/522079/93812801-1d5cde80-fc20-11ea-85d5-e59d811cee4f.png)

**Comment by rijkvanzanten** [comment]
This only happens in the combination existing collection + new field
