### ISSUE TITLE
General problems with sql syntax for MSSQL on collections endpoint

### ISSUE THREAD

**Issue by kukulaka** [directus/next#383]
Undefined column causing query to fail. This has now been resolved in knex-schema-inspector package

select top (@p0) *, [undefined] from [directus_collections] where 1 = @p1 order by [undefined] asc - Invalid column name 'undefined'.

````

**Comment by rijkvanzanten** [comment]
What do you mean by "missing single quotes"? Where are these missing?

**Comment by kukulaka** [comment]
Sorry @Rijk - This query was well-formed but MSSQL primary in knex-schema-inspector issue was returning undefined.  This has now been resolved.

**Comment by kukulaka** [comment]
Additional issues with SQL syntax. TSQL requires that column names not be ambiguous. For example, if two tables have a column called "collections" then the query must specify the table this column belongs to. 

`{"message":"select top (@p0) *, [collection] from [directus_collections] where 1 = @p1 order by [collection] asc - Ambiguous column name 'collection'`
