### ISSUE TITLE
Saving on Item Detail Spins Forever

### ISSUE THREAD

**Issue by benhaynes** [directus/next#384]
I have a simple collection with one text field. I enter a value and hit save button or the META-S keyboard shortcut, and I get an infinite spinner on the save action button:

![Screen Shot 2020-09-21 at 4 40 27 PM](https://user-images.githubusercontent.com/522079/93819035-2d2cf080-fc29-11ea-9f2f-719b45a99083.png)

It does save the item. There are no errors in the console or API output.

**Comment by rijkvanzanten** [comment]
Fixed in 15043c7a
