### ISSUE TITLE
Dynamic Export File Name

### ISSUE THREAD

**Issue by benhaynes** [directus/next#387]
@kukulaka @rijkvanzanten — I imagine users will often download several collections in a row. To avoid the `export (1).csv` annoyance (and to just add more clarity), maybe we can add the ability to pass a name to the export? Ideally this would use the Collection name... and maybe a time stamp:

`ingredients.csv`
or something like...
`ingredients_2020_09_21_05_12_30_PM.csv`

**Comment by rijkvanzanten** [comment]
`Export ingredients 2020-09-20 at 5.45.45 PM`

"macOS Screenshot Style" ?
