### ISSUE TITLE
Relational Setup Tweaks

### ISSUE THREAD

**Issue by benhaynes** [directus/next#394]
* Let's change the corresponding field section so that the Related Collection name is the field title of "Create Field"
    * eg: `Create Field` -> `Ingredients Field`
* Let's have the "blue" for matched collections and fields ALSO show when the fields are disabled (eg: Auto Fill)
- [x] No interface available for M2M
- [x] With the options in the screenshot, it does not add the new junction table FK field (`ingredient_id`)

![Screen Shot 2020-09-21 at 6 51 49 PM](https://user-images.githubusercontent.com/522079/93829535-d250c480-fc3b-11ea-9800-aa6035e9ee28.png)
![Screen Shot 2020-09-21 at 6 54 15 PM](https://user-images.githubusercontent.com/522079/93829549-dd0b5980-fc3b-11ea-9815-d4f80492ba53.png)
![Screen Shot 2020-09-21 at 6 57 18 PM](https://user-images.githubusercontent.com/522079/93829759-586d0b00-fc3c-11ea-86bb-cc6f92341bf8.png)

**Comment by benhaynes** [comment]
@rijkvanzanten — is this done?

**Comment by rijkvanzanten** [comment]
I believe it is, yes
