### ISSUE TITLE
Fast navigation causes tool-tip glitch

### ISSUE THREAD

**Issue by shealavington** [directus/next#40]
Navigating too quickly causes the item tooltip to hide in the top corner, it doesn't update x/y quick enough, after a split second it does fix though, so it's not urgent.

![image](https://user-images.githubusercontent.com/16869302/89403652-8b048800-d710-11ea-9e9a-6f0ca7a5ba4f.png)

**Comment by rijkvanzanten** [comment]
@nitwel Would you mind helping me with this? 🙂 

I think it might have something to do with the fact that the tooltip "loses" the element it was attached to because it was re-rendered or something like that, not too sure

**Comment by benhaynes** [comment]
Yes, this a very annoying issue that happens pretty consistently. Would *love* if anyone had time to troubleshoot it!! 🤞
