### ISSUE TITLE
Change user default timezone to UTC

### ISSUE THREAD

**Issue by shealavington** [directus/next#42]
Could we allow the user/developer during setup to select the default timezone/language to be used? It just creates a better experience as when you look at your user account and see it set to NYC, it's rather confusing haha!

**Comment by rijkvanzanten** [comment]
We'll have to figure out what we want to ask for, and what we can automate 🤔 

@benhaynes as of right now, that timezone flag on the user detail page isn't used for anything in the app itself. We could even consider removing it completely (or defaulting it to UTC/GMT)

**Comment by shealavington** [comment]
I would consider a UTC a good option, being Universal n'all ;)

**Comment by benhaynes** [comment]
Yeah, well need to decide what goes in the CLI installer, what goes on the env file, and what is in the database. The installer should always be fast and lightweight... but we could add ways to go through a more "verbose" installer that covers more options.

I think another good option for this is to have a one-time initial setup modal when you first open the app as an admin. Although this should only be for configuring app specific things, not for API requirements.

**Comment by benhaynes** [comment]
Also, since we're saving everything in UTC, doesn't it make sense for each user to have an option to convert that to a local time for them? Relative times work for this too, but feel less exact/professional in some cases. 

Maybe this just makes things more confusing in terms of time zones though?

**Comment by rijkvanzanten** [comment]
We should do that kind of time conversion based on the users computer time (browser relative) instead of a setting, otherwise it gets _really_ confusing if you don't explicitly set it up correctly

**Comment by benhaynes** [comment]
So are we saying we're removing this User Setting in favor of the browser timezone? When we add the User Onboarding, will we should have a field for this? I wonder if this will work as expected when a user is traveling and crosses timezones. IF it's automatic, there should still be a way to see the set timezone for each user/datetime.

**Comment by rijkvanzanten** [comment]
> So are we saying we're removing this User Setting in favor of the browser timezone? 

Yes

> When we add the User Onboarding, will we should have a field for this?

No

> I wonder if this will work as expected when a user is traveling and crosses timezones.

Yes. timestamp type fields (the only one with a timezone) save and retrieve with said timezone. We already discussed allowing you to see / set the timezone explicitly in the datetime interface.

In the current tech landscape, every device I can think of that connects to the internet will auto-change the clock when traveling internationally, and show times/dates set internationally relative to that. I don't think that's confusing at all. What would be confusing is to lock it to a certain timezone, then travel abroad, and not realize you're locked in a different timezone in just directus (even though your computer clock will say it's a different time)

**Comment by benhaynes** [comment]
All this is fine, but the interfaces/displays need to always show the presented TZ so this is clear.
