### ISSUE TITLE
Directus + LetsEncrypt/Certbot + Nginx (and proxy_pass)

### ISSUE THREAD

**Issue by ahoebeke** [directus/next#426]
Hi,
I wanted postgresql support so I chose to use directus/next.
Worked easily, with nginx using a simple `proxy_pass http://127.0.0.1:41201/` directive.

However I want HTTPS of course. To let certbot do its thing, I made the root URL path available with the default nginx config. 
I hosted my proxy_pass directive at location `https://mydomain.com/directus/` instead of `https://mydomain.com/` and that's where I'm now stuck.
It seems like `https://mydomain.com/directus/` redirects to `https://mydomain.com/admin/` instead of loading `https://mydomain.com/directus/admin/`.

Also... seeing the sample nginx config file at [https://docs.directus.io/advanced/server-setup.html#nginx](https://docs.directus.io/advanced/server-setup.html#nginx) makes me wonder what other trouble I will likely run into by doing this `proxy_pass` thing.

Anyone gone down this road and care to share ? 

--- 

**Update**
It seems you can add an Nginx location config to allow certbot to do its domain verification correctly.
Answer found here : https://serverfault.com/questions/768509/lets-encrypt-with-an-nginx-reverse-proxy

In the end, what I currently have works (for now).
1. used default nginx config (default message showing at mydomain.com) 
1. added my servername, let's say mydomain.com
1. run `certbot --nginx`
1. replace `location /` to contain `proxy_pass` directives (see my nginx.conf file below).
1. tested `certbot --dry-run renew` and that seems to indicate that this will work when the time comes to renew.

The above mentioned `location /.wellknown` solution should allow you to simply setup your `proxy_pass` up directly, before running certbot. 
Certbot will place some file or info over at `/var/www/html/.wellknown` (uses your server_root, which may be different from `/var/www/html` of course).
Place the `location /.wellknown` before the `location /` and then hope it works fine :) 

```
server {

        root /var/www/html;
        index index.html index.htm;
        server_name _ mydomain.com;

        location /.wellknown {
                alias /var/www/html/;
                # alias /var/www/html/.wellknown;  # Some say this works for them instead..
        }

        location / {
                # I run `npx directus start` which runs the app at the below location.
                # set up your firewall to block direct access to this port (ideally :)
                proxy_pass http://127.0.0.1:41201 ;
                # You might or might not need the below. 
                # During my trials it ended up like this and as it works, i left it this way.
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                #proxy_set_header Upgrade $http_upgrade;
                #proxy_set_header Connection 'upgrade';
                #proxy_cache_bypass $http_upgrade;
        }

        #       location / {
        #               try_files $uri $uri/ =404;
        #       }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
        if ($host = mydomain.com) {
                return 301 https://$host$request_uri;
        } # managed by Certbot

        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _ mydomain.com;
        return 404; # managed by Certbot
}
```

Please update or correct me if something needs to be improved. Could save the next ones a lot of time and trouble.

Regards :)

**Comment by rijkvanzanten** [comment]
Hi @ahoebeke! That second approach seems good to me 🙂 There's a ticket (#91) to allow the app to run under a subpath in the future
