### ISSUE TITLE
Auto-generated translations table gets language_code created as Numeric

### ISSUE THREAD

**Issue by lluishi93** [directus/next#441]
![image](https://user-images.githubusercontent.com/14786440/94549787-05eea880-0253-11eb-9b30-a118215ac4ce.png)

```bash
insert into `foo_translations` (`description`, `foo_id`, `languages_code`, `name`) values ('<p>La descripzione.</p>', 1, 'es-ES', 'Hotel Praga') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'es-ES' for column 'languages_code' at row 1 

```

![image](https://user-images.githubusercontent.com/14786440/94549844-1a32a580-0253-11eb-8c3c-c16fe30d6b7f.png)

The language code field should be created as a string.

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-09-29 at 18 34 34](https://user-images.githubusercontent.com/9141017/94623655-b1632180-0282-11eb-89fc-399a7bce571f.png)

When auto-generating the table using the "QuickStart" dialog, it will use `code` for a field 🤔

**Comment by rijkvanzanten** [comment]
Ohhhhhhhhhhhhhhhhhh this is the _foreign_ key 👍
