### ISSUE TITLE
Unable to select display fields when creating M2M relationship for the first time

### ISSUE THREAD

**Issue by lluishi93** [directus/next#443]
Steps:

1. Create collection A
2. Create collection B
3. Create M2M field in collection A pointing to B
4. Select corresponding field when setting up the relationship

![image](https://user-images.githubusercontent.com/14786440/94552206-caee7400-0256-11eb-9871-0071dbbae600.png)

5. Verify that display fields cannot be selected atm:

![image](https://user-images.githubusercontent.com/14786440/94552488-43553500-0257-11eb-9da7-20f8994db916.png)

6. Edit the M2M field, and verify that now display fields can be selected:

![image](https://user-images.githubusercontent.com/14786440/94552558-5c5de600-0257-11eb-9e42-8526ba2e6786.png)

Expected behaviour: display fields should be selectable when setting up the relationship for the first time.

**Comment by benhaynes** [comment]
Thanks @lluishi93 — appreciate you helping report these issues! 🙂

**Comment by rijkvanzanten** [comment]
If the auto generated `test_foo` collection doesn't exist yet, there aren't any fields yet either 🤔 

This is a bit of a weird edge case where the options of the m2m / o2m / m2o interface have to be able to use either the "real" existing collection + fields, or the "about to be created" collection/fields
