### ISSUE TITLE
Impossible to create new field

### ISSUE THREAD

**Issue by lukrate** [directus/next#444]
**Configuration**
**OS** : Linux - Ubuntu 20.04.1 LTS
**DB** : SQLITE
**Directus V 9.0.0-beta.2**

_________________

When saving the field, no matter what type (string, boolean,...) I get this error in the console :

collections : "todos"

```
Error: select 1 from pragma_table_info(`todos`) where `name` = 'validate' - SQLITE_ERROR: no such column: todos
```

**Comment by kukulaka** [comment]
PR for knex-schema-inspector will resolve this issue

https://github.com/knex/knex-schema-inspector/pull/18
