### ISSUE TITLE
BETA 4: Create new collection modal opens when going back right after creating a collection

### ISSUE THREAD

**Issue by lluishi93** [directus/next#454]
1. Create a collection
2. Click the go back orange button

![image](https://user-images.githubusercontent.com/14786440/94707835-306c5e80-0344-11eb-85fe-2cf0274cb55b.png)

3. Verify that the create collection modal gets open up

![image](https://user-images.githubusercontent.com/14786440/94707754-1b8fcb00-0344-11eb-8cdc-6fd0c55b9aea.png)

**Comment by rijkvanzanten** [comment]
Interesting, this is technically by design, but I see how it's confusing. Adding a new collection is a route `/+`, and the back button goes back 1 entry in the browsers history. 🤔

**Comment by benhaynes** [comment]
@rijkvanzanten — did we just resolve this with the recent back button logic PR?

**Comment by Nitwel** [comment]
Yes!
