### ISSUE TITLE
Creating collection Error 500 - subValidation.map(...).flat

### ISSUE THREAD

**Issue by lukrate** [directus/next#459]
OS : Linux - Ubuntu 20.04.1 LTS
DB : SQLITE
Directus V 9.0.0-beta.4

Hello, I have a 500 error when saving my collection.

![Screenshot from 2020-09-30 20:10:51](https://user-images.githubusercontent.com/6481999/94723838-a62ef500-0359-11eb-9237-69635b9ddaef.png)

**Comment by rijkvanzanten** [comment]
@lukrate What version of Node are you using?

**Comment by lukrate** [comment]
@rijkvanzanten Iam on v10.19.0
