### ISSUE TITLE
M2M are not persisting on saving when creating new item (details modal)

### ISSUE THREAD

**Issue by guilhermeaiolfi** [directus/next#479]
Hi,

I have the last commit (2a77c0c) and run npm update too, restarted the API and admin panel. The details of the collections are described in #406. 

![directus-m2m-bug](https://user-images.githubusercontent.com/254360/94823677-7f64d300-03da-11eb-9086-e16e16764776.gif)

Since the junction table has the relation, but the related item doesn't exist, that's how it shows it:

![screenshot-localhost-8080-admin-collections-news-1-1601563214941](https://user-images.githubusercontent.com/254360/94824200-1fbaf780-03db-11eb-8886-ab8ccb0d6b44.png)

**Comment by rijkvanzanten** [comment]
Are you sure that commit is the latest that you're on? This many to many situation was overhauled in https://github.com/directus/next/commit/1e5a5bce697f7763613bbaeb5bd61ddc69fdabcf, and I can't seem to reproduce your issue in any version after that commit 🤔 I'll close this for now, as I believe it was resolved in https://github.com/directus/next/commit/1e5a5bce697f7763613bbaeb5bd61ddc69fdabcf, but we can keep discussing and reopen if needed
