### ISSUE TITLE
Move image to new folder

### ISSUE THREAD

**Issue by Cruze** [directus/next#484]
If i only move an image to a new folder i can not save, until i change any other attributes.

**Comment by rijkvanzanten** [comment]
Changing the folder of a file through the action button in the header saves the new folder immediately. There's no manual save required after that.

**Comment by benhaynes** [comment]
Let's push an async notification that it was saved then... this will make it clearer. Actually, we might want to do this for many of the "Automatically saved" fields... @rijkvanzanten ?

**Comment by Cruze** [comment]
Yes that would help
