### ISSUE TITLE
Hooks don’t hook...

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#488]
Directus 9 beta 4
PG 12

Not possible to extend with a custom api hook. Followed the docs guide. The hook isn’t triggered at all. No errors. 

<img width="812" alt="983A9C1D-ED84-4B41-9281-FC95062C264B" src="https://user-images.githubusercontent.com/20950568/94861471-dd73d380-0437-11eb-89d4-3a3be041f0ed.png">

**Comment by benhaynes** [comment]
I believe you've tried this, but the screenshot you're showing uses an incorrect event syntax. It should be `items.create.*`... can you please confirm that you've tried this?

**Comment by danieljwestman** [comment]
Yes, both * and actual collection name.

**Comment by danieljwestman** [comment]
Is the folder and file structure correct. The docs aren’t consistent when browsering around different extension types...

**Comment by benhaynes** [comment]
I defer to @rijkvanzanten on that... but could you outline the inconsistencies so we can take a look?

**Comment by nickrum** [comment]
I think the folder structure should be `extensions/hooks/my-hook/index.js`, similar to how custom API endpoints work.
Have you tried that @danieljwestman?

**Comment by benhaynes** [comment]
I think that's it... the Docs are currently how we're _thinking_ of making the hooks (as simple as possible, in a single file), while in the code it's still in a directory as @nickrum mentioned. Also, we'd love feedback on which of these two is preferred.

To be clear, "bundles" (eg: things from the marketplace) will be in directories and will allow more complex structures.

**Comment by danieljwestman** [comment]
Sorry, but still no output... 😥

<img width="966" alt="Skärmavbild 2020-10-02 kl  07 53 07" src="https://user-images.githubusercontent.com/20950568/94892244-76c8d700-0484-11eb-96bf-a766025bee26.png">

**Comment by danieljwestman** [comment]
Hm, I changed to 'item.create.*' (removed the s) and now I get the log output... Don't know if it should be like that or if it's a bug... Isn't "items" a better term than "item" in this matter?

**Comment by benhaynes** [comment]
Good catch! I defer to @rijkvanzanten on this, but agree that even though the singular "reads better", plural makes more sense (since all the other hook scopes are also plural).

**Comment by rijkvanzanten** [comment]
I'm updating it now, it should be `items` (plural)
