### ISSUE TITLE
Docs: Add colored syntax for code

### ISSUE THREAD

**Issue by benhaynes** [directus/next#489]
![Screen Shot 2020-10-01 at 5 23 14 PM](https://user-images.githubusercontent.com/522079/94864971-cd91ca80-040a-11eb-89fc-b9f19774a16a.png)
![Screen Shot 2020-10-01 at 5 23 06 PM](https://user-images.githubusercontent.com/522079/94864975-cf5b8e00-040a-11eb-80e2-54a7ecb538ae.png)

**Comment by rijkvanzanten** [comment]
@Nitwel Didn't you already plugin Highlight.js?

**Comment by Nitwel** [comment]
Yes, I've added that. Maybe there is something I forgot. I'll look into that tomorrow.
