### ISSUE TITLE
Required does not work at field creation

### ISSUE THREAD

**Issue by lukrate** [directus/next#492]
**directus-beta-4**
**OS** : Windows 10
**DB** : SQlite
**Node** : v12.18.4

If i want to create a required field i have this error (tested with string and boolean field) :

```
Error: alter table `todos` add column `test` varchar(255) not null - SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
```

It works if i enter a default value

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/next/issues/447
