### ISSUE TITLE
Translation image selection is not possible

### ISSUE THREAD

**Issue by Cruze** [directus/next#502]
A translation field "image" can not select and save an image from gallery

**Comment by benhaynes** [comment]
Thanks! What DB vendor/version are you using? Version of Directus? Any other helpful details?

**Comment by Cruze** [comment]
Ubuntu 18.04
Webmin 1.955
Virtualmin 6.12
Apache 2.4.29
MySQL version 5.7.31
Directus V9 beta4

Translation Collection with an file / image in different languages.
Edit mode, choose a language, choose an image from gallery with no result

**Comment by Nitwel** [comment]
I just tried this and it seems to work. Did you still run into this issue in the latest release?

**Comment by Cruze** [comment]
The error message is gone now, but I still can't see assigned data after saving.
In the database table i can see the entries. The frontend did not show them.

**Comment by Nitwel** [comment]
Could you give information on how to recreate this?

**Comment by Cruze** [comment]
Hi, i tried it again two times and now it seems to work. Thanks!
