### ISSUE TITLE
Editing M2O column shows M2M relation

### ISSUE THREAD

**Issue by shealavington** [directus/next#51]
I am editing an M2O field however seeing the m2m relation setup

![image](https://user-images.githubusercontent.com/16869302/89415919-79c57680-d724-11ea-9704-17e968af9e77.png)
![image](https://user-images.githubusercontent.com/16869302/89415977-8a75ec80-d724-11ea-8a6e-7262dd47caa9.png)

**Comment by rijkvanzanten** [comment]
@shealavington Do you have multiple relations in `directus_relations` pointing to the same field?
