### ISSUE TITLE
Error saving Collection Navigation settings

### ISSUE THREAD

**Issue by benhaynes** [directus/next#510]
Just tried adding a "test" group and single "recipes" collection 

```directus: 18:11:09 🚨 insert into `directus_activity` (`action`, `collection`, `ip`, `item`, `user`, `user_agent`) values ('update', 'directus_roles', '127.0.0.1', 'b39531d0-cfee-42c9-a583-dd2a907b6f93', '4eededce-7a4d-493b-b4d9-484cb0c4a256', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36') - ER_BAD_FIELD_ERROR: Unknown column 'user' in 'field list' 
directus: Error: ER_BAD_FIELD_ERROR: Unknown column 'user' in 'field list'
directus:     at Query.Sequence._packetToError (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus:     at Query.ErrorPacket (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus:     at Protocol._parsePacket (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus:     at Parser._parsePacket (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus:     at Parser.write (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus:     at Protocol.write (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus:     at Socket.<anonymous> (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/Connection.js:88:28)
directus:     at Socket.<anonymous> (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/Connection.js:526:10)
directus:     at Socket.emit (events.js:314:20)
directus:     at addChunk (_stream_readable.js:303:12)
directus:     --------------------
directus:     at Protocol._enqueue (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus:     at Connection.query (/Users/Ben/Sites/directus/next/node_modules/mysql/lib/Connection.js:198:25)
directus:     at /Users/Ben/Sites/directus/next/node_modules/knex/lib/dialects/mysql/index.js:135:18
directus:     at new Promise (<anonymous>)
directus:     at Client_MySQL._query (/Users/Ben/Sites/directus/next/node_modules/knex/lib/dialects/mysql/index.js:129:12)
directus:     at Client_MySQL.query (/Users/Ben/Sites/directus/next/node_modules/knex/lib/client.js:169:17)
directus:     at /Users/Ben/Sites/directus/next/node_modules/knex/lib/transaction.js:321:24
directus:     at new Promise (<anonymous>)
directus:     at Client_MySQL.trxClient.query (/Users/Ben/Sites/directus/next/node_modules/knex/lib/transaction.js:316:12)
directus:     at Runner.query (/Users/Ben/Sites/directus/next/node_modules/knex/lib/runner.js:151:36)
directus: 18:11:09 ✨ request errored PATCH 500 /roles/b39531d0-cfee-42c9-a583-dd2a907b6f93 211ms```

**Comment by rijkvanzanten** [comment]
Sounds like you're on an older database schema

**Comment by benhaynes** [comment]
Fresh install... still getting an error...

```
directus: 18:47:04 🚨 insert into `directus_revisions` (`activity`, `collection`, `data`, `delta`, `item`) values (7, 'directus_roles', {"id":"7989ad67-5faf-46a7-aa87-2473064a8c3f","name":"Administrator","icon":"verified_user","description":"Initial administrative role with unrestricted App/API access","ip_access":null,"enforce_tfa":false,"module_list":null,"collection_list":[{"accordion":"always_open","group_name":"Test","collections":[{"collection":"recipes"}]}],"admin_access":true,"app_access":true}, '{\"collection_list\":\"[{\\\"group_name\\\":\\\"Test\\\",\\\"accordion\\\":\\\"always_open\\\",\\\"collections\\\":[{\\\"collection\\\":\\\"recipes\\\"}]}]\"}', '7989ad67-5faf-46a7-aa87-2473064a8c3f') - ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1 
directus: Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
directus:     at Query.Sequence._packetToError (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus:     at Query.ErrorPacket (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus:     at Protocol._parsePacket (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus:     at Parser._parsePacket (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus:     at Parser.write (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus:     at Protocol.write (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus:     at Socket.<anonymous> (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/Connection.js:88:28)
directus:     at Socket.<anonymous> (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/Connection.js:526:10)
directus:     at Socket.emit (events.js:314:20)
directus:     at addChunk (_stream_readable.js:303:12)
directus:     --------------------
directus:     at Protocol._enqueue (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus:     at Connection.query (/Users/Ben/Sites/directus/next/api/node_modules/mysql/lib/Connection.js:198:25)
directus:     at /Users/Ben/Sites/directus/next/api/node_modules/knex/lib/dialects/mysql/index.js:135:18
directus:     at new Promise (<anonymous>)
directus:     at Client_MySQL._query (/Users/Ben/Sites/directus/next/api/node_modules/knex/lib/dialects/mysql/index.js:129:12)
directus:     at Client_MySQL.query (/Users/Ben/Sites/directus/next/api/node_modules/knex/lib/client.js:169:17)
directus:     at /Users/Ben/Sites/directus/next/api/node_modules/knex/lib/transaction.js:321:24
directus:     at new Promise (<anonymous>)
directus:     at Client_MySQL.trxClient.query (/Users/Ben/Sites/directus/next/api/node_modules/knex/lib/transaction.js:316:12)
directus:     at Runner.query (/Users/Ben/Sites/directus/next/api/node_modules/knex/lib/runner.js:151:36)
directus: 18:47:04 ✨ request errored PATCH 500 /roles/7989ad67-5faf-46a7-aa87-2473064a8c3f 419ms
```
