### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by maartenvn** [directus/next#512]
**Directus**: 9.0.0-beta.7 (Docker image)
**MySQL**: Ver 14.14

I am unable to upload a project logo from device.

**Console output:**

```
TypeError: can't access property "id", e is undefined
```

**Comment by maartenvn** [comment]
The file viewer also appears to be broken. I am not able to view or upload images

**Comment by maartenvn** [comment]
I think this is an issue in the app, not the API. I get a status code 200 when uploading the image

```
✨ request completed POST 200 /files 195ms
```

**Comment by maartenvn** [comment]
However, the request received from the server has no response body

**Comment by maartenvn** [comment]
The files appear inside the upload directory.

![image](https://user-images.githubusercontent.com/6013068/95082316-28813580-071b-11eb-80a0-c9802070c3f1.png)
![image](https://user-images.githubusercontent.com/6013068/95082413-451d6d80-071b-11eb-8e68-ca4ae1907715.png)

**Comment by maartenvn** [comment]
This isn't linked to MySQL or Docker. I just tried it on beta.7 and SQLite and I have exactly the same issue with the same error.

**Comment by maartenvn** [comment]
I have been looking into the source code. `uploaded_on` seems to be the issue after some debugging.

```
uploaded_on:
    type: timestamp
    nullable: false
    default: '$now'
```

It seems to be configured as a `timestamp` inside the database seeds, however it is stored as a time string, instead of a timestamp number:

![image](https://user-images.githubusercontent.com/6013068/95086427-c62b3380-0720-11eb-9a7d-3577668851b0.png)

This is `last_access` which has the same database type and has the correct number format:

![image](https://user-images.githubusercontent.com/6013068/95086494-d9d69a00-0720-11eb-8c3d-1e6ab4e29eff.png)

**Comment by rijkvanzanten** [comment]
@maartenvn Is this database from an older version of the beta? We changed the datatypes of various date/time related fields in #438, and I can confirm that on my end both `last_access` and `uploaded_on` use identical types

**Comment by maartenvn** [comment]
I just tested it again, creating a project from scratchn and I still have the same issue.

### Environment
- **Node**: v14.12.0
- **Directus**: 9.0.0-beta.8
- **Yarn**: 1.22.0
- **NPM**: 6.14.7

### Steps to reproduce

1. `yarn create directus-project directus-test`
2. Select `SQLite` as DBMS
3. `npx directus start`
3. Login
4. Go to Settings -> Project Settings
5. Upload a logo

Then nothing happens and an error is printed in (browser) console.

Terminal (api):
```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule
Error
```
