### ISSUE TITLE
BETA 8 - Docker - Can't create any item, unknown column 'user'

### ISSUE THREAD

**Issue by lluishi93** [directus/next#524]
1. Update to beta 8
2. Try to create some item in previously created collections
3. Verify the following error occurs:

```
{"errors":[{"message":"insert into `directus_activity` (`action`, `collection`, `ip`, `item`, `user`, `user_agent`) values ('create', 'banners', 'XXX.XXX.XXX.XXX', 4, '4ff4f465-e48d-4ea0-ab17-ca8a696665e9', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36') - ER_BAD_FIELD_ERROR: Unknown column 'user' in 'field **list'","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}**
```

**ER_BAD_FIELD_ERROR: Unknown column 'user' in 'field **list'"**.

If rolled back to beta 7, everything works fine again.

**Comment by rijkvanzanten** [comment]
> If rolled back to beta 7, everything works fine again.

We updated a couple system keys in the schema between 7 and 8. Doing a fresh install on 8 should resolve this specific issue 👍

**Comment by mscbpi** [comment]
@rijkvanzanten  is it complicated to create the field manually in case we don't want to lose data ?
thanks

**Comment by rijkvanzanten** [comment]
@mscbpi That's totally doable! These were the biggest ones iirc: https://github.com/directus/next/issues/482
