### ISSUE TITLE
Drag&Drop a file when editing a field does not keep the file selected

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#534]
When having a file (image) field for a collection, and adding/editing an entry, dragging and dropping a file in the field does not keep the file selected.
It does upload it, but I have to select it once dragged and dropped.
![2020-10-06_09-38-10 (1)](https://user-images.githubusercontent.com/6372094/95172772-199c9080-07b8-11eb-954c-1cb88648a1de.gif)

Expected behavior : 
When I drag & drop a file, I expect the file to be uploaded and already selected as the file I want for my field.

**Comment by benhaynes** [comment]
Thanks @jojomillennium! Could you provide a bit more info on your Directus version, stack, DB, etc?

**Comment by jojomillennium** [comment]
Sure: 9.0.0beta7 docker image.
DB pointing on a mysql 5.7
Let me know if any other info is needed

**Comment by Nitwel** [comment]
I just tested this but couldn't reproduce this. Is this still not working?
What filetype are you suing?
Could you test this out in the lastest version?

**Comment by rijkvanzanten** [comment]
looks good on my end too, we'll reopen if we can reproduce

**Comment by jojomillennium** [comment]
I confirm latest version does not have this issue.
