### ISSUE TITLE
Permission issues in beta8 and beta9 

### ISSUE THREAD

**Issue by MajesteitBart** [directus/next#537]
In beta8 and 9, admin users can't update or create any record. 
![image](https://user-images.githubusercontent.com/8057288/95183888-e57c9c00-07c6-11eb-9f21-bb32c0e2303f.png)

I also have an issue which persists since beta 7: manifest.webmanifest 404 not found. I thought it was a permission setting, but I cant seem to fix it with chown.

![image](https://user-images.githubusercontent.com/8057288/95183486-54a5c080-07c6-11eb-81d2-13160d4ceeeb.png)

**Comment by benhaynes** [comment]
What stack/DB are you using?

I believe the 404 is known, and not an issue.

**Comment by MajesteitBart** [comment]
That's good to know, I'm using:
Ubuntu 18.04
NPM 6.14.8
Node 12.18.4
mysql Ver 14.14

**Comment by MajesteitBart** [comment]
I just did a clean install on a new machine and everything works fine now. Probobly a migration issue or something?
