### ISSUE TITLE
Cannot access item ID in hook

### ISSUE THREAD

**Issue by lluishi93** [directus/next#538]
Hi, I've the following hook.

![image](https://user-images.githubusercontent.com/14786440/95195850-66dc2a80-07d7-11eb-9dcf-2491ad383cc7.png)

Problem appears when I find out that both `item` (which is null) and `input` (which I assume is the payload) do not have the `id` attribute.

![image](https://user-images.githubusercontent.com/14786440/95195996-ab67c600-07d7-11eb-8258-5a954cb6d220.png)

ID should be accessible in the item param IMHO.

Edit: same happens with UUID fields.

**Comment by lluishi93** [comment]
Ok, I just found that with this syntax, id is appended to item:
![image](https://user-images.githubusercontent.com/14786440/95201927-e28ea500-07e0-11eb-8f74-c1670af4f9cb.png)

![image](https://user-images.githubusercontent.com/14786440/95201949-ecb0a380-07e0-11eb-8ba7-d284e5920f68.png)

I assume the docs are still in progress, but hope this helps someone using hooks atm.

**Comment by benhaynes** [comment]
Hey @lluishi93 — did you see these? Was this not enough?

https://github.com/directus/next/blob/main/docs/guides/extensions/api-hooks.md#event-handler-function

**Comment by rijkvanzanten** [comment]
`items.create.*` only matches with `items.create.before`, which is called blocking before the item is actually created. That also means that the primary key doesn't exist yet. The second example (`items.create`) is async after the item has been created, at which point the primary key exists as well
