### ISSUE TITLE
Feature request: trigger hooks scoped to collections

### ISSUE THREAD

**Issue by lluishi93** [directus/next#539]
Could it be possible to add the ability to trigger the hook scoped to a spefic collection, based on v8 syntax?

`items.create.banners:before`
`items.create.banners`
etc.

**Comment by benhaynes** [comment]
To simplify the code/docs, we've decided to remove the collection scope from the trigger. However it's just as easy (if not MORE powerful) to filter within the hook itself. Now you could use a regex, or more complicated ways to filter collections with code... eg: `if (collection !== 'recipes') return input;`. If you disagree with this new approach, let's open a Discussion and chat through the advantages of alternates.

https://github.com/directus/next/blob/main/docs/guides/extensions/api-hooks.md#full-example

```js
// extensions/hooks/sync-with-external/index.js

module.exports = function registerHook({ services, exceptions }) {
	const { ServiceUnavailableException, ForbiddenException } = exceptions;

	return {
		// Sync with external recipes service, cancel creation on failure
		'items.create.before': async function(input, { collection }) {
			if (collection !== 'recipes') return input;

			try {
				await axios.post('https://example.com/recipes', input);
			} catch (error) {
				throw new ServiceUnavailableException(error);
			}

			input[0].syncedWithExample = true;

			return input;
		}
	}
}
```
