### ISSUE TITLE
Missing "Time" interface field type in repeater

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#541]
9.0.0beta7 docker image with DB pointing on a mysql 5.7

V8 was providing the "time" interface as a field in repeaters. 
V9 is not.
See image below with v9 on left, and v8 on right
![image](https://user-images.githubusercontent.com/6372094/95208398-5339bf80-07e9-11eb-902c-a5e2a9c02dd5.png)

**Comment by benhaynes** [comment]
Hey @jojomillennium — to get the time interface:

1. Create a field
2. Choose the `time` type
3. Choose the `datetime` interface

That interface is dynamic and will tailor the input based on the type.

**Comment by jojomillennium** [comment]
Hi Ben, thanks.
I was referring to being able to have a "Time" field in a repeater.
So field type "JSON", interface "Repeater", and new item interface I see the "Datetime", but can set it to be a time selection.
And I get a bug (which I am about to create) where that interface in a repeater does not allow to provide a value.

**Comment by benhaynes** [comment]
Ahhh, because there is no `type` setup in a repeater's _Edit Fields_ options. I see.

@rijkvanzanten, thoughts?
