### ISSUE TITLE
Field with datetime interface in a repeater cannot be edited

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#542]
9.0.0beta7 docker image with DB pointing on a mysql 5.7

issue: When setting up a repeater interface, and putting in the repeater fields "datetime", it is not possible to provide a "datetime" value.

reproduce (see video):
- Setup a repeater field in a collection
- Setup in that repeater a field with "datetime" interface
- Try creating a new entry, the field "datetime" does not allow to select or enter a value

![2020-10-06_15-57-31 (1)](https://user-images.githubusercontent.com/6372094/95211493-f2ac8180-07ec-11eb-87ee-fad32608f4f7.gif)

**Comment by Nitwel** [comment]
@rijkvanzanten This is caused because the `type` prop of the datetime interface doesn't get set.
How should we handle this? Should we include a type dropdown for that interface in the repeater?

**Comment by benhaynes** [comment]
That's a good solution, but I wonder if we need to limit the types available here... are there any issues saving certain types within a JSON value?

**Comment by Nitwel** [comment]
We could either implement that inside the datetime interface and check if the type value is already set inside the options. I'm just not sure if that is set on setup.
Or we could implement that in a more hardcoded way inside the repeater which wouldn't scale that well but would also solve the issue.
I think Rijk has the most knowledge on how to implement this.
