### ISSUE TITLE
Repeater are not displayed through O2M

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#543]
9.0.0beta7 docker image with DB pointing on a mysql 5.7

issue: When setting up a O2M field in a collection to another collection containing a repeater, the repeater is not usable.

reproduce (See video):
- setup a collection1 with a repeater field which contains any field.
- setup a collection2 with a O2M relationship with collection1 
- try adding an collection1 entry through collection2, the repeater fields are not visible

![2020-10-06_16-01-55 (3)](https://user-images.githubusercontent.com/6372094/95212553-1b814680-07ee-11eb-94c9-bd7547146e98.gif)

**Comment by Nitwel** [comment]
This is caused because you do not have a template set. @rijkvanzanten should we make that field of the repeater required or have the first field of the repeater as the default template?

**Comment by jojomillennium** [comment]
Thanks, it does work if a template a set.!
The first field as a default would be my preference. Or all fields of the repeater separated by a | , with an elipsis if too long for the space?
