### ISSUE TITLE
Settings > Presets: Not working

### ISSUE THREAD

**Issue by benhaynes** [directus/next#553]
Adding a collection, scope, and layout to a NEW preset (not saved) does not show anything in the preview. Clicking on any of the filters in the page sidebar does not do anything (or throw any errors).

**Comment by benhaynes** [comment]
Maybe due to the "collection" sending a formatted value? `directus_activity` seems to work... but is broken in the dropdown since that option doesn't exist.

![Screen Shot 2020-10-06 at 4 06 35 PM](https://user-images.githubusercontent.com/522079/95254518-00aed200-07ee-11eb-89d5-889d5f521219.png)

**Comment by rijkvanzanten** [comment]
Roles doesn't use layouts, so that's expected. Webhooks is interesting, as it's admin only 🤔
