### ISSUE TITLE
Settings > Collection field type Numeric, can't edit Length of decimals/doubles

### ISSUE THREAD

**Issue by prikr** [directus/next#560]
Hi guys,

Today I ran into the bug which @rijkvanzanten and I already discussed on Discord. This will be the reminder of the bug.

The actual bug:
We can't edit the field length in here, if the MySQL databasetype === double.
![image](https://user-images.githubusercontent.com/48241027/95263640-5f943b80-082e-11eb-9b93-2c737398e9c4.png)

`error.js:9 Error: SQLSTATE[42000]: Syntax error or access violation: 1439 Display width out of range for column 'test' (max = 255)`

The standard length of `10` has to be used always. 

I ran into this issue when I was working with longitudes and latitudes. Workaround for me was to parse them to strings, and when using them in code again, parse them back to doubles.

**Comment by rijkvanzanten** [comment]
(note to self, screenshot shows v8.8, but v9 likewise doesn't show length/precision yet
