### ISSUE TITLE
Add Custom CSS option to Project Settings

### ISSUE THREAD

**Issue by benhaynes** [directus/next#561]
A code interface that allows dynamic overriding of CSS. Only in RC in case this is easy and causes a schema change (avoids migration).

**Comment by Nitwel** [comment]
I'm not 100% sure but I think this also needs to be implemented into the api schema.
@rijkvanzanten could you show me how to do that?

**Comment by maartenvn** [comment]
How about a single CSS endpoint, provided by the api, which is linked in the index.html of the app?
This way the CSS is loaded at initial load and wouldn't require a delay (until the JS bundle is done downloading/parsing)

**Comment by maartenvn** [comment]
Just an extra field inside `directus_settings` would suffice then, if implemented as I described.

**Comment by rijkvanzanten** [comment]
That's a pretty nifty approach! Didn't think about that. What would be a good endpoint path? 🤔 

We know that `/settings` is a singleton, so we could make it `/settings/custom_css`. We could even expose any field of any singleton under that `/:collection/:key` path, but lets not get ahead of ourselves here 😁
