### ISSUE TITLE
Modify the label of a repeater "Add" button does not accept space unless edited

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#571]
9.0.0beta7 docker image with DB pointing on a mysql 5.7

When typing a new label in the "Add New Row" Label, space bar key is not accepted.
User need to move the cursor afterwords to where space is desired and press the space bar there.

![2020-10-07_13-37-07 (1)](https://user-images.githubusercontent.com/6372094/95326103-5ba20100-08a2-11eb-8200-def010b7b3c8.gif)

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/next/commit/60d038deff45b8a549a35c24dd8cbec72b17c421
