### ISSUE TITLE
Users see items that should be filtered by permissions in role

### ISSUE THREAD

**Issue by MajesteitBart** [directus/next#596]
For example, a user should see only users in the same role. However, he sees everything. I used this example:
```
{
    "role": {
        "_eq": "$CURRENT_ROLE"
    }
}

```

### Project Details
```
Directus Version: 9.0.0-beta.10
OS: Ubuntu
Database: MySQL 5.7.31
Nodejs 10.22.1
NPM 6.14.6
```

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-10-12 at 16 36 10](https://user-images.githubusercontent.com/9141017/95788192-0ce0d680-0ca9-11eb-9915-04cda0d86021.png)

This seems to do the trick for me. Where did you add those permissions @MajesteitBart ?

**Comment by MajesteitBart** [comment]
I don't know what to tell you, but it happens everytime I try. Is it an error in something you see here?

Just tried it again
1. Create new directus_role: Customer2
2. Change read permission of users: 
```
{
    "role": {
        "_eq": "$CURRENT_ROLE"
    }
}

```
2. Assign user John Doe the Customer2 role
3. Login using John Doe, still see all Admins and users from other roles.

![image](https://user-images.githubusercontent.com/8057288/95790245-4c2a1a00-0cdf-11eb-8861-316ecf3ac363.png)
![image](https://user-images.githubusercontent.com/8057288/95790261-52b89180-0cdf-11eb-9f66-3734cd10422a.png)
![image](https://user-images.githubusercontent.com/8057288/95790282-59df9f80-0cdf-11eb-964b-7efd6a4a2b63.png)
![image](https://user-images.githubusercontent.com/8057288/95790402-94e1d300-0cdf-11eb-8aa2-b8a0fa00d424.png)

**Comment by rijkvanzanten** [comment]
Raar, could be that it might've been fixed since the last beta, as I'm testing this on the latest from `main` as opposed to the latest release

> I'm not sure, but I don't think closed issues trigger a notification, so here you go @rijkvanzanten :)

I get notified about everything that happens, regardless of repo/status 😁

**Comment by MajesteitBart** [comment]
Very raar inderdaad! I would test the main repo for you, but I've used the npm command to start the project, so that would probably cause some other issues...
