### ISSUE TITLE
Docs: links for the extension guides in the nav don't match file names

### ISSUE THREAD

**Issue by MiniDigger** [directus/next#597]
https://github.com/directus/next/blob/main/docs/nav-app.yaml#L58
vs
https://github.com/directus/next/blob/main/docs/guides/extensions/interfaces.md

if somebody can indicate what the right path should be, I would be able to PR a fix, either fixing the nav, or renaming the files

**Comment by Nitwel** [comment]
As far as I know @benhaynes is still writing them so lets wait until that's done.

**Comment by MiniDigger** [comment]
fixed by d8babfd3b06913f62408b85f06989b4dcbe4f069
