### ISSUE TITLE
Unable to update PK field in collection

### ISSUE THREAD

**Issue by apstanisic** [directus/next#613]
When I try to change id filed from non managed to managed, it throws 500 error. It throws this error only for primary key. 
Beta 10 and postgres
```
error alter table "posts" alter column "id" drop not null - column "id" is in a primary key
```
Payload in PATCH request:
```
{
   "field":"id",
   "type":"uuid",
   "schema":{
      "name":"id",
      "table":"posts",
      "type":"uuid",
      "default_value":"gen_random_uuid()",
      "max_length":null,
      "is_nullable":false,
      "is_primary_key":true,
      "has_auto_increment":false,
      "foreign_key_column":null,
      "foreign_key_table":null,
      "comment":null,
      "schema":"public",
      "foreign_key_schema":null
   },
   "meta":{
      "id":108,
      "collection":"posts",
      "field":"id",
      "special":null,
      "interface":null,
      "options":null,
      "display":null,
      "display_options":null,
      "locked":false,
      "readonly":false,
      "hidden":false,
      "sort":null,
      "width":"full",
      "group":null,
      "translation":null,
      "note":null
   }
}
```

**Comment by rijkvanzanten** [comment]
Are you sure that's the payload, and not what's returned? The request payload for "click to manage" should be (and is on my end) the following:

```json
{"meta":{}}
```

**Comment by rijkvanzanten** [comment]
Ohhhh, you mean updating a PK field in general, gotcha

**Comment by benhaynes** [comment]
In MySQL, I added the following directly into the database (fresh install)

```
articles.id — INT(11)
articles.title — VARCHAR(200)
```

And clicked manage for the collection/fields... and things worked as expected.

**Comment by apstanisic** [comment]
It's request payload, I don't know why meta is not empty. 
I didn't change any options for PK, just took default for that field.

Here are steps to reproduce:
Create table outside of Directus
```
CREATE TABLE test_pk (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rand_value text
)
```
Go into that model in Directus, click on id field, and click save.

![rsz_1screenshot_from_2020-10-13_17-10-28](https://user-images.githubusercontent.com/19491605/95880041-5b5ca680-0d77-11eb-8c32-7746ac6b2aa8.png)

**Comment by rijkvanzanten** [comment]
Yeah, that last bit 

> and click save

was the missing piece of the puzzle. Clicking the field itself makes it "managed", even when you don't save 🙂

**Comment by apstanisic** [comment]
You're right. Then the issue is that we can't change any options for PK, including interface and display.
