### ISSUE TITLE
Docs module not showing content in Edge for Android

### ISSUE THREAD

**Issue by MajesteitBart** [directus/next#616]
Already tested disabling tracking and adblockers. Example is running beta 10, but I think the problem was there in earlier versions.

Chrome is fine
![Screenshot_20201011-123438_Chrome.jpg](https://user-images.githubusercontent.com/8057288/95685214-d34f9300-0bf6-11eb-9928-1cfec151c020.jpg)

Firefox also fine

![Screenshot_20201011-123405_Firefox.jpg](https://user-images.githubusercontent.com/8057288/95685218-d6e31a00-0bf6-11eb-9ec0-c5d148e688e7.jpg)

Edge doesn't show the docs
![Screenshot_20201011-123356_Edge.jpg](https://user-images.githubusercontent.com/8057288/95685244-0134d780-0bf7-11eb-887b-d20235af7215.jpg)

`Directus Version: 9.0.0-beta.10
OS: Ubuntu
Database: MySQL 5.7.31
Nodejs 10.22.1
NPM 6.14.6`

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/next/pull/762
