### ISSUE TITLE
Error editing unmanaged collection

### ISSUE THREAD

**Issue by benhaynes** [directus/next#629]
```
articles.id — INT(11)
articles.title — VARCHAR(200)
```

Add in database, go to "Create Item" page.

![Screen Shot 2020-10-13 at 10 30 11 AM](https://user-images.githubusercontent.com/522079/95874947-77445600-0d3f-11eb-9359-a94800534381.png)

**Comment by rijkvanzanten** [comment]
Fixed in bab82426
