### ISSUE TITLE
Option for user to only change items that belong to him

### ISSUE THREAD

**Issue by apstanisic** [directus/next#635]
In v8 there is an option to allow user to only change items that belong to him or to his role.
![demo directus io_admin_](https://user-images.githubusercontent.com/19491605/95917364-6c72db00-0daa-11eb-9564-3b44e268a80f.png)

**Comment by rijkvanzanten** [comment]
You can set the permissions as follows:

```
{
  "user": {
    "_eq": "$CURRENT_USER"
  }
}
```

and/or

```
{
  "role": {
    "_eq": "$CURRENT_ROLE"
  }
}
```

in the permissions setup
