### ISSUE TITLE
Presets are not reliable in high latency environments

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#638]
I imagine this was caused because I'm connected to a remote database and latency is ultra high, but: when trying to display multiple columns and sorting them out, I ended up with multiple entries of the "same" presets, which makes them totally unable to be edited. 

I had to delete all the created entries of the same preset in the user scope (~5 entries) in order to get the fields to be editable again.

**Comment by WoLfulus** [comment]
It also doesn't seem to persist. The setup was reset.

**Comment by rijkvanzanten** [comment]
Classic racing condition

**Comment by WoLfulus** [comment]
this makes the ui look so weird because stuff keeps changing out of nowhere because of the rollback when request finishes

I'm not sure how this would be handled though:

- queue up the changes and only request the next ones when one finishes? 
- debouncing for a while before requesting a save?
- apply button?

**Comment by rijkvanzanten** [comment]
I think option 4:

* Cancel/ignore response for any in-progress request in favor of only using the latest state
