### ISSUE TITLE
No way to create entries if field is required but doesn't allow edits

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#654]
It's impossible to create new entries if a field is marked as  required, doesn't have a default value and doesn't allow edits. Would be nice to also support an option to allow editing the field when creating an item, and not when editing.

**Comment by rijkvanzanten** [comment]
> It's impossible to create new entries if a field is marked as required, doesn't have a default value and doesn't allow edits. 

I think this is to be expected and is not a bug that we can prevent 🤔 

Lets open a discussion for idea 2:

> Would be nice to also support an option to allow editing the field when creating an item, and not when editing.

**Comment by WoLfulus** [comment]
on #658
