### ISSUE TITLE
Can't exit a modal clicking outside or hitting esc.

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#659]
Even if I haven't done anything in the interface, just opened to view an information, I'm unable to exit the modal by clicking outside it or hitting escape. If this is to avoid loosing data, we can confirm with a second escape hit.

**Comment by benhaynes** [comment]
Which modal? Any specific steps here? Some are persistent, and others don't allow closing with esc due to potential data loss).

**Comment by rijkvanzanten** [comment]
Duplicate of #120

The click outside is on purpose so you don't miss-click when going for the next/save button. Esc should still work though, but that's what https://github.com/directus/next/pull/600 aims to solve
