### ISSUE TITLE
BETA 11: Unknown directus_collections.id field

### ISSUE THREAD

**Issue by lluishi93** [directus/next#667]
Just updated beta 10 to beta 11, and right after the login I get the following error:

![image](https://user-images.githubusercontent.com/14786440/96110569-52d3af80-0ee0-11eb-9a12-2e968e394212.png)

As seen in the table description, it doesn't exist that id field:

![image](https://user-images.githubusercontent.com/14786440/96110623-64b55280-0ee0-11eb-8d5d-6d8b03baa1f3.png)

Is this a bug itself or something am I missing?

**Comment by Nitwel** [comment]
Try setting the `one_primary` column from `id` to `collection` in `directus_relations` like on the image below.
![grafik](https://user-images.githubusercontent.com/22577866/96117395-5409da00-0eea-11eb-9294-2e4ade5b7593.png)
