### ISSUE TITLE
[MSSQL] SQL connection fails when deploying with npx

### ISSUE THREAD

**Issue by mscbpi** [directus/next#673]
Steps to reproduce:
`$ npx create-directus-project my-project`
Select Microsoft SQL Server

Override port or re-enter 1433.

```
(node:21392) UnhandledPromiseRejectionWarning: TypeError: The "config.options.port" property must be of type number.
```

same as https://github.com/directus/next/issues/363 but this time we are not dealing with ENV (env was corrected).

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/next/pull/623
