### ISSUE TITLE
WYSIWYG interface visuals

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#681]
In wysiwyg interface there is some inconsistances and confusing things.

1. In dark skin, when focusing a field on popup (media and links) the field get light background instead of border highlighting, it also affect the source code editor.
![image](https://user-images.githubusercontent.com/1009639/96228387-326a2a80-0f9e-11eb-9b65-45b514727064.png)

2. Link modal uses different style dropdown input
![image](https://user-images.githubusercontent.com/1009639/96228598-73fad580-0f9e-11eb-9ade-2e6ced060a06.png)

3. In the interface settings itself, there are 3 options for font (this is also for other fields where font is available to pick) which are Sans Serif, Monospace and Serif, but I do think it will be better to have also "Default" or to add a default meaning to the Sans Serif since the app client is using it for fonts.

---

### Project details
Directus Version: 9.0.0-beta.13
Environment: production
OS: Linux 4.19.76-linuxkit
Node: 14.13.1

**Comment by benhaynes** [comment]
1. Should be possible
2. Might use a system input, which we can't style. We'll have to look into swapping this out for our custom dropdown (if possible)
3. We can just have "Sans Serif" as the default here

@Nitwel — This media modal (and any other popups within the WYSIWYG) have always been rather ugly (TinyMCE). It'd be great we if could get the styling more consistent with the Directus design system.
