### ISSUE TITLE
BETA 13: Can't save translations in singleton

### ISSUE THREAD

**Issue by lluishi93** [directus/next#684]
1. Create collection with translations
2. Make that collection singleton
3. Try to save translations
4. Check that translations get saved at DB level, but front-end doesn't reflect those changes

Something similar happened here https://github.com/directus/next/issues/544 but with M2M.

**Comment by Nitwel** [comment]
This seems to be the same issue as in #544 which already got fixed.
If this problem still occurs, please reopen this issue again.
