### ISSUE TITLE
Commenting on content

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#691]
When commenting on content, the comment is stored but trigger error.
![image](https://user-images.githubusercontent.com/1009639/96331748-89d4cd00-1068-11eb-9aa2-05bd386b778e.png)

Also the mention button and emoji do nothing.

**Comment by benhaynes** [comment]
Thanks! We'll get the bug fixed ASAP. As for mentions and emoji, we have a separate ticket for that... hopefully we get a PR to help move that along (we're 100% focused on stability for now), otherwise we'll have to remove those icons for 9.0.0 production release.

**Comment by rijkvanzanten** [comment]
I pushed up a tweak to remove those icons (and some other tiny fixes in the shortcut area), but I haven't been able to reproduce the .length issue 🤔 What db do you use?

**Comment by dimitrov-adrian** [comment]
I am almost sure it might be caused by #715. I cannot reproduce it anymore too.
