### ISSUE TITLE
Modals / alerts isn’t mobile friendly

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#702]
Chrome on iOS 14

Width of modals/alerts doesn't fit well. Too wide. 

New file/upload, warnings etc

![image](https://user-images.githubusercontent.com/20950568/96353537-54ae9600-10cd-11eb-9263-6a74087e7f3d.jpeg)

**Comment by benhaynes** [comment]
Thanks! Still some mobile polish required... we do this in sprints and it's been a while since we've done one. Here is a new mock for how notifications should look.

![Frame 1](https://user-images.githubusercontent.com/522079/96466625-02b65f00-11f8-11eb-8248-c7892f0fb923.png)
