### ISSUE TITLE
Permissions are not inherit by sub-items of an permitted item

### ISSUE THREAD

**Issue by MajesteitBart** [directus/next#710]
Permissions are not inherit by sub-items of an owned item. For instance:

**Company collection**
- has a primary_contact field
- is only visble for the customer users that are marked as primary contact

**Assessment collection**
- is related to a company
- should only be visible to customer users that are marked as primary contact of the related company record.

But, what happens is the customer user sees all assessments, but just shows an empty field where company should be.

Permissions I used for the customer user:
![image](https://user-images.githubusercontent.com/8057288/96419134-fe884280-11f3-11eb-94ae-a2f69b949acf.png)

User only sees company he should:
![image](https://user-images.githubusercontent.com/8057288/96419173-0c3dc800-11f4-11eb-9055-00836794f8ba.png)

However, sees all the assessments:
![image](https://user-images.githubusercontent.com/8057288/96419209-18298a00-11f4-11eb-842b-0cc83773e2e9.png)

**Project settings**
```
Directus v9.0.0-rc.0
Postgres 10.14
Nodejs 10.22.1
NPM 6.14.6
Ubuntu 18.04.1
```

**Comment by MajesteitBart** [comment]
Hey @rijkvanzanten, is this a problem that only exists with Postgres? I want to test some things, but need this bug to be fixed in it.

**Comment by rijkvanzanten** [comment]
No, I believe this happens regardless of DB driver used. The problem here has to do with the way `knex` adds joins to existing queries, so I'm battling our own dependency a bit here
