### ISSUE TITLE
Setting M2M field with mouse only doesn't work

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#718]
Setting relationship from existing table does not allow to advance (next button is not active) and stuck with no errors in console. Manual typing in some of fields helps if reseting the relation ids

**Comment by Nitwel** [comment]
Please give some more information on how to recreate this.

> Manual typing in some of fields helps if reseting the relation ids

Where did you have to type in?

**Comment by dimitrov-adrian** [comment]
I cannot reproduce it anymore with last changes.
The issue was the advance button (blue save button on right top corner) which was inactive and needed to type in some of relation fields to activate.
