### ISSUE TITLE
M2M relation. Saved entries are not displayed

### ISSUE THREAD

**Issue by Cruze** [directus/next#726]
Selected and saved data are not displayed. The entries are stored in the database.

Version 9.rc0

I have another case. A M2M relation to the same table does not work at all. Here there is a direct error, that the configuration would be incorrect.

**Comment by rijkvanzanten** [comment]
You gotta give us a little more to work with here..

What database vendor do you use? 
What version of database?
What version of Node?
What does your relationship look like?

Basically I want to know everything I need in order to recreate your setup on my end 🙂

**Comment by Cruze** [comment]
Ubuntu 18.04
Webmin 1.955
Virtualmin 6.12
Apache 2.4.29
MySQL version 5.7.31
NodeJS 14.13
Directus V9 rc.0

**Comment by Nitwel** [comment]
Items might not be displayed if there is an issue with the relation / junction item.
I fixed that it was not possbile to have a m2m to the same collection in the PR above.
