### ISSUE TITLE
Entry edit fail to render

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#727]
Imported external database and just manage some of tables and fields. Then go and edit entry.
![image](https://user-images.githubusercontent.com/1009639/96513713-34b4d900-126b-11eb-94f3-a491b31b3681.png)

### Project details
Directus Version: 9.0.0-rc.0
Environment: development
OS: macOS Catalina (10.15)
Node: 12.17.0

**Comment by Nitwel** [comment]
Could you give some information on what fields where in the collection and maybe the file you imported.

**Comment by dimitrov-adrian** [comment]
Just imported some data for testing (https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_Sqlite.sql)

The table caused such issue should be managed with unmanaged fields (for example Media Type)

**Comment by Nitwel** [comment]
Do you remember what item you clicked at and in which collection it was?

**Comment by rijkvanzanten** [comment]
@Nitwel I'm 90% sure the detail.vue file in the collections module is reading `collection.schema.display_template` somewhere, without checking if `collection.schema` exists. Probably the title
