### ISSUE TITLE
Issue with O2M fields with more then one value

### ISSUE THREAD

**Issue by goggi** [directus/next#728]
9.0.0-rc.0
Postgres
Node

I'm having issues with the O2M field. When opening an item that has a O2M field with multiple relations there is an error: 

code: "INTERNAL_SERVER_ERROR"
message: "select "work_order_task_log"."id" from "work_order_task_log" where "work_order_task_log"."id" in ($1) limit $2 - invalid input syntax for type uuid: "a943830e-e01c-46c7-bea2-a62f0f20495e,eb5102c5-a2e4-4590-a6e2-d3a3a978ad18""

It works fine if there is only one relation.

URL when there is one relation:
items/work_order_task_log?fields[]=id&filter[id][_in]=a943830e-e01c-46c7-bea2-a62f0f20495e

URL when there are two relations:
items/work_order_task_log?fields[]=id&filter[id][_in]=eb5102c5-a2e4-4590-a6e2-d3a3a978ad18,a943830e-e01c-46c7-bea2-a62f0f20495e

**Comment by Nitwel** [comment]
I need a bit more info here.
Please describe in detail the relations in your situation / how the collections are connected.

**Comment by goggi** [comment]
Some screenshots for you: 

![image](https://user-images.githubusercontent.com/1946339/96560202-48d5f600-12be-11eb-8ec1-9f39f16ebf35.png)

![image](https://user-images.githubusercontent.com/1946339/96560268-5f7c4d00-12be-11eb-904a-47d2f444c8c9.png)

![image](https://user-images.githubusercontent.com/1946339/96560286-673bf180-12be-11eb-93d7-72737892a8a0.png)

**Comment by goggi** [comment]
Database: 

![image](https://user-images.githubusercontent.com/1946339/96561700-31980800-12c0-11eb-903a-c16b09ac76ca.png)

![image](https://user-images.githubusercontent.com/1946339/96561737-3e1c6080-12c0-11eb-95a4-44d80caf3c38.png)

**Comment by Nitwel** [comment]
I did not manage to recreate this but my guess is that this got already fixed in 16cd8838a9fd2f94617f1818ba4060fb113146af.
If you run into this issue in the next release, please reopen this issue.
