### ISSUE TITLE
View record in activity reset filter

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#736]
Go to http://localhost:8080/admin/activity?action=update and click some record, when closing viewed record, the filter "Update" is reset.

---

### Project details
Directus Version: 9.0.0-rc.1
Environment: development
OS: macOS Catalina (10.15)
Node: 12.18.3

**Comment by benhaynes** [comment]
Issue confirmed. @rijkvanzanten would this be stored in user preferences/presets? Alternatively, we could not overwrite the underlying dataset and somehow "remember" the `?action=update` query parameter when closing the drawer.

**Comment by rijkvanzanten** [comment]
> would this be stored in user preferences/presets?

Nope!

> Alternatively, we could [...] somehow "remember" the ?action=update query parameter when closing the drawer.

This is the case, it's the same setup as in folders -> files

**Comment by benhaynes** [comment]
Ahh, I just noticed that Folders/Files doesn't remember where you were either. How/where would we store this info so the Collection Detail will be persisted?

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/next/commit/3a54e396b8831112e74013bc1937e9d4995f03cd
