### ISSUE TITLE
No feedback when extensions fails to initialize

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#738]
When there's an error initializing extensions, only `Couldn't register hook "name"` is shown. Logging the error will provide a lot more information on what is going on as this is really hard to debug/find the cause.

**Comment by rijkvanzanten** [comment]
It does log the error:

https://github.com/directus/next/blob/b98499b1402e2d28c9ebcbeecb8cb38308c58d0f/api/src/extensions.ts#L74-L75

What log level are you using?

**Comment by WoLfulus** [comment]
I was probably missing since the "error" is printed in green, while the warn was red. can we switch the level to something else since it's an error? or at least match the warn
