### ISSUE TITLE
Last repeater item is displayed as open. 

### ISSUE THREAD

**Issue by goggi** [directus/next#743]
Not sure if this is a bug. But when I open an item with JSON repeaters the last item in each repeater is displayed as open. It would be great if they started as closed as it speeds up the load time. It's a new feature introduced in RC. Earlier they all started as closed. 

How it looks when I open an item:

![image](https://user-images.githubusercontent.com/1946339/96707351-0d0f5f00-1398-11eb-9c1c-4f8a21d633f4.png)

How it used to look:
![image](https://user-images.githubusercontent.com/1946339/96707399-1a2c4e00-1398-11eb-8823-a5fd22267172.png)

---

### Project details
Directus Version: 9.0.0-rc.1
Environment: production
OS: Linux 4.15.0-88-generic
Node: 14.7.0

**Comment by rijkvanzanten** [comment]
What do you mean by

> It would be great if they started as closed as it speeds up the load time

How would it speed up the load time by having the last record collapsed?

**Comment by goggi** [comment]
Some of us abuse the repeater field :) 
So when I open an item that has a lot of repeater fields (complex structure), its slows the load time of the site if the last repeater item (of all repeater fields) starts as open.

Here you have an example:  https://i.imgur.com/MS11ytB.gif
I don't have that many repeaters here and there will have more in other collections, but you can see a very short delay when I open the item. This did not happen when all the repeaters started as closed.

**Comment by rijkvanzanten** [comment]
Interesting! That delay to me looks like a delay in the API fetching the data (cause it's showing the loading state correctly), but that wouldn't make sense as the repeater fields are all inline-json and don't require any fetching from the API that isn't done already anyways 🤔 The only thing that would make sense is that it takes Vue a split second longer to render out the dom tree with deep nested repeaters

**Comment by goggi** [comment]
You are probably right about the vue rendering. The API speed is excellent: 
![image](https://user-images.githubusercontent.com/1946339/96712204-0d5f2880-139f-11eb-979f-4b91f9008b07.png)

**Comment by benhaynes** [comment]
I'm not sure about loading times, but I would be fine adding an option to this interface that allows customizing when the elements are initially open, closed, or accordion (on load, on add new, on click)... similar to the setting for collection group override within project settings.

**Comment by Nitwel** [comment]
A PR for this is already on the way. It was a bug that the last item is initially open on load. It only should be open when adding a new one.

**Comment by benhaynes** [comment]
Makes sense!
