### ISSUE TITLE
RC: Accordion gets closed when entering item form

### ISSUE THREAD

**Issue by lluishi93** [directus/next#748]
1. Create some collections
2. Create some collection navigations, and set the accordions as START collapsed
3. Open any of the accordions, and proceed to click any of the collections inside

Expected behavior:
The accordions start collapsed (this is correct), but when the user opens any of them to see some collection items or to edit any item, that same accordion should remain open

Current behavior:
All accordions that had been set with the "Start collapsed" option, get closed once the user performs any of the actions mentioned below.

From my point of view, in order to achieve better UX, accordions that are opened by the user within the same session, should remain open. 

Example: A user opens the "Modules" accordion to edit some banners, and then goes to the "Cross elements" accordion to edit some CTAs, and he/she wants to switch between those quickly. If accordions get closed when editing an item or switching between collections, UX gets a little worse IMHO.

**Comment by benhaynes** [comment]
I think this is the same issue as below, we just need a global way to persist the navigation state in the vue store per session. Let's rename one of these tickets and have it solve all of these. @rijkvanzanten agree?

https://github.com/directus/next/issues/736
