### ISSUE TITLE
O2M interface item display improvement

### ISSUE THREAD

**Issue by goggi** [directus/next#749]
This is a minor ux improvement suggestion for the O2M interface. 

I'm displaying 3 columns in the O2M field and there is space for all of them to be visible. But it seems like it's using a fixed size for each column.  

![image](https://user-images.githubusercontent.com/1946339/96719514-c3c80b00-13a9-11eb-8649-7c1270bd9a61.png)

Would be nice if all the fields are fully visible if there is space. 

![image](https://user-images.githubusercontent.com/1946339/96719583-dd695280-13a9-11eb-90e4-07d3b1f32ba5.png)

---

### Project details
Directus Version: 9.0.0-rc.1
Environment: production
OS: Linux 4.15.0-88-generic
Node: 14.7.0

**Comment by benhaynes** [comment]
The same applies to the table layout too, ideally we add "right-click" to the column headers, and there are resize options for manual (px) or auto (tries to fit content). We should also discuss how we want to handle min-width, max-width, and recommended width (eg: for the status dot or icons).
