### ISSUE TITLE
Issue Chrome version 84 or lower

### ISSUE THREAD

**Issue by Cruze** [directus/next#750]
We had an issue with chrome 84 or lower
All above are fine.

Login is not working. White screen.

![image](https://user-images.githubusercontent.com/1686589/96721770-e4de2b00-13ac-11eb-8470-9289a17aa065.png)

**Comment by Nitwel** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
ReplaceAll got added in chrome version 85 so thats why.
We could replace `replaceAll` with `replace(/./g)` but shouldn't this be done by webpack automaticly @rijkvanzanten ?
