### ISSUE TITLE
m2m fields for existing items not shown in edit window

### ISSUE THREAD

**Issue by bartlibert** [directus/next#755]
I have set up a m2m collection as follows:
![image](https://user-images.githubusercontent.com/948770/96837028-12c37e00-1446-11eb-91e6-46fca88aa379.png)

`praesidumfuncties` above is itself a m2o relationship:
![image](https://user-images.githubusercontent.com/948770/96837108-2f5fb600-1446-11eb-82bd-30c67c4ff02b.png)

If I create a new `praesidumfuncties` item in the m2m collection, it shows up correctly in the interface (`Functie` is a dropdown string of `praesidumfuncties`, `naam`, `voornaam` and `bijnaam` are strings of `praesidiumleden`)

![image](https://user-images.githubusercontent.com/948770/96836834-d3952d00-1445-11eb-9d58-272d4526b860.png)

However, if I open the collection afterwards, or if I try to add an existing item to it, the fields of the `praesidiumleden` item are not shown anymore:

![image](https://user-images.githubusercontent.com/948770/96838094-b19caa00-1447-11eb-8e4f-bfcd73521441.png)

Note that the data is correctly saved in the (postgresql) database.

This is on directus 9.0.0-rc.1

**Comment by Nitwel** [comment]
Already good explanation but could you give me direct steps on how to receate this.
For example:
- 1 Create collection X and add these fields to it...
- 2 ...

**Comment by rijkvanzanten** [comment]
@Nitwel I think those three fields `voornaam` / `naam` / `bijnaam` are fields on the `-leden` table that's nested again from the m2m related collection, so in dotnotation the m2m fields would use `-functies` (related) -> `persoon` (m2o) -> `voornaam`

It is probably that extra level that isn't fetched correctly somewhere 🤔

**Comment by bartlibert** [comment]
A minimal reproduction scenario:

1. Create a new collection called `person` and add a standard text field `name` to it
2. Create a new collection called `function` with the following fields:
    -  A standard text field `position`
    - A M2O relation called `person` with settings as below and display template `name` for both interface and display
![image](https://user-images.githubusercontent.com/948770/96866877-3f8a8c00-146c-11eb-896d-7f91ba511114.png)
3. Create a new collection called `board` and add a M2M field called `member` with following settings:
![image](https://user-images.githubusercontent.com/948770/96867134-9bedab80-146c-11eb-8f60-0be78429fc6e.png)
![image](https://user-images.githubusercontent.com/948770/96867255-bc1d6a80-146c-11eb-8062-467f08a03af8.png)
Note: I cannot set the display settings at this point, but when I edit the `member` field afterwards, I set the display settings to:
![image](https://user-images.githubusercontent.com/948770/96867442-043c8d00-146d-11eb-8730-e1abe890c5ed.png)
4. Create a new `board`
5. Select `Create Item` to add a new `member`
6. Enter `foo` for `position` and create a new person with `name` `bar`
7. Observe that the new `person` is added:
![image](https://user-images.githubusercontent.com/948770/96867699-5a113500-146d-11eb-99ee-964a2e6aef28.png)
8. Save the `board`
9. Open the `board` again and observe that the `position` field is shown, but the `Name` field isn't: 
![image](https://user-images.githubusercontent.com/948770/96867909-993f8600-146d-11eb-87a6-db7436287027.png)

**Comment by Nitwel** [comment]
Thank you very much. 😄
