### ISSUE TITLE
Select M2M inteface by default when creating m2m relations

### ISSUE THREAD

**Issue by lluishi93** [directus/next#763]
1. Create collection A
2. Create collection B
3. Create a field in Collection A as a M2M pointing to Collection B
4. Check that, when going through the field set-up wizard, the M2M interface is not selected by default:

![image](https://user-images.githubusercontent.com/14786440/97006811-b1cca080-1540-11eb-99b6-2416c4490b7b.png)

Expected behavior: M2M should be selected by default, if not, the field shows up misconfigured

**Comment by rijkvanzanten** [comment]
@Nitwel  can you pick this up? I think by moving to that local type check we talked about the other day for interfaces and displays, this should be resolved too. As soon as there's only 1 available interface, it'll be selected automatically.

**Comment by Nitwel** [comment]
So the files interface should not be shown?

**Comment by rijkvanzanten** [comment]
Not for a regular m2m field, correct
