### ISSUE TITLE
GraphQL doesn't return Singleton data

### ISSUE THREAD

**Issue by flayks** [directus/next#769]
From a bare minimum/super fresh database and project setup with the latest RC of the version 9 (RC2 as I write it), I can't figure out how to get a result that is not `null` from a Singleton query. The REST API gives me a result, but nothing with GraphQL.

The query:
```gql
{
  items {
    about {
      contact_email
      intro_image {
        id
      }
    }
  }
}
```
Result for a Singleton with GraphQL:
![image](https://user-images.githubusercontent.com/273716/97017521-50abc980-154e-11eb-9daa-50ac69ae7df8.png)

Result for the same Singleton but with the REST API:
![image](https://user-images.githubusercontent.com/273716/97017710-8c469380-154e-11eb-9f9b-002fc6ae6427.png)

The data is there then, but only works with a Collection of repeatable items, not Singletons. Same with another Singleton with data as well.

Maybe I'm misunderstanding something? Or is it a bug?

It works perfectly for a Collection as shown here:

![image](https://user-images.githubusercontent.com/273716/97018040-f3644800-154e-11eb-9227-003894275b57.png)

The Singleton itself:

![image](https://user-images.githubusercontent.com/273716/97017610-6c16d480-154e-11eb-85d0-93af3d84f6f9.png)

**Comment by rijkvanzanten** [comment]
I found an issue in the way relationships were constructed in the graphql endpoint and I think that fixed this too. A quick singleton setup on my end works as expected now:

![Screen Shot 2020-10-26 at 11 52 18 AM](https://user-images.githubusercontent.com/9141017/97164019-ce0b5000-1781-11eb-8bb7-19637a1871eb.png)

**Comment by flayks** [comment]
Awesome! Thanks @rijkvanzanten. That'll definitely help me with my current project 💯

**Comment by flayks** [comment]
Sorry to kind of reopen that issue again @rijkvanzanten but I feel that even with the fix you've made and the RC3, the problems remains the same on my install.

I've created a new singleton (on the same install tho), with just one field. Same problem, the data returns `null`.
Anything about permissions that I would have missed or something else?

![image](https://user-images.githubusercontent.com/273716/97502997-8698e580-1974-11eb-8d19-36ae35c4d018.png)

Data from `http://localhost:8055/items/news`:
`{"data":{"id":1,"date_updated":null,"yolo":"Yiha"}}`

**Comment by flayks** [comment]
Another go with "default" fields:

![image](https://user-images.githubusercontent.com/273716/97504601-7afaee00-1977-11eb-8cbf-94e4cf7f762c.png)

**Comment by rijkvanzanten** [comment]
@flayks Would you be able to share a DB dump so I can reproduce your setup exactly? It's working as expected on my end.. (Also, what DB are you using?)

**Comment by tchapi** [comment]
Works on my side, in both REST and GraphQL endpoints : 

<img width="1030" alt="Screenshot 2020-10-29 at 20 03 44" src="https://user-images.githubusercontent.com/1944007/97620458-e600ff00-1a21-11eb-9d5b-8f31a754b263.png">
:

<img width="1027" alt="Screenshot 2020-10-29 at 20 03 32" src="https://user-images.githubusercontent.com/1944007/97620454-e4373b80-1a21-11eb-994a-2eb2a8b30314.png">

I'm using PostgreSQL 10.3 BTW.

<img width="845" alt="Screenshot 2020-10-29 at 20 01 10" src="https://user-images.githubusercontent.com/1944007/97620650-25c7e680-1a22-11eb-9292-20360f231748.png">


---

### Project details
Directus Version: 9.0.0-rc.3
Environment: production
OS: macOS Catalina (10.15)
Node: 12.19.0

**Comment by flayks** [comment]
@rijkvanzanten alright, I tried with a fresh install on RC3 and a MySQL database, just created an `about` singleton with a `email` and `image` field, both filled with data, here is the result:

![image](https://user-images.githubusercontent.com/273716/97620905-79d2cb00-1a22-11eb-9d01-f9f088a38513.png)

I quite don't get what's happening, if it's on my side or not 🧐

**Comment by rijkvanzanten** [comment]
Could be a MySQL thing! I'll try it later today on MySQL 5.7 (I usually dev on Postgres 12.3 / MySQL 8)

**Comment by rijkvanzanten** [comment]
https://github.com/directus/next/blob/1e6ade241327f122717ba014d9e2a97e5c9bdd0b/api/src/services/graphql.ts#L517-L518

MySQL stores—and therefore Knex returns—booleans as `1` instead of `true` ᕕ( ᐛ )ᕗ

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-10-29 at 17 39 48](https://user-images.githubusercontent.com/9141017/97635443-bfd16400-1a0d-11eb-841d-924638e526f7.png)

Looking good now on your schema @flayks

**Comment by flayks** [comment]
Awesome! Looks good. Always a tricky little thing screwing up everything haha 🤷
Looking forward for the rc4!

**Comment by flayks** [comment]
Just to follow up, it's working now on my end, thanks @rijkvanzanten 👌
