### ISSUE TITLE
Custom permissions are not parsed after being loaded from the database

### ISSUE THREAD

**Issue by fribeau** [directus/next#776]
### The problem
I have created a `user` role that is supposed to be able to read only his `user object`. To do so, I have used the following custom permission on the `directus_user` collection in the `user` role:
```
{
    "id": {
        "_eq": "$CURRENT_USER"
    }
}
```

But the filter was never applied and I was always getting all the `user objects`.

### Why
I found out that the function [parseFilter](https://github.com/directus/next/blob/fc8bdffeee13acb00ca97afa9d0139507149918b/api/src/services/authorization.ts#L148) is called with a `string` instead of a `Filter` object.

I have printed the output of the `parseFilter` function and I get this:
```ts
const parsedPermissions = parseFilter(permissions.permissions, accountability);
console.log("PARSED_PERMISSIONS: " + JSON.stringify(parsedPermissions));
```
```
PARSED_PERMISSIONS: {"0":"{","1":"\"","2":"i","3":"d","4":"\"","5":":","6":" ","7":"{","8":"\"","9":"_","10":"e","11":"q","12":"\"","13":":","14":" ","15":"\"","16":"$","17":"C","18":"U","19":"R","20":"R","21":"E","22":"N","23":"T","24":"_","25":"U","26":"S","27":"E","28":"R","29":"\"","30":"}","31":"}"}
```

So I have then passed `JSON.parse(permissions.permissions)` instead of `permissions.permissions`
```ts
// @ts-ignore
const parsedPermissions = parseFilter(JSON.parse(permissions.permissions), accountability);
console.log("PARSED_PERMISSIONS: " + JSON.stringify(parsedPermissions));
```
```
PARSED_PERMISSIONS: {"id":{"_eq":"e8409624-ae3c-46f3-aa69-7e7690c42e80"}}
```
The output is now correct and as expected, I just get my `user object`.

### Where does it coming from ?
I don't think that the issue is coming from the **App** because I have what it is expected in the database:
![image](https://user-images.githubusercontent.com/19540101/97105657-f41aec80-16bc-11eb-9b89-5761a07e535d.png)
So I think is it more an **Api** issue or maybe a `knex` issue, I don't known.  The result of [this call](https://github.com/directus/next/blob/fc8bdffeee13acb00ca97afa9d0139507149918b/api/src/services/authorization.ts#L35) is:
```
[
  RowDataPacket {
    id: 122,
    role: '7c9fdffc-fec0-4de7-9c02-e04772be002e',
    collection: 'directus_users',
    action: 'read',
    permissions: '{"id": {"_eq": "$CURRENT_USER"}}',
    validation: null,
    presets: null,
    fields: '*',
    limit: null
  }
]
```

### Project details
Directus Version: 9.0.0-rc.2
Environment: development
OS: Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Node: 14.14.0
Branch: master
Commit: fc8bdffeee13acb00ca97afa9d0139507149918b

**Comment by rijkvanzanten** [comment]
Good catch! This is actually also the source of the occasional memory heap problem (it infinitely loops on that string object)
