### ISSUE TITLE
Unbranded Login-Screen

### ISSUE THREAD

**Issue by jekuer** [directus/next#784]
When I define a project color, logo, and public background, I except it to be reflected on the login screen (as with V8).
With V9.RC2, it only works, if I am already logged in (referring to the your-already-logged-in-screen). 
When logged out, it shows the default values.

Console says:
400 for /auth/refresh
403 for /settings (this looks suspicious

(Docker with PostgreSQL 11)

**Comment by rijkvanzanten** [comment]
> 403 for /settings (this looks suspicious

This is suspicious. The default permissions for the public role should allow access to the required fields in settings to render the public views correctly
