### ISSUE TITLE
Custom permissions not reflected at API and not per role

### ISSUE THREAD

**Issue by jekuer** [directus/next#785]
This might be related to https://github.com/directus/next/issues/776.

When I create 2 new roles,
and define permissions for a custom collection "pages", the following can be observed:

1. The setting is the same for both roles, no matter where I change it. And also for the public role.
2. ~~The setting is not reflected within the API - when I activate read access and try to access the collection via a respective user, I get the error "You don't have permission to access the \"pages\" collection."~~
3. When I have a look at the database permission table, there is only one row regarding "read" for only one role. The permissions column is NULL. For create and update, role is NULL too.
4. In another test, the database only showed rows for the admin role, no matter the setup at the other roles (there, (3) could not be replicated).

In any case, I was only able to use the Admin role for accessing the custom collection.
**Any ideas, where this breaks?**

**Comment by rijkvanzanten** [comment]
(2) Should be resolved in #786
