### ISSUE TITLE
Not possible to delete users

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#790]
Directus v9 rc2
PG 12

It's not possible to delete a user who has uploaded a file (or other activities with relations I assume).

```
directus: 11:17:22 🚨 error delete from "brf1"."directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_fkey" on table "directus_files" 
directus: error: delete from "brf1"."directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_fkey" on table "directus_files"
directus:     at Parser.parseErrorMessage (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/parser.ts:357:11)
directus:     at Parser.handlePacket (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/parser.ts:186:21)
directus:     at Parser.parse (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/parser.ts:101:30)
directus:     at Socket.<anonymous> (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/index.ts:7:48)
```

**Comment by rijkvanzanten** [comment]
Closing in favor of https://github.com/directus/next/issues/594

**Comment by danieljwestman** [comment]
@rijkvanzanten So for now it's not possible to delete users in the App? (every user usually has done something in the app and therefore has some references that breaks it..)

**Comment by rijkvanzanten** [comment]
It means that you can't delete a record that has a foreign key constraint to another record, so you'd have to nullify the uploaded_by field before you can delete a user. This is obviously not ideal nor how we want it to work, hence the 594 issue that aims to solve this with some proper UX
