### ISSUE TITLE
Drag&Drop file throws error

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#791]
9.0.0rc2 docker image with DB pointing on a mysql 5.7
Similar to issue #534, but this time the image is not even uploaded.

Request being fired: https://cms.millennium.ch/files/null

Getting response
:
`{"errors":[{"message":"update \"directus_files\" set \"storage\" = $1, \"filename_download\" = $2, \"title\" = $3, \"type\" = $4, \"uploaded_by\" = $5, \"modified_by\" = $6, \"modified_on\" = $7 where \"id\" in ($8) - invalid input syntax for type uuid: \"null\"","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

see screen recording below

![2020-10-27_11-16-48 (1)](https://user-images.githubusercontent.com/6372094/97288576-4f2c1b00-1846-11eb-949a-b134198e3ab6.gif)

**Comment by rijkvanzanten** [comment]
Was the file actually uploaded? (if you check your storage adapter)

**Comment by rijkvanzanten** [comment]
I think that commit might've fixed it, but I'm not 100% sure. Can you give this another spin on RC3 @jojomillennium? I'll release that in an hour or two

**Comment by jojomillennium** [comment]
@rijkvanzanten confirmed worked as expected in RC3!
thanks
