### ISSUE TITLE
User has a lot of roles... (duplications of field)

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#792]
Directus v9 rc2
PG 12

The user view has a lot of role fields. 

See attachment.

<img width="1307" alt="Skärmavbild 2020-10-27 kl  11 26 19" src="https://user-images.githubusercontent.com/20950568/97289398-6c151e00-1847-11eb-874d-fbe3d021fbcb.png">

**Comment by benhaynes** [comment]
Well that is... odd. I am not seeing this, so there must be something funky going on. I assume you didn't edit/extend the `directus_users` collection at all, right? My only thoughts go to migrations (which we haven't written in RCs yet).

**Comment by danieljwestman** [comment]
@benhaynes Nope, it's a clean installation and db...

**Comment by danieljwestman** [comment]
(latest commit)

**Comment by benhaynes** [comment]
"Latest commit"... is this being installed via npm or git (dev mode)?

**Comment by danieljwestman** [comment]
Yup, npm run dev

**Comment by rijkvanzanten** [comment]
@danieljwestman I'm not seeing this on my end on a fresh install on PG12. Would you be able to share a DB dump to rule out any funny business in there?

**Comment by danieljwestman** [comment]
@rijkvanzanten I'll check it out again

**Comment by rijkvanzanten** [comment]
I'll close this for now. https://github.com/directus/next/pull/811 will have significantly changed this flow so if it was still a problem, it might've been fixed now
