### ISSUE TITLE
Search does not include nested collections

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#793]
9.0.0rc2 docker image with DB pointing on a mysql 5.7

Searching entries in a collection does not include nested elements.

![image](https://user-images.githubusercontent.com/6372094/97289755-e0e85800-1847-11eb-8454-ea3557e85799.png)

Typically, searching in a collection having a field of type translations, will not search in the content of the corresponding translations themselves as they are located in another collection.

![image](https://user-images.githubusercontent.com/6372094/97290184-813e7c80-1848-11eb-974b-9ed8c704813f.png)

**Comment by benhaynes** [comment]
Not sure how this would be done without initial configuration or a more dedicated service. Relational data can be deeply nested, and you can have _many_  parent/related items... so this query would be pretty complicated and slow (especially considering we now support M2A relationships). I imagine this would need to be configured to allow-list the searchable relational fields, or have some dedicated table for concatenated values that can be more efficiently searched. @rijkvanzanten — thoughts?
