### ISSUE TITLE
GraphQL: Filter with Logical Operators ignores Relational filter

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/next#796]
The Relational filter in my screenshot works if I just use it as a single filter without Logical Operators. As soon as I add Logical Operators, the filter seems to be ignored.

![Screenshot_19](https://user-images.githubusercontent.com/15796397/97402999-2f6c2400-1926-11eb-8fd5-544a04829838.png)

Current Version: 9.0.0-rc.2

**Comment by rijkvanzanten** [comment]
I'm 85% sure this PR solved that: https://github.com/directus/next/pull/786

**Comment by rijkvanzanten** [comment]
Did some quick and dirty checks, looks good on my end
