### ISSUE TITLE
M2O relation (User) error

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/next#799]
I have an owner field in my collection which is connected by M2O to the directus_users table. There are 2 problems with the same error message:

1. The dropdown Interface doesn't work
2. If I use the Modal interface, the choosen User isn't displayed

The error message of the console: 

![Screenshot_23](https://user-images.githubusercontent.com/15796397/97404109-23816180-1928-11eb-90d6-c93230203f31.png)

Version: v9.0.0-rc.2

**Comment by rijkvanzanten** [comment]
I believe this is already fixed on the latest master. We'll push out a release end of day today, so keep a lookout on that one 🙂
