### ISSUE TITLE
Save button activated when opening a Item

### ISSUE THREAD

**Issue by goggi** [directus/next#800]
Hi!

The save button gets activated once I open an item even tho no changes have yet been done. 
I think it's related to the JSON field but I'm not 100% sure. 
Interface is CODE with JSON as language.
This was introduced in RC3. It was not an issue in RC2.

https://i.imgur.com/WCsBPRX.gif

---

### Project details
Directus Version: 9.0.0-rc.3
Environment: production
OS: Linux 4.15.0-88-generic
Node: 14.7.0

**Comment by goggi** [comment]
I can confirm that the issue is related to the JSON field. I created a new collection with a JSON field and got the same issue. Also, it only happens when you open the item from the collections site. If I open the item directly by entering the URL it works fine

https://i.imgur.com/kFzBJ3F.gif

**Comment by rijkvanzanten** [comment]
@goggi This might be on purpose actually. Do you have any default values set?

https://github.com/directus/next/pull/760

**Comment by nickrum** [comment]
@rijkvanzanten that's what I thought at first too. But the save button is also enabled for existing items without changes, which shouldn't happen.

I will try to fix this.
