### ISSUE TITLE
Improve empty-schema error in GraphQL

### ISSUE THREAD

**Issue by tchapi** [directus/next#801]
Hi,

When installing from scratch (with yarn + Postgres), the GraphQL endpoint does not work:
  - Fetching the schema returns a 500 (with no other error message)
  - Any query returns the same error: `Type items must define one or more fields.`

The other REST endpoints (and the admin) work fine

Any hint ?
Thanks a lot !

---

### Project details
Directus Version: 9.0.0-rc.3
Environment: production
OS: macOS Catalina (10.15)
Node: 12.19.0

**Comment by tchapi** [comment]
Ok, in fact this is due to incorrect credentials ... with the correct token, it works well. I guess the error message is quite misleading (a 403 would be better maybe ? Like for the other endpoints)

**Comment by rijkvanzanten** [comment]
You're right! It's actually an issue. The GraphQL endpoint doesn't have any items / resolvers available because the public role doesn't have read access to anything. This in turn causes Directus to pass an empty `items` object to GraphQL, which causes that error. 

I'll reopen this so we can optimize that error

**Comment by tchapi** [comment]
Super, thanks !

**Comment by tchapi** [comment]
I have tried on rc4 and if my auth is not good, the error message is now nice, **thanks** !

@rijkvanzanten I know this might be a really edgy case but this below still remains:

If I use `Authorization: bearer <perfectly_valid_token>` instead of `Authorization: Bearer <same_perfectly_valid_token>` (notice the capital B), I have the following response, which I think is unclear as well:

```
{
  "errors": [
    {
      "message": "Cannot query field \"items\" on type \"Directus\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```
