### ISSUE TITLE
Maximum call stack size exceeded with filter

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#805]
Directus v9-RC3 docker image with DB pointing on a mysql 5.7

Error calling : https://cms.millennium.ch/items/i18n_translations?filter[data.languages_code]=fr

response status 500
```
{
    "errors": [
        {
            "message": "Maximum call stack size exceeded",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```
------
I created a collection 'i18n' to gather all my app's translation keys
![image](https://user-images.githubusercontent.com/6372094/97579946-f9e13c80-19f2-11eb-9840-cf47896f3a5d.png)
and it's translation collection 'i18n_translations' for the field (M2M)
![image](https://user-images.githubusercontent.com/6372094/97580036-17160b00-19f3-11eb-85a5-c0aae7fdcd7d.png)

My objective is to return all the translations key that are in a given language (e.g. 'fr')
So if I query directly 'i18n_translations'
The usual response when not filtered:
```
{
    "data": [
        {
            "id": 1,
            "languages_code": "fr",
            "i18n_key": "test.test",
            "value": "Test 1"
        },
        {
            "id": 2,
            "languages_code": "en",
            "i18n_key": "test.test",
            "value": "Test 2"
        },
        {
            "id": 3,
            "languages_code": "fr",
            "i18n_key": "test1",
            "value": "Teste 1"
        },
        {
            "id": 4,
            "languages_code": "en",
            "i18n_key": "test1",
            "value": "Test one"
        },
        {
            "id": 5,
            "languages_code": "fr",
            "i18n_key": "42090635cf33c251c4970ba9bfbe0eb1aafe4c99",
            "value": "Aucune option pour vos paramètres"
        },
...
```

**Comment by rijkvanzanten** [comment]
This looks wrong:

`https://cms.millennium.ch/items/i18n_translations?filter[data.languages_code]=fr`

You shouldn't include `data` in the filter here, so it's:

`https://cms.millennium.ch/items/i18n_translations?filter[languages_code]=fr`

(issue still exists though)
