### ISSUE TITLE
RC-3: Translations auto generate no longer working

### ISSUE THREAD

**Issue by lluishi93** [directus/next#810]
1. Create a collection
2. Create translations field with auto-generate
3. Check that translations is no longer set-up correctly.

![image](https://user-images.githubusercontent.com/14786440/97597372-0d49d300-1a06-11eb-95da-e1f1e0d7bb1a.png)

Table gets created, but not linked to the item collection:

![image](https://user-images.githubusercontent.com/14786440/97597462-23f02a00-1a06-11eb-9b0e-184ea4f628b8.png)

![image](https://user-images.githubusercontent.com/14786440/97597537-379b9080-1a06-11eb-8631-14e71aa46317.png)

Also, once it is created, the user does not see the created translations table as it happened before, which is confusing

**Comment by lluishi93** [comment]
UPDATE: The languages_code field in the translations collection does NOT get created as a M2O field. Rather, it gets created as a String

**Comment by rijkvanzanten** [comment]
1. Create a collection
2. Create translations field with auto-generate
3. Check that translations is no longer set-up correctly.

Done, done, and done. Looks good on my end! 🤷 

![CleanShot 2020-10-29 at 16 49 09](https://user-images.githubusercontent.com/9141017/97630969-ad9ff780-1a06-11eb-89d6-84ed3c9f58c5.png)

![CleanShot 2020-10-29 at 16 49 18](https://user-images.githubusercontent.com/9141017/97630980-b1cc1500-1a06-11eb-833f-1557383abdb2.png)

What DB are you using @lluishi93?

**Comment by lluishi93** [comment]
Hi @rijkvanzanten , I'm using MySQL 5.7
IDK if I could provide you the full DB to take a look at it... Because this behavior is weird :S

**Comment by rijkvanzanten** [comment]
That's always helpful!

**Comment by rijkvanzanten** [comment]
I just tried this out on your DB dump; created a new table, added translations, used the auto-generated, and everything seems to be working as expected.. 

Lets reopen this if it keeps happening and we have specific steps to reproduce this
