### ISSUE TITLE
Collection Items cannot be edited with custom permissions

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/next#817]
I cannot edit Collection Items if I use custom rules. 

Following Item Permission is in use: (workes as intended on list view)
```
{
    "owner": {
        "_eq": "$CURRENT_USER"
    }
}
```

It doesn't matter which field permissions (all or nothing) I create, I cannot edit the Item.

---

### Project details
Directus Version: 9.0.0-rc.3
Environment: production
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.0.1

**Comment by rijkvanzanten** [comment]
When you say

> Following Item Permission is in use: (workes as intended on list view)

Is that for `read` or for all 4? 

> workes as intended on list view

Sounds to me like you've configured the `read` access, which would explain why:

> I cannot edit the Item.

**Comment by MichaelNussbaumerGOWEST** [comment]
I configured `read` and `edit`. The role shouldn't be able to `create` and/or `delete`.

But even if I give full access to `create` and `delete` I cannot add anything.

![Screenshot_26](https://user-images.githubusercontent.com/15796397/97727621-356b2c00-1b03-11eb-88fc-9a34d5a7221d.png)
![Screenshot_27](https://user-images.githubusercontent.com/15796397/97727628-369c5900-1b03-11eb-8223-9a7f4b753bae.png)

**Comment by MichaelNussbaumerGOWEST** [comment]
Maybe this is another usefull information:

![Screenshot_28](https://user-images.githubusercontent.com/15796397/97734563-e970b500-1b0b-11eb-97b1-d18a92d53c23.png)

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten for me it still doesn't work. All the fields are disabled when I try to `edit` an item. I am on rc.5 right now.

**Comment by rijkvanzanten** [comment]
@MichaelNussbaumerGOWEST Can you share a DB dump where this is happening?

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten have sent you on Discord yesterday :)

**Comment by kaYcee** [comment]
Any update on this? Tried with rc.6 but the fields are still read-only if edit permissions for a collection are changed from "All access" to selected fields. Regardless which of the fields is deselected - the result is that none of the collection's fields can be edited by the user for which the role permissions apply.

**Comment by MichaelNussbaumerGOWEST** [comment]
I am on rc.8 right now. The normal Inputs are working, but the `text area/wysiwyg fields` are now disabled. (with them enabled in custom permissions). 

Before the changes it was the opposit way, the `text area/wysiwyg fields` where enabled in any case and the normal inputs were disabled

**Comment by benhaynes** [comment]
Hey @MichaelNussbaumerGOWEST — we'll look into this today, but perhaps you can send some example permissions JSON or your database SQL?

**Comment by MichaelNussbaumerGOWEST** [comment]
@benhaynes  rijk has my dump from lust time (discord), there are basically no changes except the migrations so far.

**Comment by rijkvanzanten** [comment]
Lets track this as a separate issue

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten it seems the problem came back with rc14
