### ISSUE TITLE
Not able to delete 250 items at once from a collection

### ISSUE THREAD

**Issue by goggi** [directus/next#819]
Hi! 

I was fiddling around while deleting some date from a collection. And everything works great until I try to delete 250 items at once. 

![image](https://user-images.githubusercontent.com/1946339/97736995-b82cc080-1adc-11eb-9c81-11093728a035.png)

![image](https://user-images.githubusercontent.com/1946339/97737039-c67adc80-1adc-11eb-8d34-95a29eafbba2.png)

Hope you have a nice weekend! 

---

### Project details
Directus Version: 9.0.0-rc.3
Environment: production
OS: Linux 4.15.0-88-generic
Node: 14.7.0

**Comment by rijkvanzanten** [comment]
Ha, I guess the URL is getting too long at that point. The batch edit/delete currently works by adding the IDs in the URL: `DELETE /items/work_order_log/key1,key2,key3,key4`.

UUIDs have a length of 36, times 250 items is 9000 which is already wayyyyy over the limit https://stackoverflow.com/a/417184/4859211 😅
