### ISSUE TITLE
Ghost files

### ISSUE THREAD

**Issue by Nitwel** [directus/next#82]
I'm not sure how they got generated but they did exist in that DB at some point. Might be a bug.
![grafik](https://user-images.githubusercontent.com/22577866/89719277-efe90800-d9c6-11ea-9308-32579926c48d.png)

**Comment by rijkvanzanten** [comment]
Seeing you closed this, I guess you figured out what caused it @Nitwel?

**Comment by Nitwel** [comment]
That was me trying to test out the `/files` endpoint and not sending "real" files.
