### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by apstanisic** [directus/next#824]
Having Basic Auth would simplify developing apps or extensions using REST API because we wouldn't have to worry about refresh and access tokens in beginning. It would simplify usage with Postman.
I can create PR.

**Comment by MichaelNussbaumerGOWEST** [comment]
@apstanisic  You can simply set an access_token in the settings of an user: (rest of the info for auth you can find in the old API docs: https://docs.directus.io/api/authentication.html#tokens)

![Screenshot_29](https://user-images.githubusercontent.com/15796397/97770197-cb36a380-1b63-11eb-81bc-48434400ec9e.png)
