### ISSUE TITLE
Show preset in app as default value

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/next#825]
I wanted to make a preset for a owner field to set the user on creation. This didn't work, so I tried a simple input field preset and this wasn't working as well.

![Screenshot_30](https://user-images.githubusercontent.com/15796397/97771978-e3fb8500-1b74-11eb-9b24-f142ecfc8f38.png)
![Screenshot_31](https://user-images.githubusercontent.com/15796397/97771980-e52cb200-1b74-11eb-983f-2799edebba8c.png)

The background is, I want that files in the App can be seen/used only by the owner or if there are public files, they can be used by every user.

---

### Project details
Directus Version: 9.0.0-rc.4
Environment: production
OS: Linux 4.18.0-147.8.1.el8_1.x86_64
Node: 15.0.1

**Comment by rijkvanzanten** [comment]
Can you elaborate what didn't work exactly? I just setup a new role, added a new users, configured a preset for that role for on create, and everything seems to behave as expected 🤔

**Comment by MichaelNussbaumerGOWEST** [comment]
My understanding is, that if I configure the preset like I showed in my screenshots, the field title would be prefilled on creation of an new item with "xxxxxxxx".

**Comment by rijkvanzanten** [comment]
@MichaelNussbaumerGOWEST Can you share a DB dump where this is happening?

**Comment by MichaelNussbaumerGOWEST** [comment]
@rijkvanzanten have sent you on Discord yesterday :)

**Comment by rijkvanzanten** [comment]
Ohh you mean visible in the app? On save, it correctly fills that value in the API
