### ISSUE TITLE
Allow uploading files via link

### ISSUE THREAD

**Issue by Nitwel** [directus/next#83]
Would be usefull to upload files like this:

```
const res = await axios.post(`${api}/files?access_token=admin`, {
  "data": "https://via.placeholder.com/150/FFFF00/000000"
});
```

**Comment by rijkvanzanten** [comment]
It will most likely be a different endpoint though, in order to keep a little separation of concerns. I'm thinking a `/files/import` that takes in a URL.

**Comment by rijkvanzanten** [comment]
Added inhttps://github.com/directus/next/commit/6b0f314e0c2878d9d5b3dc13279f3800c0fde6c6
