### ISSUE TITLE
Collection created in postgres DB but not showing in UI

### ISSUE THREAD

**Issue by botzill** [directus/next#834]
Using version 9.0.0-rc4 I create a test collection using PG DB, I see tables created in DB but in UI I can't add new fields and in the console I see

```
chunk-vendors.ce045efa.js:14 TypeError: Cannot read property 'name' of undefined
    at a.Le (app.a147d66a.js:1)
    at chunk-vendors.ce045efa.js:116
    at be (chunk-vendors.ce045efa.js:116)
    at a.t.render (chunk-vendors.ce045efa.js:116)
    at a.e._render (chunk-vendors.ce045efa.js:14)
    at a.r (chunk-vendors.ce045efa.js:14)
    at nr.get (chunk-vendors.ce045efa.js:14)
    at nr.run (chunk-vendors.ce045efa.js:14)
    at Qn (chunk-vendors.ce045efa.js:14)
    at Array.<anonymous> (chunk-vendors.ce045efa.js:14)
it @ chunk-vendors.ce045efa.js:14
rt @ chunk-vendors.ce045efa.js:14
tt @ chunk-vendors.ce045efa.js:14
e._render @ chunk-vendors.ce045efa.js:14
r @ chunk-vendors.ce045efa.js:14
nr.get @ chunk-vendors.ce045efa.js:14
nr.run @ chunk-vendors.ce045efa.js:14
Qn @ chunk-vendors.ce045efa.js:14
(anonymous) @ chunk-vendors.ce045efa.js:14
lt @ chunk-vendors.ce045efa.js:14
Promise.then (async)
ot @ chunk-vendors.ce045efa.js:14
mt @ chunk-vendors.ce045efa.js:14
e.$nextTick @ chunk-vendors.ce045efa.js:14
r @ chunk-vendors.ce045efa.js:116
Ke @ chunk-vendors.ce045efa.js:116
(anonymous) @ chunk-vendors.ce045efa.js:116
nr.run @ chunk-vendors.ce045efa.js:14
Qn @ chunk-vendors.ce045efa.js:14
(anonymous) @ chunk-vendors.ce045efa.js:14
lt @ chunk-vendors.ce045efa.js:14
Promise.then (async)
ot @ chunk-vendors.ce045efa.js:14
mt @ chunk-vendors.ce045efa.js:14
er @ chunk-vendors.ce045efa.js:14
nr.update @ chunk-vendors.ce045efa.js:14
ge.notify @ chunk-vendors.ce045efa.js:14
set @ chunk-vendors.ce045efa.js:14
set @ chunk-vendors.ce045efa.js:116
endRequest @ app.a147d66a.js:1
E.S.<computed> @ chunk-vendors.ce045efa.js:102
u @ app.a147d66a.js:1
Promise.then (async)
c.request @ chunk-vendors.ce045efa.js:1
r.forEach.c.<computed> @ chunk-vendors.ce045efa.js:1
(anonymous) @ chunk-vendors.ce045efa.js:8
hydrate @ app.a147d66a.js:1
E.S.<computed> @ chunk-vendors.ce045efa.js:102
k @ app.a147d66a.js:1
async function (async)
k @ app.a147d66a.js:1
nt @ chunk-vendors.ce045efa.js:14
n @ chunk-vendors.ce045efa.js:14
nt @ chunk-vendors.ce045efa.js:14
Nn.e.$emit @ chunk-vendors.ce045efa.js:14
(anonymous) @ chunk-vendors.ce045efa.js:116
c @ app.a147d66a.js:1
nt @ chunk-vendors.ce045efa.js:14
n @ chunk-vendors.ce045efa.js:14
Zi.o._wrapper @ chunk-vendors.ce045efa.js:14
```

**Comment by danieljwestman** [comment]
Using other than the public schema as search path?

**Comment by botzill** [comment]
I use public schema in PG for this.

**Comment by rijkvanzanten** [comment]
@botzill Can you elaborate on the steps to reproduce this?

I just created a new table directly in the DB, went into the app, and am not seeing what you're talking about

**Comment by botzill** [comment]
I created the collection via UI. I see it in DB, but not in UI. In
collections i see empty.

**Comment by botzill** [comment]
I still get the issue after `rc5` upgrade:

![Kapture 2020-11-03 at 12 17 02](https://user-images.githubusercontent.com/4686040/97973259-7ea2d080-1dce-11eb-9932-82a5c22dccb9.gif)

and I get an error in the console when I create a new field. 

<img width="1035" alt="Screen Shot 2020-11-03 at 12 20 49 1" src="https://user-images.githubusercontent.com/4686040/97973557-ee18c000-1dce-11eb-8bbe-8e5664965bf8.png">

**Comment by rijkvanzanten** [comment]
@botzill Does it store the record in `directus_collections` correctly? Is this is in a fresh installation? Could you share a DB dump where this is happening?

**Comment by botzill** [comment]
Hi @rijkvanzanten 

yes it does store data in `directus_collections`

<img width="1244" alt="Screen Shot 2020-11-04 at 09 14 37" src="https://user-images.githubusercontent.com/4686040/98080533-3e029000-1e7e-11eb-87f4-1d4b147e3c80.png">

And yes it's a fresh install, PG is on DigitalOcean managed DB.

I did a dump of DB here(modified only some sensitive info)


[directus_next_db_dump.sql.zip](https://github.com/directus/next/files/5486121/directus_next_db_dump.sql.zip)

**Comment by rijkvanzanten** [comment]
> p.s.s: Not sure why I see this in dev tools console for the /collections end point?

Interesting! I think you found the cause of the issue here. How are you hosting Directus? For whatever reason, it looks like it's serving the app under the `/collections` endpoint??

**Comment by botzill** [comment]
I host this on kubernetes with standard ingress endpoint with path `/`

<img width="761" alt="Screen Shot 2020-11-04 at 17 26 59" src="https://user-images.githubusercontent.com/4686040/98130614-20a3e500-1ec3-11eb-8c8f-275ce944552f.png">

Not sure why it does serve it on that url

**Comment by rijkvanzanten** [comment]
@WoLfulus any insights on why/when/how kubernetes does that routing?

**Comment by botzill** [comment]
I see 2 requests made, one is:
`/admin/collections`

and the second is `/collections` which return empty

<img width="1000" alt="Screen Shot 2020-11-05 at 00 34 09" src="https://user-images.githubusercontent.com/4686040/98175170-bc067b80-1efe-11eb-8612-4c6d6e3ba24d.png">

**Comment by botzill** [comment]
note that I set the env

```
PUBLIC_URL
https://mydomain.com
```

is that OK?

**Comment by rijkvanzanten** [comment]
If you go to `https://mydomain.com/collections` manually, does the collection show up?

**Comment by botzill** [comment]
No.

<img width="215" alt="Screen Shot 2020-11-05 at 00 45 36" src="https://user-images.githubusercontent.com/4686040/98175952-3daad900-1f00-11eb-9bd2-164bb6fcc3bf.png">

**Comment by rijkvanzanten** [comment]
Could it be that your server setup strips out the Authorization header by chance?

**Comment by botzill** [comment]
then why other endpoints works, like files or users? I mean I can see files isn't that loaded as well via API?

**Comment by botzill** [comment]
a request like

```
/users?limit=25&fields[]=id&fields[]=avatar.modified_on&fields[]=avatar.type&fields[]=avatar.filename_disk&fields[]=avatar.storage&fields[]=avatar.id&fields[]=first_name&fields[]=last_name&fields[]=email&sort=id&page=1&filter=%7B%7D
```

I see works when I got to users section.

**Comment by rijkvanzanten** [comment]
🤷 no idea, just thinking aloud here

**Comment by rijkvanzanten** [comment]
Would I be able to access this instance? Very curious to see what's going on

**Comment by botzill** [comment]
Sure, I just did @ you, we can connect and show you.

**Comment by rijkvanzanten** [comment]
This turned out to be a configuration problem in the K8s stack, unrelated to Directus (pfew)
