### ISSUE TITLE
Issue with public url not ending in /

### ISSUE THREAD

**Issue by botzill** [directus/next#836]
Currently, if the public URL does not end in `/` then I get an error when I access the page:

<img width="232" alt="Screen Shot 2020-11-02 at 11 00 01" src="https://user-images.githubusercontent.com/4686040/97848866-63669100-1cfa-11eb-80b3-65ba469372e5.png">

and it tries to access:

```
Request URL: https://mydomian.comadmin/css/app.c8867b04.css
```

If I set the ending `/` then when I get the email invite link, it contains 2 slashes:

```
You have been invited to Directus. Please click the link below to join:https://mydomain.com//admin/accept-invite?
--
```

which is not a valid path.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/next/pull/827
