### ISSUE TITLE
Display template for translations not applied

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#838]
v9.00-rc4

I've set the translations for my collection 
![image](https://user-images.githubusercontent.com/6372094/97873965-a0418080-1d18-11eb-8fa4-4cf48b26582a.png)

and configured for the _languages_ collection the display template to use the field _name_
![image](https://user-images.githubusercontent.com/6372094/97874029-b6e7d780-1d18-11eb-91b1-e7c3171a5ad9.png)

but then, when editing a collection, it still shows the _code_
![image](https://user-images.githubusercontent.com/6372094/97874152-dd0d7780-1d18-11eb-9583-53fee4b8bdd9.png)

Note that the same configuration does work as expected in v9.00-beta.10

**Comment by flayks** [comment]
I tried to use Name as a value for the Display Templates for my languages as well, but it seems that the data is not retrieved anymore:

![image](https://user-images.githubusercontent.com/273716/97965868-4ba31180-1dbb-11eb-8a18-a430274b2b82.png)

Same data (unchanged) but without the Display Template:

![image](https://user-images.githubusercontent.com/273716/97965937-670e1c80-1dbb-11eb-8c22-1f8d168e2aac.png)
