### ISSUE TITLE
Duplicated titles in the collection setup page

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#839]
v9.0.0-rc4
![2020-11-02_14-51-32 (1)](https://user-images.githubusercontent.com/6372094/97875731-2232a900-1d1b-11eb-96d7-a3abb32436e1.gif)

**Comment by rijkvanzanten** [comment]
Make sure to run `npx directus database migrate:latest` after updating your Directus version 🙂

**Comment by jojomillennium** [comment]
Thanks! 👍
