### ISSUE TITLE
Endpoint "fields/{collection}" not working right.

### ISSUE THREAD

**Issue by Nitwel** [directus/next#84]
It returns fields of other collections too.
![grafik](https://user-images.githubusercontent.com/22577866/89720426-4a3b9600-d9d2-11ea-8f86-28e08d141274.png)

**Comment by rijkvanzanten** [comment]
I believe this was already fixed in https://github.com/directus/next/commit/9fb4d0e8eb2cabee624189cc30486c08bb51dbf6. Can you confirm you're on the latest version and that this still persists @Nitwel?
