### ISSUE TITLE
No permissions to update items with role with update permissions

### ISSUE THREAD

**Issue by maartenvn** [directus/next#840]
### Environment

- **Directus**: 9.0.0-rc.4
- **Postgres**: 13

### Bug
Roles with the "Update" permission set to allow get an error 403 when updating an item.

### Stacktrace
```json
{
	"errors": [
		{
			"message": "You're not allowed to update item \"3\" in collection \"article\".",
			"extensions": {
				"collection": "article",
				"item": [
					"3"
				],
				"action": "update",
				"code": "FORBIDDEN"
			}
		}
	]
}```

**Comment by rijkvanzanten** [comment]
I think this is cause by the same thing as https://github.com/directus/next/issues/817
