### ISSUE TITLE
O2M doesn't display related items in edit table

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#841]
- Added a M2O relationship `operacoes.carteira_id` <- `carteiras.id` to `operacoes` table
- Checked to add the inverse O2M relationship automatically
- Into the `interface` on the generated M2O relationship, added some interface fields

![image](https://user-images.githubusercontent.com/412397/97878774-d58ca500-1cfd-11eb-9c20-9256af1b8d8f.png)

Fields doesn't show up even though they are registered

![image](https://user-images.githubusercontent.com/412397/97878858-ef2dec80-1cfd-11eb-8ac4-d306690443f7.png)

Same happens for `Ticker` which is another relationship to another table

**Comment by rijkvanzanten** [comment]
Could you elaborate on the relationship in use here? It kinda sounds like you're trying to read `name` from within the `m2o` field that points back to the parent `o2m`, so effectively you're trying to read `nome` from the current `o2m` parent item??
