### ISSUE TITLE
Initial role creation not working on postgresql

### ISSUE THREAD

**Issue by MiniDigger** [directus/next#842]
Running directus v9 rc4 in docker, its able to properly create the database tables and seed them, but it fails upon trying to create the administrator role:

```
11:16:04 ✨ Database installed
11:16:05 ✨ Creating administrator role
(node:458) UnhandledPromiseRejectionWarning: error: insert into "directus_roles" ("id") values ($1) - null value in column "name" violates not-null constraint
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:458) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode ). (rejection id: 2)
(node:458) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I first thought there was an additional issue in the schema inspector or that my user doesn't have permission to read certain stuff from the db, but I executed a bunch of queries, including 
```sql
select information_schema.key_column_usage.column_name from information_schema.key_column_usage
left join information_schema.table_constraints on information_schema.table_constraints.constraint_name = information_schema.key_column_usage.constraint_name
where information_schema.table_constraints.constraint_type = 'PRIMARY KEY'
and information_schema.table_constraints.table_name = 'directus_roles'
```
which was the issue in https://github.com/knex/knex-schema-inspector/issues/23, but the all returned what I would expect (which is strange since now I don't see how I ran in that issue if the query on the DB with the same user returns something...)

I don't know how to continue debugging this.

**Comment by rijkvanzanten** [comment]
@WoLfulus How are you running the CLI command? Sounds like the arguments aren't passed to the CLI 🤔

**Comment by MiniDigger** [comment]
even running the command manually doesn't fix it (we been thru this last week where you also suggested me to try --, the cli would catch missing arguments)

**Comment by rijkvanzanten** [comment]
Yeah, I'm just trying to figure out what specifically causes that to happen in Docker 🤔 

With directus installed globally, or by using the local one with `npx` I'm not seeing issues in the CLI by running it directly under unix/macos based systems

**Comment by MiniDigger** [comment]
This is caused by the schema not being passed into `knex-schema-inspector`.
as a test I added this line here: https://github.com/directus/next/blob/main/api/src/services/items.ts#L44
`this.schemaInspector.withSchema("directus");` and my issue is gone.

**Comment by MiniDigger** [comment]
sadly was not fixed in rc5 because of https://github.com/knex/knex-schema-inspector/pull/25 :/
