### ISSUE TITLE
[Suggestion] "Close" button UX in modals

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#843]
When creating inline relationship items or doing any modal actions, at first I kept hitting "close" button instead of the "checkmark" one and having no clue why the value wouldn't land - Figured out that I had to click the "checkmark" to apply the selection/create the item, but even knowing about that I kept hitting close from time to time - felt kinda counter intuitive

Maybe moving the "close" button to the side of the "checkmark" one?

To illustrate: 

![izRAazNSMF](https://user-images.githubusercontent.com/412397/97879419-b6dade00-1cfe-11eb-81d6-99808abe28c0.gif)

**Comment by rijkvanzanten** [comment]
The fact that it shows unstaged selections after closing and reopening is a bug

**Comment by benhaynes** [comment]
I totally see what you're saying, but I think this UX still makes the most sense. This keeps the edit page the exact same as in the parent (no injected "x" button), and clearly shows the "x" as part of the overlay (in case we had a custom form/layout in the modal that didn't have a slot for it).

What I think we should do is be consistent by also having the "are you sure?" confirmation when you try to exit with staged changes. So...

* If you exit with no changes (eg: _just looking_), then the "X" will just close the modal
* If you exit with staged changes (eg: a selection, or form edit), then you'll get a notification. And we can make this smarter by offering a way to save in the notification... so it would have the following text/options:
    * `This window has unsaved changes, how would you like to proceed?`
    * `Discard Changes` (button, default)
    * `Save Changes` (button) Not sure if we need this, but nice to have
    * `Cancel` Stays on the modal

Thoughts @WoLfulus ?
