### ISSUE TITLE
Can't seem to be able to save updates

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#846]
v9.0.0-rc4
I can't seem to be able to change the status and save.
The save button stays disabled, but if I leave the page, I get a warning that I have unsaved changes.

![2020-11-02_14-54-33 (1)](https://user-images.githubusercontent.com/6372094/97881747-13e88b00-1d23-11eb-9566-ff50ceae5ebd.gif)

**Comment by benhaynes** [comment]
Thanks for reporting this! It seems specific to that interface/type not staging the value to the parent form (or something like that). We're on it!

**Comment by rijkvanzanten** [comment]
@jojomillennium If possible, can you share a DB dump where this happens? We're not able to reproduce this with the info provided

**Comment by jojomillennium** [comment]
@rijkvanzanten Here you go!
[dump.sql.zip](https://github.com/directus/next/files/5480020/dump.sql.zip)

**Comment by jojomillennium** [comment]
Further tests make any fields not trigger the enablement of the save button (status, text field, image, ...)

**Comment by mscbpi** [comment]
same here with clean install / deployment (docker).

**Comment by mscbpi** [comment]
same here with clean install
