### ISSUE TITLE
Sort files/images by manual order

### ISSUE THREAD

**Issue by flayks** [directus/next#849]
That would be great to be able to sort multiple files and images by a manual order and not only by title, similar to what the v8 proposed with a `sort` field on the relational collection.

![image](https://user-images.githubusercontent.com/273716/97889068-316e2280-1d2c-11eb-822b-15ffe3c29cbc.png)

**Comment by rijkvanzanten** [comment]
We already have support for this in the regular m2m, so it should be fairly easy to copy paste that logic over

**Comment by benhaynes** [comment]
Didn't https://github.com/directus/next/issues/360 kinda solve that? Or was that for a different field type?

**Comment by rijkvanzanten** [comment]
That's m2m/o2m, not multiple files

**Comment by flayks** [comment]
Okay, so I tried to add a manual sort, with a `sort` field (integer) in my `projects_directus_files`

![image](https://user-images.githubusercontent.com/273716/97968042-675be700-1dbe-11eb-8bcd-e4bdf3a62f43.png)

The manual order can now be triggered

![image](https://user-images.githubusercontent.com/273716/97968082-76429980-1dbe-11eb-94fe-bef3d872b865.png)

But when saving, I get an error

![image](https://user-images.githubusercontent.com/273716/97968129-83f81f00-1dbe-11eb-8c48-21b61b237658.png)

```
10:17:09 ✨ request completed GET 200 /items/projects_directus_files?fields[]=id&fields[]=directus_files_id&fields[]=sort&filter[id][_in]=27,24,25,26,28,29,30 48ms
10:17:09 ✨ request completed GET 200 /files?fields[]=id&fields[]=type&fields[]=title&filter[id][_in]=0afecf95-0167-4f6b-bbd4-c0e8aa792473,2e1b6f6b-bc16-420a-8ec2-fdb6bdf77bec,68519f92-2477-4a15-a67e-f913c4aa79e5,73e52ace-dc9f-4300-b690-1fd6cbb16c53,a083a7be-e986-4cd2-b76b-ecea03754b55,ab89f308-40d4-43f1-ba9b-0697e96319bf,f9e7ecd5-a01e-4cb5-b136-04fa0fbe4332,73e52ace-dc9f-4300-b690-1fd6cbb16c53,0afecf95-0167-4f6b-bbd4-c0e8aa792473,2e1b6f6b-bc16-420a-8ec2-fdb6bdf77bec,68519f92-2477-4a15-a67e-f913c4aa79e5,a083a7be-e986-4cd2-b76b-ecea03754b55,ab89f308-40d4-43f1-ba9b-0697e96319bf,f9e7ecd5-a01e-4cb5-b136-04fa0fbe4332 49ms
10:17:10 ✨ request completed PATCH 400 /items/projects/3 297ms
```

Am I missing a step or something else?

**Comment by rijkvanzanten** [comment]
What's the API response for that 400 request?

**Comment by flayks** [comment]
@rijkvanzanten not quite sure, how can I check? I got these from the terminal when saving the post

**Comment by rijkvanzanten** [comment]
The browser devtools should show the response under the `network` tab 🙂

**Comment by flayks** [comment]
I believe that's the response:

```
{"errors":[{"message":"\"storage\" is required","extensions":{"field":"storage","type":"required","code":"FAILED_VALIDATION"}},{"message":"\"filename_download\" is required","extensions":{"field":"filename_download","type":"required","code":"FAILED_VALIDATION"}}]}
```

**Comment by rijkvanzanten** [comment]
Is this when sorting existing items, or when selecting new items and then sorting?

**Comment by flayks** [comment]
In the latest attempt, it was to sort existing items.

**Comment by rijkvanzanten** [comment]
@flayks What DB is this under? Would you be able to provide a dump where this is happening?

**Comment by flayks** [comment]
It's with a MySQL database
Here is a dump: [cetrucflotte.sql.zip](https://github.com/directus/next/files/5484400/cetrucflotte.sql.zip)
