### ISSUE TITLE
Can't generate a cropped thumbnail from URL

### ISSUE THREAD

**Issue by flayks** [directus/next#853]
When accessing the `/assets/UID` using the `fit=crop` option like that:

`http://localhost:8055/assets/f3a557d4-546f-4304-8664-c9ac02f38515?fit=crop&width=1500&height=1000&quality=80`

I get this error:

```
{"errors":[{"message":"Expected valid fit for fit but received crop of type string","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

**Comment by flayks** [comment]
Oh, I figured from the Storage and Assets Presets that the `crop` option has been renamed to `cover`. Is that the reason? It seems to work with this URL then:
`http://localhost:8055/assets/f3a557d4-546f-4304-8664-c9ac02f38515?fit=cover&width=1500&height=1000&quality=80`

**Comment by rijkvanzanten** [comment]
Yep, it's `cover`
