### ISSUE TITLE
Setup relation for "user created" / "user modified" on collection creation

### ISSUE THREAD

**Issue by kaYcee** [directus/next#855]
When I show the user who created or updated a record in a collection view, only the uid is shown and not the name. Can this be configured somehow?

**Comment by rijkvanzanten** [comment]
Yes, you can add a display for this field and use either "related values" or "user"

**Comment by kaYcee** [comment]
Hi @rijkvanzanten thx for your reply! I can select the following Display options for the standard `user_created` or `user_updated` fields in RC5:
**Raw Value, Formatted Value, Collection, Color, Icon, Labels, MIME Type**

Do I have to enable 'Related Values' somewhere?


But nowhere could I find either of your proposed options.

**Comment by rijkvanzanten** [comment]
Could be that the app creates them as regular text fields instead of a relational field to users!
