### ISSUE TITLE
Cant opt out of creating new collection.

### ISSUE THREAD

**Issue by Nitwel** [directus/next#87]
You cant close that popup.
![grafik](https://user-images.githubusercontent.com/22577866/89736409-7bb37080-da69-11ea-8605-90b0e0813188.png)

**Comment by benhaynes** [comment]
Haha, hilarious...

**Comment by Nitwel** [comment]
You better create that collection now! 🔪

**Comment by rijkvanzanten** [comment]
That cancel button in the bottom left works 😉

**Comment by Nitwel** [comment]
Ohhhh, theres a button. Haha. 🤣

**Comment by rijkvanzanten** [comment]
It was the wrong color though (see https://github.com/directus/next/issues/46), but that was subsequently fixed. Can you make sure you're looking at the latest version @Nitwel ?
