### ISSUE TITLE
Visible json object in collections when user preference language is not english

### ISSUE THREAD

**Issue by TheAzack9** [directus/next#873]
### Project details
Directus Version: 9.0.0-rc.6
Environment: production
OS: Linux 4.15.0-112-generic
Node: 14.15.0
			

When i changed the language preference on my user i noticed a json object appearing on all collections. See image for reference :) 

![image](https://user-images.githubusercontent.com/2140448/98071193-2f5aaf80-1e63-11eb-99ff-9b076d64da9f.png)

![image](https://user-images.githubusercontent.com/2140448/98071164-194cef00-1e63-11eb-9a5c-1da27153c554.png)

**Comment by rijkvanzanten** [comment]
Translations haven't been updated yet.. See #230. Incidentally, @maartenvn made a manual patch to the Dutch translations for this exact thing: https://github.com/directus/next/pull/848
