### ISSUE TITLE
Note in collection overview seems clamped

### ISSUE THREAD

**Issue by TheAzack9** [directus/next#874]
### Project details
Directus Version: 9.0.0-rc.6
Environment: production
OS: Linux 4.15.0-112-generic
Node: 14.15.0
			
Note: Might not be a bug, but a misunderstanding on my part :) Just thought i should create an issue just in case!

The collection overview seems to clamp the note column. See image for example.

The text in the news sections is supposed to say "Nyheter som vises på nettsiden.", but is clamped significally.

![image](https://user-images.githubusercontent.com/2140448/98072238-de988600-1e65-11eb-83de-8aaf26a667df.png)

**Comment by benhaynes** [comment]
It's a bug, we'll need to update the default column widths to handle normal/longer length notes.
