### ISSUE TITLE
What is the format of the new custom roles access

### ISSUE THREAD

**Issue by botzill** [directus/next#883]
Prev in Directus we had:

<img width="189" alt="Screen Shot 2020-11-05 at 12 29 33" src="https://user-images.githubusercontent.com/4686040/98229442-94e19580-1f62-11eb-9756-1d0855733d0e.png">

What is the equivalent in Directus Next, I see this:

<img width="611" alt="Screen Shot 2020-11-05 at 12 30 10" src="https://user-images.githubusercontent.com/4686040/98229502-a88cfc00-1f62-11eb-9536-83094b57c866.png">

What is the format of this data?

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/next/blob/main/docs/reference/filter-rules.md#filter-rules
