### ISSUE TITLE
API call error

### ISSUE THREAD

**Issue by botzill** [directus/next#884]
I have an error while I call the API to get all the items:

```
....from "my_table" where "" = $1 limit $2 - zero-length delimited identifier at or near """"
```

My Filters look like `?limit=10000&filter%5Bstatus%5D%5Beq%5D=published`,

Is there anything changed related to this?

**Comment by botzill** [comment]
I see, now we need to use underscore in comparators like `_eq`.

**Comment by benhaynes** [comment]
The v9 dynamic API Reference is in the works, which will make all this much easier to figure out.
