### ISSUE TITLE
Unauthenticated users can access the files uploaded on Directus

### ISSUE THREAD

**Issue by metalmarco** [directus/next#887]
• Version of Directus: 9.0.0 RC6
• MacOSX Catalina - MariaDB 10.4.13
• Steps to Reproduce:

- Clean Installation of Directus 9
- Login as Admin and upload a file
- Make sure Public role has no permission on any custom or system collection  

- Open a different browser in which the user is unauthenticated and paste the URL to access the file https://{{directus}}/assets/{{filename}}
- The file can be viewed/downloaded

The ideal solution for me would be to have a private S3 bucket as storage, not publicly accessible.
Directus should check the user permission when requesting an assets/{{filename}}. 
The permission could be managed on a folder level, so it could be possible to have Public Folders and Private Folders.
Maybe the token should be sent as query parameter?

**Comment by rijkvanzanten** [comment]
`/assets` should use the same permissions as `/files`. That'll also allow you to set different access levels for different roles, set access permissions based on the value of any field on the file (like the folder) etc.

**Comment by metalmarco** [comment]
I just tested the issue on version 9.0.0-rc.13 and the problem is still present.
The tests have been performed with an authenticated browser, and all the permissions set to DENY for the Public user.

If I include the access_token Directus behaves correctly:
`http://localhost:8055/assets/3b22bbbd-1574-4dcd-9647-1472f425ac45?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyNDZhOTI3LTVhYmYtNGRjZC1iYjc3LWYxYTc5NGNiMzg1MyIsImlhdCI6MTYwNTE5NjI3MiwiZXhwIjoxNjA1MTk3MTcyfQ.8n0voMxiIt61iiLrbZbiUUIspdLsWpum0_jLtqqxJ3Y`

- The image is downloaded as long as the token is valid
- The image is not downloaded if the token is expired


However, if I access the image without passing the access_token like this:
`http://localhost:8055/assets/3b22bbbd-1574-4dcd-9647-1472f425ac45`

- The image is ALWAYS downloaded, and this should not happen for a public user

**Comment by rijkvanzanten** [comment]
Is that file used on the public pages as configured in project settings?

**Comment by metalmarco** [comment]
> Is that file used on the public pages as configured in project settings?

Hi @rijkvanzanten.
The file is not used in the project settings. It has just been uploaded in the Files Library by the Admin user.

The "Directus Files" permission is all DENY for the Public user, so I guess it should not be possible for an unauthenticated user to access it at http://localhost:8055/assets/3b22bbbd-1574-4dcd-9647-1472f425ac45

**Comment by rijkvanzanten** [comment]
Can you share a DB dump where this is happening? I can't reproduce it on my end

**Comment by metalmarco** [comment]
Here it is.
[directus9_2020-11-13.sql.zip](https://github.com/directus/next/files/5538204/directus9_2020-11-13.sql.zip)
