### ISSUE TITLE
Error when a field is not permitted in nested fields

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#890]
Direct v9.0.0-rc6

When querying with * . * is works fine, but when querying with * . * . *  there is an error of missing permission for a specific field, which I can't find where it is from.
I would expect, in the nested fields, if one is not accessible, to either not show the field missing the permission, or put its value to null, or specifically have its value "no permission to access", but still show all the rest that is allowed.
This way at least we'd see where in the tree (and collection) the missing permission is located.

![image](https://user-images.githubusercontent.com/6372094/98251719-5c998180-1f79-11eb-8e75-aaba5844566d.png)

**Comment by rijkvanzanten** [comment]
fwiw `uploaded_by` is most likely in `directus_files`

**Comment by jojomillennium** [comment]
I assumed the same, but what is weird is that I have _all access_ for read on `directus_files`
![image](https://user-images.githubusercontent.com/6372094/98263998-be60e800-1f87-11eb-8b21-f580a262ef8b.png)

**Comment by rijkvanzanten** [comment]
@jojomillennium If possible, could you share a DB dump with this setup so I can reproduce it exactly?

**Comment by jojomillennium** [comment]
Sure, here it is
[dump-cms-05-11.sql.tar.gz](https://github.com/directus/next/files/5495514/dump-cms-05-11.sql.tar.gz)

**Comment by rijkvanzanten** [comment]
@jojomillennium I just tried this on your DB dump in RC7, and everything seems to be working:

![CleanShot 2020-11-05 at 16 05 42](https://user-images.githubusercontent.com/9141017/98296329-c406ff80-1f80-11eb-9703-a9b9d1bdff17.png)

Could you give it a shot in RC7 and let me know if the problem still occurs on your end?

**Comment by jojomillennium** [comment]
tested on RC8 and problem has gone, thanks!
Nevertheless, there is another issue:
level 2 (* . *) are not retrieved when querying level 3 ( * . * . *)
You can test with the same dump with the two queries below:
https://sandboxcms.millennium.ch/items/amenities?fields=*.*&filter[code]=la_brasserie
https://sandboxcms.millennium.ch/items/amenities?fields=*.*.*&filter[code]=la_brasserie

You will see in the first one, the `business_hours` is expanded, but with the second one, it is `null`.

I would expect * . * . * to retrieve all levels ( 1 + 2 + 3).
Let me know if you prefer a new bug ticket.

**Comment by rijkvanzanten** [comment]
Yeah i'll move it to a new issue 👍
