### ISSUE TITLE
Don't allow archiving if permission not set

### ISSUE THREAD

**Issue by kaYcee** [directus/next#900]
Thanks for fixing edit permissions in rc.8! I spotted a glitch, though. The `Archive` button is still visible, although editing of the `status` field has been disabled. If a user clicks on `Archive` now, she receives a _Forbidden_ warning now:

`You are now allowed to update field "status" in collection "..."`

As it is unexpected to have the archiving option at all while edit permissions are set to a minimum, I would suggest having either an additional column in the permissions table to allow/disallow archiving or adding _Archiving_ to the edit permissions field list as a checkbox. 

Any other suggestions or what's the community's take on this?

**Comment by benhaynes** [comment]
I'd rather avoid a dedicated permission for this, it should be doable by simply looking at the current permissions for the archive field. Right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Yeah absolutely, the archive button is nothing more than a "shortcut" to update the value for that field to a pre-configured value
