### ISSUE TITLE
Error when we access a user without role

### ISSUE THREAD

**Issue by botzill** [directus/next#901]
version: `9.0-rc8`

When I create a user without a 
<img width="755" alt="Screen Shot 2020-11-06 at 10 40 29" src="https://user-images.githubusercontent.com/4686040/98344974-b010db80-201c-11eb-89f4-1e9ee7bc0f83.png">
role and access the details page I get the error:

**Comment by benhaynes** [comment]
Users who are not assigned to a role (which is allowed) inherit the "public" role's access. I assume this is just a small uncaught issue with the NULL role... not sure if if should say `Public`, `None`, or something else though.
