### ISSUE TITLE
GraphQL Error while using variables

### ISSUE THREAD

**Issue by Clex1o1** [directus/next#903]
version directus 9 rc8.

I receive this message when I fetch data with variables through the graphql explorer or vue-apollo:
`"message": "Undefined binding(s) detected when compiling WHERE. Undefined column(s): [news.id] query: where 'news'.'id' = ?",`

My query looks like this:
```
query news($id: ID) {
  items {
    news(filter: {id: {_eq: $id}}) {
      headline
    }
  }
}
```

If i using my query like this, without variables it works:
```
query news {
  items {
    news(filter: {id: {_eq: 1}}) {
      headline
    }
  }
}
```

**Comment by benhaynes** [comment]
I defer to @rijkvanzanten and @WoLfulus on this one being a bug or new feature... I'm not super familiar with our GraphQL implementation as of now.

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-11-10 at 13 19 49](https://user-images.githubusercontent.com/9141017/98714877-6ba47900-2357-11eb-87f5-b8f8822e79ac.png)

now works as expected 🙂
