### ISSUE TITLE
Redis doesn't connect in RC8

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#911]
When trying to run Directus rc8 with CACHE_ENABLED pointed to a Redis instance, it seems that it tries to connect to a local instance, and not the one configured in CACHE_REDIS url.

**Comment by rijkvanzanten** [comment]
This seems to be a configuration option in the deployment, as connecting to Redis from another source seems to work as expected

**Comment by flayks** [comment]
@rijkvanzanten Would you have an example of Docker config? I run into the same issue, can't really connect a Redis instance to Directus.

**Comment by rijkvanzanten** [comment]
Not in Docker, but I configured the env vars to:

```
CACHE_ENABLED=true
CACHE_TTL=30m
CACHE_STORE=redis
CACHE_REDIS="redis://@127.0.0.1"
```

which did the trick for me 🤷
