### ISSUE TITLE
Issues while adding a new Presets & Bookmark

### ISSUE THREAD

**Issue by botzill** [directus/next#917]
When I click to add a new bookmark I get this error:

<img width="632" alt="Screen Shot 2020-11-07 at 18 12 30" src="https://user-images.githubusercontent.com/4686040/98446270-09fcc880-2125-11eb-9e71-6904e7c68340.png">

**Comment by rijkvanzanten** [comment]
@botzill I can't seem to reproduce this on my end in PG / MySQL. Do you have a DB dump available where this happens consistently?
