### ISSUE TITLE
Boolean field not showing custom on, off Labels

### ISSUE THREAD

**Issue by botzill** [directus/next#918]
I have a boolean field where I define:

<img width="645" alt="Screen Shot 2020-11-07 at 20 21 17" src="https://user-images.githubusercontent.com/4686040/98448723-ea6e9b80-2136-11eb-966c-7b01c8386488.png">

But I don't see the labels on change

<img width="866" alt="Screen Shot 2020-11-07 at 20 23 17" src="https://user-images.githubusercontent.com/4686040/98448736-1558ef80-2137-11eb-86f2-d9c2e776af1c.png">

**Comment by benhaynes** [comment]
Thanks! We'll look into this and get it fixed...

On a side note, it's driving me crazy that your colors are reversed! 😉

**Comment by botzill** [comment]
Thx.

Colors are OK, when it's started show button red to stop and when is stoped show color green to start.

**Comment by benhaynes** [comment]
Ahh, maybe the icons are backwards then? Haha, anyways, will look into it!

**Comment by rijkvanzanten** [comment]
@botzill I think you're confused between the display and the interface. The first screenshot is the setup for the `boolean` display, but your screenshot shows the `toggle` interface with no label

**Comment by botzill** [comment]
Well, I did remove the Interface setup and let only Display:

<img width="618" alt="Screen Shot 2020-11-11 at 01 27 56" src="https://user-images.githubusercontent.com/4686040/98745900-21ee7980-23bd-11eb-93d3-443560a5ff17.png">

But still,
<img width="871" alt="Screen Shot 2020-11-11 at 01 28 50" src="https://user-images.githubusercontent.com/4686040/98745940-3894d080-23bd-11eb-85f4-f577f346986c.png">
 I see the checkbox and no Label:

**Comment by benhaynes** [comment]
I think you got this backwards — what you're trying to set up is the interface.

That said, @rijkvanzanten — shouldn't this have `Enabled` next to it by default?
