### ISSUE TITLE
Cannot upload images and files to documents

### ISSUE THREAD

**Issue by adrianhajdin** [directus/next#925]
I'm having some trouble with the Directus App. I'm logged in as the admin user, I've created a collection that has a few text inputs and one file and one image input. When I try to create a new document and upload either the file or the image as the admin user, it doesn't let me upload. No errors are visible in the UI, but in the network tab I get: 
"You don't have permission to access this.", extensions: {code: "FORBIDDEN"}. I'm not sure why this is happening as I'm logged in as the Admin user. I'm using MySQL if that helps.

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/next/commit/555f977af790e0a19a6026c3f1ffa94a0cd12d1e. Could you try it again in RC.10+? 🙂
