### ISSUE TITLE
Not able to run dev - invalid properties (redirect & grant) in type Session

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#927]
Directus v9-rc.8
Latest commit 0bcc2c1d3cd8c55551f9b7a988ee1cb156dac6c6
PG 12
Clean and fresh install

Running `npm install` in root not possible.

The properties `redirect` and `grant` doesn't exist on `Session` type.

```
> rm -rf dist && tsc --build && copyfiles "src/**/*.*" -e "src/**/*.ts" -u 1 dist

src/controllers/auth.ts(243,16): error TS2339: Property 'redirect' does not exist on type 'Session | InitializedSession'.
  Property 'redirect' does not exist on type 'Session'.
src/controllers/auth.ts(256,33): error TS2339: Property 'redirect' does not exist on type 'Session | InitializedSession'.
  Property 'redirect' does not exist on type 'Session'.
src/controllers/auth.ts(271,17): error TS2339: Property 'grant' does not exist on type 'Session | InitializedSession'.
  Property 'grant' does not exist on type 'Session'.

lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! directus@9.0.0-rc.8 build: `rm -rf dist && tsc --build && copyfiles "src/**/*.*" -e "src/**/*.ts" -u 1 dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the directus@9.0.0-rc.8 build script.
```
![Skärmavbild 2020-11-10 kl  10 35 02](https://user-images.githubusercontent.com/20950568/98656226-bb2b7a80-2340-11eb-80b1-8fd6142a3d6a.png)

**Comment by rijkvanzanten** [comment]
Could you elaborate what you mean by "Clean and fresh install" ?

I just did a fresh clone of the repo, ran `npm install` and everything went through as expected. 

The `req.session` is typed as an `Express.Session`:

![CleanShot 2020-11-10 at 14 07 04](https://user-images.githubusercontent.com/9141017/98719681-0ef88c80-235e-11eb-9935-066404a3fd55.png)

Which itself<sup>(1)</sup> is typed to hold any `key: value` pair<sup>(2)</sup> no problem.

![CleanShot 2020-11-10 at 14 07 31](https://user-images.githubusercontent.com/9141017/98719719-1a4bb800-235e-11eb-8cda-919d6426827c.png)

Do you have any packages / types installed that aren't included in the repo by default that throw trouble? I searched for in the dependencies/code of Directus, but `InitializedSession` doesn't seem to exist 🤔

**Comment by danieljwestman** [comment]
Very strange, I can’t get it to work from here... No other packages or types installed...

**Comment by rijkvanzanten** [comment]
Very strange! The only other explanation I have is that you somehow ended up with a different version of `@types/express` or `@types/express-session`, or maybe a different version of Node is causing issues..?

I'm testing this under Node v14.15.0 with `@types/express@4.17.8` and `@types/express-session@1.17.0`. Could you confirm the versions on your end?

**Comment by danieljwestman** [comment]
@rijkvanzanten I've downloaded a new clean source code and run npm install in root. 

Still:

```
> directus@9.0.0-rc.12 build /Users/danielwestman/directus/api
> rm -rf dist && tsc --build && copyfiles "src/**/*.*" -e "src/**/*.ts" -u 1 dist

src/controllers/auth.ts(243,16): error TS2339: Property 'redirect' does not exist on type 'Session | InitializedSession'.
  Property 'redirect' does not exist on type 'Session'.
src/controllers/auth.ts(256,33): error TS2339: Property 'redirect' does not exist on type 'Session | InitializedSession'.
  Property 'redirect' does not exist on type 'Session'.
src/controllers/auth.ts(271,17): error TS2339: Property 'grant' does not exist on type 'Session | InitializedSession'.
  Property 'grant' does not exist on type 'Session'.

lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! directus@9.0.0-rc.12 build: `rm -rf dist && tsc --build && copyfiles "src/**/*.*" -e "src/**/*.ts" -u 1 dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the directus@9.0.0-rc.12 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielwestman/.npm/_logs/2020-11-11T13_43_23_785Z-debug.log

lerna ERR! npm run build exited 1 in 'directus'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! directus-monorepo@ build: `lerna run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the directus-monorepo@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielwestman/.npm/_logs/2020-11-11T13_43_23_834Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! directus-monorepo@ postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the directus-monorepo@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielwestman/.npm/_logs/2020-11-11T13_43_24_105Z-debug.log
```

**Comment by rijkvanzanten** [comment]
Would you be able to trace where that InitializedSession comes from? VS Code should point you in the right direction 🤔

**Comment by danieljwestman** [comment]
Nope, no hits on InitializedSession. It's nowhere on my machine...

**Comment by danieljwestman** [comment]
![Uploading Skärmavbild 2020-11-11 kl. 15.04.59.png…]()

**Comment by danieljwestman** [comment]
![Skärmavbild 2020-11-11 kl  15 04 59](https://user-images.githubusercontent.com/20950568/98821076-5569ec00-242f-11eb-9732-96d77de7bda7.png)

**Comment by rijkvanzanten** [comment]
In VS Code, under `api/controllers/auth.ts` line 242, what is the type for `req.session`?

On my end, it's `Express.Session` 🤔 

![CleanShot 2020-11-11 at 09 05 11](https://user-images.githubusercontent.com/9141017/98821141-1fac0f80-23fd-11eb-82fa-c648de92559b.png)

**Comment by rijkvanzanten** [comment]
Wait a second, your `index.d.ts` for express-session is different from mine 🤯

**Comment by danieljwestman** [comment]
Okay... why? I copied the repo

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-11-11 at 09 07 48](https://user-images.githubusercontent.com/9141017/98821302-60a42400-23fd-11eb-981c-523cec6c6d36.png)

**Comment by rijkvanzanten** [comment]
Looks like you're on a newer version of the `@types/express-session` package then I am 🤔 

Your screenshot matches the latest state of the source on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-session/index.d.ts

I think that PR might've been an accidental breaking change under a patch release on `@types/express-session`

**Comment by danieljwestman** [comment]
Hm, okay... How come I'm on different version? I'm running the same packa.json file... How to fix this for me now?

**Comment by rijkvanzanten** [comment]
I'll lock the package version to `1.17.0` exactly for the time being

**Comment by danieljwestman** [comment]
That worked out

**Comment by rijkvanzanten** [comment]
Ref https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49484
