### ISSUE TITLE
Error when filtering on revisions

### ISSUE THREAD

**Issue by jojomillennium** [directus/next#949]
v9.0.0 - rc12
When querying on revisions and filtering on data, I get an error.

/revisions?filter[collection]=amenities&filter[item]=la_brasserie&filter[data.status]=published&limit=1
Error :
`{
    "errors": [
        {
            "message": "select \"directus_revisions\".\"id\", \"directus_revisions\".\"activity\", \"directus_revisions\".\"collection\", \"directus_revisions\".\"item\", \"directus_revisions\".\"data\", \"directus_revisions\".\"delta\", \"directus_revisions\".\"parent\" from \"directus_revisions\" where (\"directus_revisions\".\"collection\" = $1 and \"directus_revisions\".\"item\" = $2 and \"directus_revisions\".\"data\".\"status\" = $3) limit $4 - missing FROM-clause entry for table \"data\"",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}`

**Comment by rijkvanzanten** [comment]
`data` isn't a relational field, but a regular text blob. You can't search in the "relationship" `data`, as it doesn't exist.

The best next thing is `filter[data][_contains]=published`

**Comment by jojomillennium** [comment]
@rijkvanzanten 
I tried it out : /revisions?filter[collection]=amenities&filter[item]=la_brasserie&filter[data][_contains]=published

and get the error:
`{
    "errors": [
        {
            "message": "select \"directus_revisions\".\"id\", \"directus_revisions\".\"activity\", \"directus_revisions\".\"collection\", \"directus_revisions\".\"item\", \"directus_revisions\".\"data\", \"directus_revisions\".\"delta\", \"directus_revisions\".\"parent\" from \"directus_revisions\" where (\"directus_revisions\".\"collection\" = $1 and \"directus_revisions\".\"item\" = $2 and \"directus_revisions\".\"data\" like $3) limit $4 - operator does not exist: json ~~ unknown",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}`

and how about the &sort=-delta.date_updated then?

**Comment by rijkvanzanten** [comment]
Same thing, `data` and `delta` are JSON blobs that can't be used like relational fields in the API. Based on the `json ~~ unknown` bit, I'm assuming you're using Postgres?

**Comment by jojomillennium** [comment]
Yes.
What I'm trying to do (maybe there is another way) is to retrieve only the latest published items.
In other words, if I move an item from a collection from status published to draft, I don't want that item to disappear from my website, I still want it to be visible, but its latest published version while I'm working on the updated content (as draft status), until I published a new version.
If my front end only filters published items, once one moves to draft version, it will disappear from my front end.
What would be the best way?

**Comment by jojomillennium** [comment]
edit: Just saw your comment on Discord about 318

**Comment by rijkvanzanten** [comment]
Yeah lets keep this discussion going on https://github.com/directus/next/discussions/318 :) I'd love to hear your use case and your thoughts on how it should / could work
