### ISSUE TITLE
Time format - Short and long displaying same format

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/next#951]
### Environment

* PostgreSQL 9.6-alpine
* Directus RC.12

### Steps to reproduce:

1. Create a field type `Time` with `Display` format `long`

2. Create a field type `Time` with `Display` format `short`

3. Create values to the collection and both times field will contain seconds as the image below shows

**Screenshot:**

<img width="836" alt="issue_951" src="https://user-images.githubusercontent.com/36451129/98828551-1e480a80-2430-11eb-9c53-5f2f399be4dd.png">

**Comment by rijkvanzanten** [comment]
@juancarlosjr97 The screenshot shows the _interface_, not the _display_. The interface has a "Include Seconds" option:

![CleanShot 2020-11-11 at 13 43 19](https://user-images.githubusercontent.com/9141017/98851166-dfac5300-2423-11eb-86e4-508ab098c6d9.png)

**Comment by juancarlosjr97** [comment]
@rijkvanzanten Yes, and regardless if I enable `Include Seconds` or not, it continues showing the Seconds either way.

**Comment by juancarlosjr97** [comment]
Sorry, I just realised you already fix it :)!
