### ISSUE TITLE
Error reading knex dependency on hook using ItemService

### ISSUE THREAD

**Issue by lluishi93** [directus/next#952]
I've a couple of hooks that use the ItemService provided from the context.

What I see is that, using RC-12, this message appears when starting directus:

![image](https://user-images.githubusercontent.com/14786440/98836566-1e510600-2442-11eb-8702-2ffa0bf377cd.png)

Here's how my hooks are set up
![image](https://user-images.githubusercontent.com/14786440/98836629-332d9980-2442-11eb-8853-16dd84af6f38.png)

**Comment by rijkvanzanten** [comment]
The services now require you to pass in a schema object for it to operate on. Try:

```ts
function registerHook({ services, schema }) {
  new services.ItemsService({ schema });
}
```

**Comment by lluishi93** [comment]
Sorry, just tried your solution and I'm getting that `schema` as undefined:

![image](https://user-images.githubusercontent.com/14786440/98839522-e77cef00-2445-11eb-8837-5f3a94649b7b.png)

![image](https://user-images.githubusercontent.com/14786440/98839545-f368b100-2445-11eb-9041-a39b4b83cdce.png)

**Comment by rijkvanzanten** [comment]
Ohh my bad, that schema is passed in the individual hook, not the register function!

```js
function registerHook({ services }) {
  return {
    '<hook>': function({ schema }) {
      const service = new services.ItemsService({ schema });
    }
  };
}
```

**Comment by lluishi93** [comment]
Just to add another fix to that code you posted, in case anyone sees it:

```
function registerHook({ services }) {
  return {
    '<hook>': function({ schema }) {
      const service = new services.ItemsService('collectionName', { schema });
    }
  };
}
```
![image](https://user-images.githubusercontent.com/14786440/98942024-ac35fb00-24ed-11eb-8e83-4d02356345ee.png)

**Comment by benhaynes** [comment]
Is any of this worth adding to the Docs?
