### ISSUE TITLE
Presets are not applied to roles

### ISSUE THREAD

**Issue by botzill** [directus/next#958]
I created a specific preset with a custom fields order, but when I connect with those users, having that roles I still see the fields layout default:

<img width="891" alt="Screen Shot 2020-11-11 at 23 26 03" src="https://user-images.githubusercontent.com/4686040/98866398-8836d300-2475-11eb-9392-f1d0db3c0ee2.png">

while in Preset that layout is different:

<img width="670" alt="Screen Shot 2020-11-11 at 23 28 55" src="https://user-images.githubusercontent.com/4686040/98866464-a7356500-2475-11eb-9471-167622ee2a16.png">

This role has access to presets:

<img width="697" alt="Screen Shot 2020-11-11 at 23 29 54" src="https://user-images.githubusercontent.com/4686040/98866548-c9c77e00-2475-11eb-80b9-5a7404da2054.png">

Any idea why is that?

**Comment by benhaynes** [comment]
Might be a bug, but can you confirm that the users don't have their own personal presets saved? Those would override the global ones. We're also thinking of adding a "Reset to Default" button in the Layout Options, which would clear your personal preset and revert to the role/global ones configured by the admin. 

https://github.com/directus/next/discussions/960

**Comment by rijkvanzanten** [comment]
I just tried this in a fresh install, and it seems to work as expected. I'm going with @benhaynes's working theory on this one. Let me know if that's not the case and we can reopen and investigate @botzill 👍
