### ISSUE TITLE
Ability to edit/delete folders in File Library

### ISSUE THREAD

**Issue by benhaynes** [directus/next#97]
I think this should be a "..." icon (vertical) on the right side of the folder item in the navigation. This would open a menu with:
* "Edit Folder": Opens a popup to rename
* "Delete Folder": Opens popup to confirm... asks if you want to:
    * "Delete Files"
    * "Keep Files" (moves them to root)

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-08-11 at 11 34 42](https://user-images.githubusercontent.com/9141017/89917316-a8c96580-dbc6-11ea-99a5-d70d13fdefaa.png)

The right side of the folder item is already in use for the open/close action for nested folders
