### ISSUE TITLE
META-S Keyboard shortcut not working on User/File Detail

### ISSUE THREAD

**Issue by benhaynes** [directus/next#98]
It tries to save the HTML page. Also, this shortcut should only work when there are staged values to save (save button is enabled)... as of now, it saves a revision every time you press the shortcut.

**Comment by benhaynes** [comment]
It works now, but too well! As of now, there is no validation on this... so if you hit META-S 5 times, you'll get 5 revisions, even if there was nothing to save. This should be based on the same logic as the action button in the header.

**Comment by rijkvanzanten** [comment]
This was added, adding the validation state as a separate issue
