### ISSUE TITLE
Webhook event: items.update.before gives item=null

### ISSUE THREAD

**Issue by botzill** [directus/next#987]
Not sure why, but I get `item=null` for the event `items.update.before`.
All the other data seems ok but this one is `null`. 

is this OK?

**Comment by rijkvanzanten** [comment]
What's the hook that you're trying to use?

I just added this:

```js
module.exports = function registerHooks() {
	return {
		'items.update.before': async function(payload) {
			console.log(payload);
			return payload;
		}
	}
}
```

and it logs as expected

**Comment by botzill** [comment]
I have the following hook:


```
'items.update.before': async function (input, data) {
                try {
                    await axios.post("${items_update_before}", data);
                } catch (error) {
                    throw new InvalidPayloadException(error.message);
                }
            return input
        },
```

Now the payload that I get into the backend has `item=null` which it should be `item=<id>`.

**Comment by rijkvanzanten** [comment]
Oh, you're talking about the `item` field under the context. I see.
