### ISSUE TITLE
No error are shown in the UI

### ISSUE THREAD

**Issue by botzill** [directus/next#990]
Currently, I see no errors in the UI of any kind. I see the in the dev tools error about permission and others, but no error in the UI.

**Comment by rijkvanzanten** [comment]
Can you be more specific? What are you trying to do where that failed?

Errors are shown on a case to case basis

**Comment by botzill** [comment]
Example would be when we get error that we don't have access to item
create. Plus button may still appear we try to ad an item, we get
permission error but not displaying.

**Comment by Fusseldieb** [comment]
I think he meant that when Creating an Item and it fails (for example if a hooh throws an exception) it fails silently. Last time I tried I think I was on rc10 and it just showed "Want to leave this page?" instead of the error.

**Comment by rijkvanzanten** [comment]
That was resolved already in rc.14

**Comment by botzill** [comment]
I still have this issue in rc14

**Comment by botzill** [comment]
@rijkvanzanten can you check this again please, as I have this in rc14 as well. Our API returns back 500 error payload with some custom message. How do we connect that into UI to show errors?

**Comment by Fusseldieb** [comment]
@botzill Rijk is currently aware of this issue (similar to #1010 )

> but without any feedback at UI level

**Comment by rijkvanzanten** [comment]
Closed in favor of #1009
