### ISSUE TITLE
Breaking changes for work around breaking change in @types/express-sesssion...

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#991]
Latest commit 137fba838ddb2d15d89a1d137ea750e976ed7180

@types/express-session@1.17.2

Sorry but I think this release of express-session (yesterday) broke the Directus work around...?

<img width="1029" alt="Skärmavbild 2020-11-13 kl  13 20 30" src="https://user-images.githubusercontent.com/20950568/99072218-e4077600-25b3-11eb-9afe-b256f7b0389d.png">

```
npm run dev

directus: Compilation error in /directus/api/src/controllers/auth.ts
directus: (node:42675) UnhandledPromiseRejectionWarning: Error: ⨯ Unable to compile TypeScript:
directus: src/controllers/auth.ts(2,19): error TS2305: Module '"../../../node_modules/@types/express-session"' has no exported member 'InitializedSession'.
directus:     at Object.<anonymous> (/directus/api/src/controllers/auth.ts:1:7)
```

**Comment by danieljwestman** [comment]
Yep, forcing dependency `@types/express-session` to `1.17.1` is making it work again.

**Comment by rijkvanzanten** [comment]
Are you kidding me :|

**Comment by rijkvanzanten** [comment]
This is the second breaking change in `@types/express-session` in a patch version in a single week. Wild..

Lets see what they respond to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49479#issuecomment-726811331
