### ISSUE TITLE
status query filter not working

### ISSUE THREAD

**Issue by jekuer** [directus/next#993]
The simple REST status filter, as it can be used in V8, does not work with V9 (at least with my tests (RC13, PostgreSQL).
The result can be achieved via the filter param, but at least due to backwards compatibility and since this one could be critical to many, I think it should be fixed.

**Comment by MichaelNussbaumerGOWEST** [comment]
In GraphQL it works for me like that: 

```
query {
    items {
        collection( 
            filter: { 
                _and: [
                    {
                        status: {
                            _in: [
                                "published"
                            ]
                        }
                    },
                    {
                        name: {
                            uuid: {
                                _eq: "test"
                            }
                        }
                    }
                ]
            }
        ) {
            name
        }
    }
}
```

**Comment by rijkvanzanten** [comment]
@jekuer There is no `status` query param. Seeing this is a major version bump (and thus a breaking change), there is no hard requirement for backwards compatibility between v8 and v9. 

(the technical reason here is that there is no system "status" field anymore to begin with)

**Comment by jekuer** [comment]
Ok, I see. Thanks.
