### ISSUE TITLE
API filters does not seems to work properly

### ISSUE THREAD

**Issue by botzill** [directus/next#998]
I have such filters:

```
{
    "filter[status][_eq]": "published",
    "filter[account][id][_eq]": 63
  }
```
which works OK. Now, when I add another filter:

```
{
    "filter[account][status][_eq]": "published",
    "filter[status][_eq]": "published",
    "filter[account][id][_eq]": 63
  }
```

it does return me all the results, which mean it des not apply `"filter[account][id][_eq]": 63`.

I'm doing smth wrong ?

**Comment by benhaynes** [comment]
Rijk would know for sure, but I don't think this is valid:

```
"filter[account][status][_eq]": "published"
```

What is this trying to do? It looks like you have two fields...

**Comment by botzill** [comment]
Well, that's the prob I want to filter by multiple fields in the `account` M2O relation. 

I want `status= published` AND `id=63`

**Comment by benhaynes** [comment]
Ahh, then this should be a "question" within Discussions... not a bug report. 😉

**Comment by botzill** [comment]
I thought it should work like this. Filtering by multiple filters is not yet implemented ?

**Comment by benhaynes** [comment]
Hmm, I'm not sure — you might need to use the "AND" or "OR"s... I'll defer to @rijkvanzanten on the exact syntax (if this is supported). In any event, this is a documentation issue... especially since our Docs for v9 aren't really finished/live yet. 😆
